### ISSUE TITLE
Reinforcement learning folder seems to be empty

### ISSUE THREAD

**Issue by ceoworks** [stefan-jansen/machine-learning-for-trading#1]
Is it intentionally or some code is missing?

https://github.com/stefan-jansen/machine-learning-for-trading/tree/master/20_reinforcement_learning

**Comment by stefan-jansen** [comment]
Chapters 16-20 are still in the works and will become available one-by-one over the coming 2-3 weeks, both content and code.

**Comment by stefan-jansen** [comment]
Sorry for the delay, but the code is finally complete and the updated online chapters should be available tomorrow.
