### ISSUE TITLE
RemoveError: 'requests' is a dependency of conda and cannot be removed from conda's operating environment.

### ISSUE THREAD

**Issue by msarm** [stefan-jansen/machine-learning-for-trading#10]
```
conda env create -f environment_mac_osx.yml --force
Collecting package metadata: done
Solving environment: done
Preparing transaction: done
Verifying transaction: failed
```

```
RemoveError: 'requests' is a dependency of conda and cannot be removed from
conda's operating environment.
```

**Comment by stefan-jansen** [comment]
See discussion: https://github.com/conda/conda/issues/8149

Running `conda update conda` before creating the env has worked for some that experienced this recent OSX bug according to the comments. Please let me know if this doesn't work.

**Comment by msarm** [comment]
Yes, it worked after adding "--force"

1. ran conda update first
`conda update conda --force`

2. ran conda to create environment with --force since it failed earlier at the end
`conda env create -f environment_mac_osx.yml --force`
