### ISSUE TITLE
Chapter 5: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by N2Network** [stefan-jansen/machine-learning-for-trading#102]
I downloaded the Docker image so I'm not sure why I'm running into so many difficulties with these notebooks. I'm trying to run the following code and getting an error:

`returns, positions, transactions = extract_rets_pos_txn_from_zipline(backtest)`

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-c71c73c9a39d> in <module>
----> 1 returns, positions, transactions = (backtest)

ValueError: too many values to unpack (expected 3)

**Comment by stefan-jansen** [comment]
There is an issue with different pyfolio versions, the (older, I believe) returns an additional DataFrame with leverage information. Use 
```
returns, positions, transactions, _ = extract_rets_pos_txn_from_zipline(backtest)
```
instead or capture the fourth DataFrame using an actual variable if interested to see what it looks like. In Jupiter notebooks you can place the cursor after a function name and hit shift + enter to see the documentation, it'll say what exactly is being returned. I urgently need to update the Docker image for this and a couple other inconsistencies, sorry about the frustration.

Feel free to reopen if this does not resolve the problem.
