### ISSUE TITLE
pandas wont read my custom date time index for splitting data  y_train = y[:'2020-01-16 22:00:00+00:00']

### ISSUE THREAD

**Issue by cody-vandervoort** [stefan-jansen/machine-learning-for-trading#103]
Using 4h data on the gbpjpy pair, I'm able to get up to this point all clear 
![image](https://user-images.githubusercontent.com/59127741/108617658-215a7b80-73cd-11eb-8f9c-52bfa1d9dbbf.png)

yet once i try to split I am unable make any format of the date and time able to parse the data correctly, i have made the DATE column the index, i tried everything using an underscore for a space, or a colon, as well as just the year ect, might you have something you could recommend for me or perhaps another way to format the data so I can make it work?
![image](https://user-images.githubusercontent.com/59127741/108617724-7d250480-73cd-11eb-9686-114dd5c6d241.png)

**Comment by stefan-jansen** [comment]
The plot looks like your index are strings instead datetime - see answer [here] for how to address this.

**Comment by cody-vandervoort** [comment]
Hi thanks, the link didn't show in your 
'here' statement though

**Comment by cody-vandervoort** [comment]
i think i found a video thought!

**Comment by stefan-jansen** [comment]
updated above.

**Comment by cody-vandervoort** [comment]
Awesome thank you!!

**Comment by cody-vandervoort** [comment]
Is it possible to give me recommendations on what I have done wrong according to the picture below, it seems it's all a black line rather than seeing the seperate blue line for the predictions 

![image](https://user-images.githubusercontent.com/59127741/108640273-8786e300-744d-11eb-9ae0-6c54b806a3ea.png)

**Comment by cody-vandervoort** [comment]
Is it possible to give me recommendations on what I have done wrong according to the picture below, it seems it's all a black line rather than seeing the seperate blue line for the predictions 

![image](https://user-images.githubusercontent.com/59127741/108640273-8786e300-744d-11eb-9ae0-6c54b806a3ea.png)

**Comment by stefan-jansen** [comment]
Your `df.info()` output suggests there are only 6 test predictions. Is this intentional? May not be visible.

When pasting code, please format by enclosing in triple backticks like "```":
```
df.info()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
a    2 non-null int64
b    2 non-null int64
dtypes: int64(2)
memory usage: 112.0 bytes
```

**Comment by cody-vandervoort** [comment]
Okay, will do, my bad, only 6 predictions was not intentional, 
![image](https://user-images.githubusercontent.com/59127741/108641129-7c828180-7452-11eb-9e86-f9acb8a5fa60.png)
i was able to get this plotted im trying to read back over everything and see what i did wrong according to the origional notebook, I will make some tweaks do you know where the error may lay if i can't get the test predictions plotted, in the data frame it says NAN for all the spots, i will try changing the training and test sets around i suppose perhaps i made them too small

**Comment by cody-vandervoort** [comment]
![image](https://user-images.githubusercontent.com/59127741/108642808-37634d00-745c-11eb-91ac-6964b2b4441e.png)

I seem to be heading in the right direction sort of now

**Comment by cody-vandervoort** [comment]
I see how we make the predictions on historical data but how do we use this notebook to forecast N number of time steps into the future? Sorry if im missing something obvious

**Comment by stefan-jansen** [comment]
There may be something off where you select the periods for train/test. If you want to forecast beyond a test period where you have features already, you need to forecast the inputs. With a 1-step forecast that only takes the lagged output as input (t-1 to predict t), you need to predict t+1, then use t+1 to predict t+2, etc. If you have more inputs, you need to forecast those as well. Alternatively, you can train a model to predict 10 steps ahead and compare what works better.

**Comment by cody-vandervoort** [comment]
Might you be able to assist me by writing me a short code snippet of how I might add that into the notebook? I will give it my best shot in figuring it out though, I appreciate sharing thank you

**Comment by stefan-jansen** [comment]
I think your selection / indexing approach was fine, you just needed to create a `DateTimeIndex` first as illustrated in the linked answer. Closing this for now, please reopen if you encounter any problems with the code in the notebooks.

**Comment by cody-vandervoort** [comment]
When making the sythetic data in chapter 21 when persisting the auto encoder, I get this error explanation at the bottom, 
Expected binary or unicode string, got PosixPath('time_gan/experiment_00/autoencoder') just wondering if it runs fine with this?

Also with regards to my other question I had done the `DateTimeIndex` and such, I got the data to fit everything nicely but my question was towards predicting the future time steps ahead with what you said _**With a 1-step forecast that only takes the lagged output as input (t-1 to predict t), you need to predict t+1, then use t+1 to predict t+2, etc. If you have more inputs, you need to forecast those as well. Alternatively, you can train a model to predict 10 steps ahead and compare what works better.**_ Do I need to create a dataframe with empty future dates so I see the predictions filled in those columns when I run the model because for what I see is I'm not receiving any value for a prediction for any date pasts the last historical price, My apologies If I am off track but I am confused how I get the prediction for the future time steps, and which piece of code to edit in the notebook to do so, as the S&P example seemed the same, how do I use the model for inference do I feed it the empty timeslots for tomorrows price?

**Comment by cody-vandervoort** [comment]
In order to calculate forward returns with the RNN do I fit this piece of code somewhere in the notebook? `for t in [1,2,3,6,12]:
data[f'target_{t}m'] = (data.groupby(level='ticker')
[f'return_{t}m'].shift(-t))
`
