### ISSUE TITLE
tensorflow and matplotlib version look incompatible

### ISSUE THREAD

**Issue by sungyunglim** [stefan-jansen/machine-learning-for-trading#104]
using ml4t-dl dock container to run deep learning (01) and (02) codes. It works for 01_build_and_train_feedforward_nn but does not work for 02_how-to-use-tensorflow because a module of tensorflow-estimator (2.2.0) is no recognized (I forget writing down the specific error. I would try again to find this). The solution suggested at a website is to downgrade tensorflow-estimator 2.1.0. When I do this, I experience a new error that matplotlib is not recognized. Did you experience this kind of error before ?

Now, I'm trying to upgrade to tensorflow 2.2.0 but this attempt looks failing due to some dependencies.

I read your book without running scripts. Now I'm attempting to run some from deep learning chapter. I appreciate for your effort to detail financial machine learning. I've learned a lot.

**Comment by sungyunglim** [comment]
One of your responses says that this is a known issue. Would you point me to the updated docker container with tensorflow 2.2 ?
Thanks

**Comment by stefan-jansen** [comment]
Thank you. There's indeed a problem with the `ml4t-dl` environment as you discovered. Sorry about that, not sure how the wrong versions got on the image, the local environment file I have lists TF 2.2 as expected. I'll update in the next couple of days.
