### ISSUE TITLE
data: nasdaq link expired

### ISSUE THREAD

**Issue by Eeonum** [stefan-jansen/machine-learning-for-trading#105]
In create_dataset.py the following url is expired. What is the new one?

`url = 'https://www.nasdaq.com/market-activity/stocks/screener?letter=0&exchang={}&render=download'
`

**Comment by stefan-jansen** [comment]
Unfortunately, NASDAQ has disabled automatic downloads, but manual access via the url listed in the dataset creation guide is still available. I've updated the instructions [here](https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/data/create_datasets.ipynb) accordingly.
