### ISSUE TITLE
glove_word_vectors.py

### ISSUE THREAD

**Issue by Eeonum** [stefan-jansen/machine-learning-for-trading#106]
This code doesn't generate any results.

"glove_word_vectors.py"

**Comment by stefan-jansen** [comment]
Thank you. Could you please let me know where you came across this?

**Comment by Eeonum** [comment]
In the data folder when trying to run this code to use in later chapter. The code does generate a folder but there is nothing inside it.

**Comment by stefan-jansen** [comment]
Thank you for letting me know, revised and updated.
