### ISSUE TITLE
issue with cerebro adddata. Ex chap 08-03. Backtrader.

### ISSUE THREAD

**Issue by luisvelo** [stefan-jansen/machine-learning-for-trading#111]
Hi Stefan

I'm on a Python 3.5 environment for backtrader on Catalina, run the below code "almost as is" 

https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/08_ml4t_workflow/03_backtesting_with_backtrader.ipynb

But Cerebro is loading just the LAST dataframe, is ignoring all the rest of the data loads. I.e.: tests just one stock.

for ticker in tickers:
    df = data.loc[idx[ticker, :], :].droplevel('ticker', axis=0)
    df.index.name = 'datetime'
    bt_data = SignalData(dataname=df)
    cerebro.adddata(bt_data, name=ticker)

I've read some backtrader docs here and there and I was not able to find any alternative ... can you help?

Thanks in advance

**Comment by stefan-jansen** [comment]
Hi @luisvelo, just to make sure I understand you correctly: are you saying the example in the notebook uses only a single stock (but the position breakdown tearsheet shows various asset) or that a modified version of the code only uses a single stock?

**Comment by luisvelo** [comment]
Hi Stefan

I'm using a conda environment in Catalina with Python 3.5 to be able to run your code. The issue is that Cerebro loads just the last one of these cerebro.adddata(bt_data, name=ticker), actually "YUM" ticker. I do not see several stocks on Pyfolio like on your example.

I had issues on the below lines, of your code, had to do minor modifications:
df = data.loc[idx[ticker, :], :].droplevel('ticker', axis=0)
return f'{h:>02.0f}:{m:>02.0f}:{s:>02.0f}
self.log(f'{order.data._name},BUY executed,{p:.2f}')  --- all of the self.log code lines do not compile on my environment
print - all the print lines fail

Then:
1- If you have a solution - suggestion I'll be glad. I did the tutorials on backtrader website, but have not found any code (yet) that uses several tickers
2- What version of OS/Python do you use to run backtrader?
3- Is there any forum (as far as you know) for the "readers of Stefan's books"? I've seen many forks on Github: anyone that you recommend or something like that? (like on the website of your publisher or whatever else)

Grusse
Luis

**Comment by stefan-jansen** [comment]
Hey Luis, 
the latest docker images use Python 3.8 for a single `ml4t` environment that covers all notebooks EXCEPT for those using Zipline; the `backtest` environment now uses 3.6 - all on Ubuntu 20.04 but via Docker runs on all platforms. 

I've recently tested the backtrader notebook and it produced the same result; could you pls try and run it with the docker image or an environment that uses more recent version? 3.5 should only be necessary for Zipline.

I'm actually planning on adding Discourse to www.ml4trading.io to facilitate some discussion given that there are quite a few folks using the notebooks by now and it would be great to facilitate some exchange. Hopefully before the end of this month..

Saludos, Stefan

**Comment by luisvelo** [comment]
Hi Stefan

Always referring to:

https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/08_ml4t_workflow/03_backtesting_with_backtrader.ipynb

I'm on Catalina and on Python 3.8 now, and I'm able to execute the worksheet in Spyder (Matplotlib on 3.2.2 as there is a known bug and otherwise backtrader graph does not appear).

Backtrader finally is able to complete the work.

I have some issues with Pyfolio (on version 0.9.2), I went to your yml for MacOSX at 

https://github.com/stefan-jansen/machine-learning-for-trading/blob/783181133adb24748f2dd30a6e4c0cff45f4caf5/installation/macosx/ml4t.yml

and found the below info about pyfolio but the link is broken
 - git+https://github.com/stefan-jansen/pyfolio.git@2676831e7a6e9badb4054695f72ca03d381c4713#egg=pyfolio

I have issues with the "returns" df on pyfolio
returns
2015-03-06 00:00:00+00:00    0.0
2015-03-09 00:00:00+00:00    0.0
2015-03-10 00:00:00+00:00    0.0
2015-03-11 00:00:00+00:00    0.0
2015-03-12 00:00:00+00:00    0.0

2018-02-21 00:00:00+00:00    0.0
2018-02-22 00:00:00+00:00    0.0
2018-02-23 00:00:00+00:00    0.0
2018-02-26 00:00:00+00:00    0.0
2018-02-27 00:00:00+00:00    0.0

transactions df seems ok

transactions
                           amount       price  sid symbol       value
date                                                                 
2015-03-23 00:00:00+00:00      -7   54.143327    0    AAL  379.003292
2015-03-23 00:00:00+00:00       3  121.237763    3   AAPL -363.713288
2015-03-23 00:00:00+00:00      -7   53.308413   12    AIG  373.158889
2015-03-23 00:00:00+00:00      -2  158.790982   18   AMGN  317.581963
2015-03-23 00:00:00+00:00       4   92.563822   19    AMT -370.255288
                          ...         ...  ...    ...         ...
2018-02-01 00:00:00+00:00       3  119.220000  232    UPS -357.660000
2018-02-01 00:00:00+00:00       7   54.490000  238     VZ -381.430000
2018-02-01 00:00:00+00:00      -4   87.430000  240    WDC  349.720000
2018-02-01 00:00:00+00:00      -2  166.010000  245   WYNN  332.020000
2018-02-01 00:00:00+00:00       4   87.500000  247    XOM -350.000000

And positions also does not look great 
returns
                           YUM          cash
Datetime                                    
2015-03-06 00:00:00+00:00  0.0  10000.000000
2015-03-09 00:00:00+00:00  0.0  10000.000000
2015-03-10 00:00:00+00:00  0.0  10000.000000
2015-03-11 00:00:00+00:00  0.0  10000.000000
2015-03-12 00:00:00+00:00  0.0  10000.000000
...                        ...           ...
2018-02-21 00:00:00+00:00  0.0   9878.879095
2018-02-22 00:00:00+00:00  0.0   9878.879095
2018-02-23 00:00:00+00:00  0.0   9878.879095
2018-02-26 00:00:00+00:00  0.0   9878.879095
2018-02-27 00:00:00+00:00  0.0   9878.879095

Can you share the library versions of your Catalina environment? Do you execute on Spyder or on Jupyter while on Catalina?

Side question: are you using an M1 Mac already?

Danke noch einmal
Luis

**Comment by stefan-jansen** [comment]
I have tried installing Zipline on Mac OSX with M1 and failed; I'm using either Ubuntu directly or via Docker. The Docker images uses [this](https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/installation/macosx/ml4t.yml) file to create the `ml4t` environment. The Pyfolio 'link' works when used like so:
```
pip install git+https://github.com/stefan-jansen/pyfolio.git@2676831e7a6e9badb4054695f72ca03d381c4713#egg=pyfolio
```
It's a reference to commit id `2676831e7a6e9badb4054695f72ca03d381c4713`; to view the commit you would go [here](https://github.com/stefan-jansen/pyfolio/commit/2676831e7a6e9badb4054695f72ca03d381c4713).

I've run the backtrader notebook again without issues using the `ml4t` environment contained in the latest Docker container, and the pyfolio output does not appear unusual. I would recommend you give this a try; it's hard to predict which versions will be install or which errors installing certain libraries will produce since some require compilation and are hence dependent on non-Python software installed for your OS. That should not prevent you from trying to do so and it may just work, it's just difficult for me to anticipate issues or provide very customized advice.

**Comment by stefan-jansen** [comment]
Closing this for now - feel free to reopen if you run into further issues.
