### ISSUE TITLE
Chapter 8: data_prep.py

### ISSUE THREAD

**Issue by N2Network** [stefan-jansen/machine-learning-for-trading#112]
What is the process of running data_prep.py? I thought I would run in shell `python data_prep.py` but it kicked out an error about numpy. Then I thought i could just rename it `.ipynb` didn't work either. Also tried `%run '00_data/data_prep.py'` in a new notebook, no luck.

 Can someone help me out?

**Comment by stefan-jansen** [comment]
The file should run in the python shell using the `ml4t` environment; it just loads data created in ch 7, combines it with the Quandl data and saves it to run the backtests in ch 8. Could you pls post the error message?

**Comment by N2Network** [comment]
Hmmm, looks like it worked today. I must have had a typo before. 

```
(ml4t) packt@a20fd7fbed78:~/ml4t/08_ml4t_workflow/00_data$ python data_prep.py
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 190451 entries, ('AAL', Timestamp('2014-12-09 00:00:00')) to ('YUM', Timestamp('2017-11-30 00:00:00'))
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   predicted  74054 non-null   float64
 1   open       190451 non-null  float64
 2   high       190451 non-null  float64
 3   low        190451 non-null  float64
 4   close      190451 non-null  float64
 5   volume     190451 non-null  float64
dtypes: float64(6)
memory usage: 14.6+ MB
None
(ml4t) packt@a20fd7fbed78:~/ml4t/08_ml4t_workflow/00_data$
```
