### ISSUE TITLE
chapter 8. 00_data: data_prep.py

### ISSUE THREAD

**Issue by life-elixir** [stefan-jansen/machine-learning-for-trading#121]
the above code doesn't store any backtest.h5 using ml4t environment.

This is my output:

`94161a326468:/opt/conda/envs/backtest/bin/python -u /opt/project/machine-learning-for-trading/08_ml4t_workflow/00_data/data_prep.py
<class 'pandas.io.pytables.HDFStore'>
File path: ../../07_linear_models/data.h5
/model_data            frame        (shape->[2904233,69])

Process finished with exit code 0`

**Comment by stefan-jansen** [comment]
Right, sorry, there was an `exit()` left from testing. Removed and parameterrized the function so you can use it with different  (lr/ridge/lasso) predictions generated in notebook `05_predicting_stock_returns_with_linear_regression.ipynb` in chapter 7.
