### ISSUE TITLE
Error in Chapter 6 "01_machine_learning_workflow.ipynb"

### ISSUE THREAD

**Issue by guillempuche** [stefan-jansen/machine-learning-for-trading#122]
Jupyter throws an error here:

![imatge](https://user-images.githubusercontent.com/3519924/111077614-e6da8f00-84f1-11eb-96ff-d447dcfef8a0.png)

**Comment by stefan-jansen** [comment]
I think the code has already changed in the current version, I updated this cell a few days ago to read:
```python
correl = X.apply(lambda x: spearmanr(x, y)[0])
correl.sort_values().plot.barh();
```
Please run `git pull` to download the latest notebooks.

Closing for now as probably already resolved; feel free to reopen if you continue to experience any issues.
