### ISSUE TITLE
yelp review dataset

### ISSUE THREAD

**Issue by life-elixir** [stefan-jansen/machine-learning-for-trading#123]
the parquet_dir needs to be changed to yelp_dir. the modified code is:

`yelp_dir = Path('yelp')`

**Comment by stefan-jansen** [comment]
Sorry, which notebook/cell?

**Comment by life-elixir** [comment]
`yelp_dir = Path('yelp')

if not yelp_dir.exists():
    parquet_dir.mkdir(exist_ok=True)`

Notebook` data/create_yelp_review_data.ipynb`

**Comment by life-elixir** [comment]
parquet_dir.mkdir(exist_ok=True) should be yelp_dir.mkdir(exist_ok=True)

**Comment by stefan-jansen** [comment]
Got it, thanks & fixed. 

By the way, feel free to just create a pull requests if you come across errors like this (I hope you won't but...).
