### ISSUE TITLE
docker password

### ISSUE THREAD

**Issue by life-elixir** [stefan-jansen/machine-learning-for-trading#124]
Is there anyway I can have the password for the docker? I need to install some packages such as vim to view the codes in my terminal. Thanks for your help Stefan!

**Comment by stefan-jansen** [comment]
See [here](https://stackoverflow.com/questions/59376888/become-root-in-a-docker-container) for how to run docker as root; once logged in you can install software using the passwd you created. Note you may have to run `docker start ml4t` first if the container has stopped and you get `... is not running` errors.
