### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by JeremyWhittaker** [stefan-jansen/machine-learning-for-trading#128]
I'm running the Docker image on Windows and following the instructions located [here](https://github.com/stefan-jansen/machine-learning-for-trading/blob/a0687ed91d7773e2f713fe00271cd84c6c325739/installation/README.md)

It states to run this command:
```
conda activate backtest
zipline ingest
```

This command generates the file structure `machine-learning-for-trading\data\.zipline\data\quantopian-quandl\2021-03-19T05;15;50.759963`

Then in chapter 4: 04_single_factor_zipline

This fails indicating it can't find any data. 

I had to run `zipline ingest -b quandl`

Which generated this file structure `machine-learning-for-trading\data\.zipline\data\quandl\2021-03-19T05;24;40.654332`

Then the notebook ran fine.

**Comment by stefan-jansen** [comment]
That's right, sorry about the oversight,I have updated the instructions accordingly.
