### ISSUE TITLE
ModuleNotFoundError: No module named 'matplotlib'

### ISSUE THREAD

**Issue by JeremyWhittaker** [stefan-jansen/machine-learning-for-trading#129]
I'm working on notebook - 06_performance_eval_alphalens in chapter 4. 

I've done `conda activate backtest`

The error I'm getting is `ModuleNotFoundError: No module named 'matplotlib'`

So I added a line above the code `!conda install -n backtest matplotlib -y`

It appears to have ran successfully. When I run a second time I get this. 
```
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```
But I still get `ModuleNotFoundError: No module named 'matplotlib'`

Any thoughts on how I can fix this?

**Comment by stefan-jansen** [comment]
I can only replicate this when I run the notebook with the`'root` (`base`) environment, which indeed does not have `matplotlib` installed. When I run it with the `backtest` environment, it works fine. You can switch the kernel in the 'Kernel' menu under 'Change Kernel'.
![conda_backtest](https://user-images.githubusercontent.com/4275885/111792232-6f628200-889a-11eb-8352-8d9c56b6ec81.png)
![conda_root](https://user-images.githubusercontent.com/4275885/111792234-6ffb1880-889a-11eb-9138-86e7f066f6b3.png)

Feel free to reopen if this doesn't work out.

**Comment by JeremyWhittaker** [comment]
Thank you sir. I assumed I could run conda activate backtest before launching lab in the console. I didn't realize I had to also select this within each notebook. As always I appreciate your quick responses.

**Comment by stefan-jansen** [comment]
You shouldn't have to, usually the kernel will be the one for the environment you activated before launching the notebook, not sure what happened.
