### ISSUE TITLE
chap 02/04/edgar_xbrl.ipynb

### ISSUE THREAD

**Issue by Eeonum** [stefan-jansen/machine-learning-for-trading#133]
**Describe the bug**
FSN needs to be replaced by FSN_PATH
FSN_PATH has one '' missing

`TypeError                                 Traceback (most recent call last)
<ipython-input-10-6ec517cad89f> in <module>
     10     if this_year == 2020 and q == 1:
     11         url = SEC_URL + 'files/node/add/data_distribution/' + filing
---> 12     response = requests.get().content
     13     try:
     14         with ZipFile(BytesIO(response)) as zip_file:

TypeError: get() missing 1 required positional argument: 'url'
`
**To Reproduce**
- In case you are not running the current version of the notebook/script as found on GitHub.
`for i, (yr, qtr) in enumerate(filing_periods[-4: -3], 1):
    print(f'{yr}-Q{qtr}', end=' ', flush=True)
    filing = f'{yr}q{qtr}_notes.zip'
    path = data_path / f'{yr}_{qtr}' / 'source'
    if not path.exists():
        path.mkdir(exist_ok=True, parents=True)
    url = SEC_URL + FSN_PATH + filing
    
    # 2020q1 is currently (Oct 2020) in a different location; this may change at some point
    if this_year == 2020 and q == 1:
        url = SEC_URL + 'files/node/add/data_distribution/' + filing
    response = requests.get().content
    try:
        with ZipFile(BytesIO(response)) as zip_file:
            for file in zip_file.namelist():
                local_file = path / file
                if local_file.exists():
                    continue
                with local_file.open('wb') as output:
                    for line in zip_file.open(file).readlines():
                        output.write(line)
    except BadZipFile:
        'https://www.sec.gov/files/node/add/data_distribution/2020q1_notes.zip'
        print('got bad zip file')
        continue`

**Expected behavior**

**Screenshots**

**Environment**
ml4t 
- OS: [e.g. MacOSX, Windows, Ubuntu]
 - Version [e.g. Big Sur, 10, 20.04]

**Additional context**

**Comment by stefan-jansen** [comment]
Thanks, updated accordingly.
