### ISSUE TITLE
Chapter 09, Notebook 07_Pairs_Trading_Backtest Run Strategy Returns No Output

### ISSUE THREAD

**Issue by toddjm** [stefan-jansen/machine-learning-for-trading#136]
**Describe the bug**
Using the ml4t Docker latest environment, steps in notebooks in Chapter 09 - specifically, 05 and 06 - have been successfully completed. All data was collected properly before execution. In notebook 07, cell 15 does not return any data, either to the Jupyter notebook or to the bt_log.csv file (empty except headers).

**To Reproduce**
Run exactly the latest version from GitHub and in the ml4t branch, in the latest Docker container

1. Execute notebooks 05, 06, and 07 in Chapter 9 after gathering the data per the notebooks in the data directory
2. See this:

<img width="785" alt="Screen Shot 2021-03-25 at 8 40 51 PM" src="https://user-images.githubusercontent.com/12463984/112565063-66961280-8daa-11eb-815b-0c19451303ab.png">

3. Note there is no error until you reach 
<img width="1089" alt="Screen Shot 2021-03-25 at 8 41 38 PM" src="https://user-images.githubusercontent.com/12463984/112565124-82011d80-8daa-11eb-94aa-00f27416bd9b.png">

4. Verify that results[0].exposure is not populated
<img width="1102" alt="Screen Shot 2021-03-25 at 8 43 24 PM" src="https://user-images.githubusercontent.com/12463984/112565259-c096d800-8daa-11eb-9b79-438a97652af8.png">

5. Prices, trades, etc. are all populated as expected

**Expected behavior**
I expect to see the reproduction as illustrated in the notebooks, namely starting and ending trades and P&L

**Environment**
Linux, ml4t branch

REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
appliedai/packt           latest              f50b79f77282        2 weeks ago         9.59GB

**Additional context**

**Comment by stefan-jansen** [comment]
@toddjm apologies for the delay. I'm getting the same error with the new Docker image, not sure how this slipped through testing. I need to take a closer look; backtrader development has slowed down since July last year and the issues page is locked. 

I suspect that some pandas update result in backtrader not picking up on the trading signals as I get the same error with the data that produced the output you can see in the notebook on GitHub. I'll go back to this next week; again, sorry for the delay. On the other hand, using the old Docker image or simply downgrading version might help sooner.

**Comment by toddjm** [comment]
@stefan-jansen Thank you so much for looking into this, don't apologize (you do have a day job :)). Many thanks for your attention and kudos on the book: it's very, very helpful!

**Comment by stefan-jansen** [comment]
Finally got around to it! Simple fix - backtrader no longer finds `date`:
```
    def next(self):
        self.today = self.datas[0].datetime.date()
```
has to be 
```
    def next(self):
        self.today = pd.Timestamp(self.datas[0].datetime.date())
```
I'll push the version in the coming days once I'm done testing the new environment files.

Closing for now - please feel free to reopen if you run into further issues.
