### ISSUE TITLE
Trouble creating environment from ml4t.yml & ml4t-zipline.yml

### ISSUE THREAD

**Issue by dev-rrusso** [stefan-jansen/machine-learning-for-trading#137]
Hi - I’m on a Windows machine running Python 3.7 using Anaconda.  Per the installation instructions I’m trying to create an environment with ml4t.yml & ml4t-zipline.yml - from a conda prompt I do “conda env create -f ml4t.yml” but I get a “ResolvePackageNotFound: libgfortran=3” error & thus I’ve been stuck now for a week unable to move through the book unfortunately.  

I’ve tried installing libgfortran via pip & otherwise to remedy but no luck.  I also have an error when trying to create the environment for ml4t-zipline.yml using ‘conda env create -f ml4t-zipline.hml’

I have pictures of the output I receive from each of these attempts.  I have the yml files in root C:/ directory & that’s the directory i’m in when running the commands.

Please help! I want to continue moving forward through the book & not be stuck 😥.

Output:
![55C5788C-1831-4817-B723-BD1C55221CC7](https://user-images.githubusercontent.com/61920073/113530054-116cb480-9593-11eb-88a7-3861a891fad0.jpeg)
![11BC3BFC-7402-4198-A2DE-6A420007E6FE](https://user-images.githubusercontent.com/61920073/113530056-12054b00-9593-11eb-8ef0-caa07c422819.jpeg)
![FF47D80F-9C42-418A-97E0-26A1BEE926C8](https://user-images.githubusercontent.com/61920073/113530060-13cf0e80-9593-11eb-8180-ff0567b2577f.jpeg)

**Comment by stefan-jansen** [comment]
The [current](https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/installation/windows/ml4t.yml) `ml4t.yml` doesn't have `libgfortran`; it was updated late February.

I've just run the current `ml4t.yml` file (which does not have version constraints) and built an environment on Windows 10 with miniconda3 just fine. I've exported the environment and used it to update the generic version under [windows/ml4t.yml](https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/installation/windows/ml4t.yml. Check the commit history for changes.

The good news is that I've published a new Zipline version that runs on current Python 3.7+ versions incl. for Windows via conda, so things will get simpler soon. I'll update the installation instructions accordingly. 

Hope this helps; closing for now, cfeel free to reopen if you run into additional issues on this matter.

**Comment by dev-rrusso** [comment]
looks like it built the environment and we’re firing on all cylinders.  thanks for the reply & for all the great material in the book! pure gold!
