### ISSUE TITLE
link might not be correct

### ISSUE THREAD

**Issue by CodeMonkeysGottaCode** [stefan-jansen/machine-learning-for-trading#14]
I cannot run https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/data/create_datasets.ipynb

I get a KeyError: 'code' in the section were we download the Wiki Prices Metadata.

It seems like that the link (https://www.quandl.com/databases/WIKIP/documentation) in section 3.1 is also pointing towards the prices data set while it should point towards a data set with meta data. The referenced data set does not contain the required 'code' and 'name' columns.

Has the meta data been moved?

**Comment by stefan-jansen** [comment]
That's right, Quandl no longer makes this information available. I've added the `wiki_stocks.csv` file and updated the `create_datasets` notebook.

**Comment by CodeMonkeysGottaCode** [comment]
Thank you!
