### ISSUE TITLE
Chapter 4.6 Alphalense pickle file

### ISSUE THREAD

**Issue by Greedy-Vulture** [stefan-jansen/machine-learning-for-trading#145]
The line:

`performance = pd.read_pickle('single_factor.pickle')`

The single_factor.pickle file seems to be missing.

**Comment by stefan-jansen** [comment]
This file is the result of running the notebook [single_factor_zipline.](https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/04_alpha_factor_research/04_single_factor_zipline.ipynb). I've added a hint to the notebook to clarify this.
