### ISSUE TITLE
Chapter 12 - Boosting - "IndexError: list index out of range"

### ISSUE THREAD

**Issue by dev-rrusso** [stefan-jansen/machine-learning-for-trading#146]
I've been unable to get the Baseline Classifier to run through without giving me the following error:

Input: 
```
fname = results_path / f'{algo}.joblib'
if not Path(fname).exists():
    dummy_cv_result, run_time[algo] = run_cv(dummy_clf)
    joblib.dump(dummy_cv_result, fname)
else:
    dummy_cv_result = joblib.load(fname)
```

Output:
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   0 out of   0 | elapsed:    0.9s finished
Traceback (most recent call last):

  File "<ipython-input-339-6e48bed8b374>", line 3, in <module>
    xbg_cv_result, run_time[algo] = run_cv(xgb_clf)

  File "<ipython-input-285-addb10ae68ad>", line 3, in run_cv
    scores = cross_validate(estimator=clf,

  File "C:\ProgramData\Miniconda3\envs\ml4t\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)

  File "C:\ProgramData\Miniconda3\envs\ml4t\lib\site-packages\sklearn\model_selection\_validation.py", line 260, in cross_validate
    results = _aggregate_score_dicts(results)

  File "C:\ProgramData\Miniconda3\envs\ml4t\lib\site-packages\sklearn\model_selection\_validation.py", line 1675, in _aggregate_score_dicts
    for key in scores[0]

IndexError: list index out of range

I thus am getting the same error when I go to run the Random Forest, AdaBoost, etc.  Been stuck for a few days with no solution. Please send help.   Thanks.

**Comment by dev-rrusso** [comment]
For reference this is what I have in run_cv thats used above..

def run_cv(clf, X=X_dummies, y=y, metrics=metrics, cv=cv, fit_params=None, n_jobs=-1):
    start = time()
    scores = cross_validate(estimator=clf,
                            X=X,
                            y=y,
                            scoring=list(metrics.keys()),
                            cv=cv,
                            return_train_score=True,
                            n_jobs=n_jobs,
                            verbose=1,
                            fit_params=fit_params)
    duration = time() - start
    return scores, duration

Also:

metrics = {'balanced_accuracy': 'Accuracy' ,
           'roc_auc': 'AUC',
           'neg_log_loss': 'Log Loss',
           'f1_weighted': 'F1',
           'precision_weighted': 'Precision',
           'recall_weighted': 'Recall'
           }

cv = OneStepTimeSeriesSplit(n_splits=12,
                            test_period_length=1,
                            shuffle=False)

And:
dummy_clf = DummyClassifier(strategy='stratified',
                            random_state=42)
algo = 'dummy_clf'

**Comment by stefan-jansen** [comment]
I just re-ran the notebook to test a new environment file without any issues. The most likely culprit is that your data does not have the right format - could you please compare your output or `X_factors.info()` with the version displayed in the Load Data section in [the notebook](https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/12_gradient_boosting_machines/01_boosting_baseline.ipynb)?

**Comment by dev-rrusso** [comment]
Here is my X_factors.info() & the notebook's Load Data version:

Ran directly following 'indexerror: list index out of range' error:

X_factors.info()
<class 'pandas.core.frame.DataFrame'>
MultiIndex: 358914 entries, ('A', Timestamp('2001-01-31 00:00:00')) to ('ZUMZ', Timestamp('2018-02-28 00:00:00'))
Data columns (total 28 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   return_1m      358914 non-null  float64
 1   return_2m      358914 non-null  float64
 2   return_3m      358914 non-null  float64
 3   return_6m      358914 non-null  float64
 4   return_9m      358914 non-null  float64
 5   return_12m     358914 non-null  float64
 6   Mkt-RF         358914 non-null  float64
 7   SMB            358914 non-null  float64
 8   HML            358914 non-null  float64
 9   RMW            358914 non-null  float64
 10  CMA            358914 non-null  float64
 11  momentum_2     358914 non-null  float64
 12  momentum_3     358914 non-null  float64
 13  momentum_6     358914 non-null  float64
 14  momentum_9     358914 non-null  float64
 15  momentum_12    358914 non-null  float64
 16  momentum_3_12  358914 non-null  float64
 17  year           358914 non-null  int32  
 18  month          358914 non-null  int32  
 19  return_1m_t-1  357076 non-null  float64
 20  return_1m_t-2  355238 non-null  float64
 21  return_1m_t-3  353400 non-null  float64
 22  return_1m_t-4  351562 non-null  float64
 23  return_1m_t-5  349724 non-null  float64
 24  return_1m_t-6  347886 non-null  float64
 25  age            358914 non-null  int32  
 26  msize          358914 non-null  int32  
 27  sector         358914 non-null  int32  
dtypes: float64(23), int32(5)
memory usage: 71.3+ MB


Notebook's Load Data versiond:

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 358914 entries, ('A', Timestamp('2001-01-31 00:00:00')) to ('ZUMZ', Timestamp('2018-02-28 00:00:00'))
Data columns (total 28 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   return_1m      358914 non-null  float64
 1   return_2m      358914 non-null  float64
 2   return_3m      358914 non-null  float64
 3   return_6m      358914 non-null  float64
 4   return_9m      358914 non-null  float64
 5   return_12m     358914 non-null  float64
 6   Mkt-RF         358914 non-null  float64
 7   SMB            358914 non-null  float64
 8   HML            358914 non-null  float64
 9   RMW            358914 non-null  float64
 10  CMA            358914 non-null  float64
 11  momentum_2     358914 non-null  float64
 12  momentum_3     358914 non-null  float64
 13  momentum_6     358914 non-null  float64
 14  momentum_9     358914 non-null  float64
 15  momentum_12    358914 non-null  float64
 16  momentum_3_12  358914 non-null  float64
 17  year           358914 non-null  int64  
 18  month          358914 non-null  int64  
 19  return_1m_t-1  357076 non-null  float64
 20  return_1m_t-2  355238 non-null  float64
 21  return_1m_t-3  353400 non-null  float64
 22  return_1m_t-4  351562 non-null  float64
 23  return_1m_t-5  349724 non-null  float64
 24  return_1m_t-6  347886 non-null  float64
 25  age            358914 non-null  int64  
 26  msize          358914 non-null  int64  
 27  sector         358914 non-null  int64  
dtypes: float64(23), int64(5)
memory usage: 78.1+ MB

virtually same output, only difference is memory usage 78.1mb+ vs 71.3mb+.  Not sure where to go from here to get it to run?

**Comment by stefan-jansen** [comment]
1. Are you using Docker or did you create your own environment?
2. Do you tet the first error at  `XGBoostClassifier` so the prior models work?
3. The backtrace says the error occurs in  line 3 of`run_cv`. So you should check the inputs to that function, namely the data and the classifier, to check they are what you think they should be.

**Comment by dev-rrusso** [comment]
1. Using conda environments. No docker.
2. First error starts at Baseline Classifier, so Random Forest, XGBoostClassifier, AdaBoost, none of them work, same error about list index..
3. Line 3 is the ‘scores’ variable declaration using ‘cross_validate()’.  I think it’s maybe not creating the scoring list parameter correctly but not sure how to correct it.  It should mirror the notebook as I didn’t make any changes..

line 3:
scores = cross_validate(estimator=clf,
X=X,
y=y,
scoring=list(metrics.keys()),
cv=cv,
return_train_scores=True,
n_jobs=n_jobs,
verbose=1,
fit_params=fit_params)

**Comment by stefan-jansen** [comment]
Please see my response to your other post https://github.com/stefan-jansen/machine-learning-for-trading/issues/147. Both Docker and the environment I shared do not produce the errors you are experiencing, thus the same recommendations apply.

Also closing this issue for now, please also feel free to reopen if my recommendations do not resolve this.
