### ISSUE TITLE
Cannot repeat with 01_parse_itch_order_flow_messages.ipynb

### ISSUE THREAD

**Issue by Alibek80** [stefan-jansen/machine-learning-for-trading#15]
Cannot repeat 01_parse_itch_order_flow_messages.ipynb. Numerous errors, some could resolve by changing names of variables, but cannot in 
The following code processes the binary file and produces the parsed orders stored by message type:

I receive the error:
error                                     Traceback (most recent call last)
<ipython-input-46-5ebcf6c33385> in <module>
     17         # read & store message
     18         record = data.read(message_size - 1)
---> 19         message = message_fields[message_type]._make(unpack(fstring[message_type], record))
     20         messages[message_type].append(message)
     21 

error: bad char in struct format

**Comment by stefan-jansen** [comment]
Thanks, @Alibek80. The error was caused by my renaming of `message_types` to `specs` after reloading the `.csv` but forgetting to also rename the subsequent uses of `message_types`. I've pushed a fix and tested successfully on Mac OS. Please let me know if you run into any other issues.
