### ISSUE TITLE
Ch 20_04_build_us_stock_dataset

### ISSUE THREAD

**Issue by twangecon** [stefan-jansen/machine-learning-for-trading#158]
**Describe the bug**
Ch 20_04_build_us_stock_dataset under the NASDAQ symbols. 
Error shown as ValueError: No objects to concatenate

**To Reproduce**
1. Go to 'Jupyter notebook'
2. Click on '04_build_us_stock_dataset',run
3. Scroll down to 'NASDAQ symbols'

**Screenshots**

![bug](https://user-images.githubusercontent.com/83743179/117238739-723e1580-adfb-11eb-99a1-bf0ab5542e6b.PNG)

**Environment**
Windows 10

**Additional context**

**Comment by stefan-jansen** [comment]
I"ve updated the notebook to fix some changes in the yfinance API. Unfortunately, Yahoo appears to have started rate limiting and downloads are currently only at 25 tickers/min. This may change again but the recent sale of Yahoo to Apollo suggest this data source may dry up in time.
