### ISSUE TITLE
Python Release

### ISSUE THREAD

**Issue by Eeonum** [stefan-jansen/machine-learning-for-trading#159]
Is it possible for you to have a release tested python project as well? It makes the job easier to run multithreading tasks instead of focusing on jupyter notebooks. Thank you!

**Comment by stefan-jansen** [comment]
I've included guidance in the [installation instructions](https://github.com/stefan-jansen/machine-learning-for-trading/tree/master/installation#converting-jupyter-notebooks-to-python-scripts) on how to convert notebooks to scripts. You can also take this a step further by [excluding markdown](https://stackoverflow.com/questions/37423380/ignore-markdown-cells-in-jupyter-nbconvert-with-to-script) - also see [nbconvert docs](https://nbconvert.readthedocs.io/en/latest/config_options.html#exporter-options).

Hope this helps.
