### ISSUE TITLE
Zipline not working 

### ISSUE THREAD

**Issue by Alibek80** [stefan-jansen/machine-learning-for-trading#16]
zipline_example.ipynb not working as zipline throws error:
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I tried Stackoverflow solution, but did not help;
https://stackoverflow.com/questions/56957791/getting-jsondecodeerror-expecting-value-line-1-column-1-char-0-with-python/58661288#58661288

**Comment by stefan-jansen** [comment]
For Zipline installation, please take a look at https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/05_strategy_evaluation/01_trade_simulation_pf_management_zipline/zipline_installation.ipynb

I'm sorry, I still need to clean up the installation instructions; this should be in the installations directory. Zipline is a bit tricky, please get in touch if you can't get it to work.

**Comment by Alibek80** [comment]
Thank you for answer! Tried to build from sources, but failed due to numerous errors. 
Can you please provide which exact files should I change in the zipline?
