### ISSUE TITLE
Ch11_00_data_prep.ipynb

### ISSUE THREAD

**Issue by cheenweekiang** [stefan-jansen/machine-learning-for-trading#164]
![image](https://user-images.githubusercontent.com/33094161/118483670-dd1b1500-b748-11eb-985f-335957e12e5b.png)

Does anyone encounter this error? I have added additional 16gb of ram to 32gb of ram. the kernel still dies. i am running in the window dockers version.

**Comment by stefan-jansen** [comment]
It shouldn't take that much memory. Have you seen the [new installation instructions](https://github.com/stefan-jansen/machine-learning-for-trading/tree/master/installation) that provide a single conda environment and avoid the use of Docker? This should make things easier and more performant.

**Comment by cheenweekiang** [comment]
Thank you very much Stefan. It works now with the new installation.
