### ISSUE TITLE
url = 'https://old.nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange={}&render=download' makes the process be hung

### ISSUE THREAD

**Issue by stevenmailca** [stefan-jansen/machine-learning-for-trading#165]
It seems that below code inside data/create_datasets.ipynb makes the process be hung:
url = 'https://old.nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange={}&render=download'
exchanges = ['NASDAQ', 'AMEX', 'NYSE']
df = pd.concat([pd.read_csv(url.format(ex)) for ex in exchanges]).dropna(how='all', axis=1)

I also try below codes which also make the process be hung:

import pandas as pd
url="https://old.nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange=NASDAQ&render=download"
c=pd.read_csv(url)

import pandas as pd
url="https://old.nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange=AMEX&render=download"
c=pd.read_csv(url)

import pandas as pd
url="https://old.nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange=NYSE&render=download"
c=pd.read_csv(url)

**Comment by stevenmailca** [comment]
I saw the update inside create_datasets.ipynb:
Update: unfortunately, NASDAQ has disabled automatic downloads.

**Comment by zxweed** [comment]
Hello, manual downloads was disabled also.
