### ISSUE TITLE
Supervised Loss in the TimeGAN implementation

### ISSUE THREAD

**Issue by Salbinus** [stefan-jansen/machine-learning-for-trading#166]
Hi,

first, thanks a lot for the work you put in this clean implementation.

I've just found a discrepancy according how the supervised loss is implemented:
g_loss_s = mse(h[:, 1:, :], h_hat_supervised[:, 1:, :])

compared to the original where:
g_loss_s = mse(h[:,1:,:], h_hat_supervise[:,:-1,:])

I guess g_loss_s should force the supervisor to generate next sequence (h[:,1:,:]) using previous sequence (h[:,:-1,:]), right? (Just reffering to [This thread](https://github.com/jsyoon0823/TimeGAN/issues/4#issuecomment-650642528 ))

Thanks and best

**Comment by stefan-jansen** [comment]
Thank you, I had the feeling that something wasn't quite right around capturing the temporal dynamics but never had the time to go back and investigate in-depth. I'll update and check how the results change, esp. at scale.
