### ISSUE TITLE
Issues with datetime in 02_rebuild_nasdaq_order_book.ipynb

### ISSUE THREAD

**Issue by Alibek80** [stefan-jansen/machine-learning-for-trading#17]
I've got an issue when converting timestamp to integer so changed:
buy_per_min.timestamp = buy_per_min.timestamp.add(utc_offset).**_values_**.astype(int)
Same for sell_per_min and trades_per_min
But now I receive error 
**OSError: [Errno 22] Invalid argument**
in the last plot in the line
xticks = [datetime.fromtimestamp(ts / 1e9).strftime('%H:%M') for ts in ax.get_xticks()]
as all timestamps are negative.

**Comment by stefan-jansen** [comment]
I've rerun this recently while testing and wasn't able to replicate this; meanwhile the notebooks have been updated, please let me know if you continue to run into any issues.
