### ISSUE TITLE
Chapter 5: Optimized portfolio performs worse than equal-weight portfolio

### ISSUE THREAD

**Issue by alviswn7** [stefan-jansen/machine-learning-for-trading#174]
**Describe the bug**
In the script 05_strategy_evaluation/02_backtest_with_pf_optimization.ipynb, the optimized portfolio performed significantly worse than the equal-weight portfolio. The results were not consistent with those shown in Figure 5.3 of the book.

**To Reproduce**
See the bottom image of [this page](https://github.com/PacktPublishing/Machine-Learning-for-Algorithmic-Trading-Second-Edition/blob/master/05_strategy_evaluation/02_backtest_with_pf_optimization.ipynb)

**Expected behavior**
The optimized portfolio should perform better than the equal-weight portfolio.

**Screenshots**
taken directly from the page above:
![image](https://user-images.githubusercontent.com/7348790/124350950-302e2600-dc2a-11eb-9dd2-1e2fc44be5e8.png)

**Environment**
N/A

**Additional context**
N/A

**Comment by stefan-jansen** [comment]
This is mostly due to updating the PyPortfolioOpt version; there were some changes as to how errors in the optimization process were handled and the code now works differently and also produces different results than originally published.
