### ISSUE TITLE
Problem importing custom stooq bundle with custom ZIPLINE_ROOT location

### ISSUE THREAD

**Issue by EcoFin** [stefan-jansen/machine-learning-for-trading#179]
Stefan, Following exactly your instructions (Ch 11 ml4at) for importing the stooq_jp_stocks custom bundle fails in my setup with a "cannot load extension..." error on the line "from stooq_jp_stocks import stooq_jp_to_bundle".  It seems that it just can't find the stooq_jp_stocks.py file.

Might this have to do with the fact that my ZIPLINE_ROOT (set as a Win 10 environment variable) is in a non-standard location (E:\Documents\\.zipline)?  Is there a recommended fix?

All the other bundles defined in extension.py based either on Norgate or zipline's csvdir ingest functions work fine.

Not sure whether this question should go here or in zipline reloaded.

regards
ay

**Comment by stefan-jansen** [comment]
There were some reports about issues with multiple custom bundles, requiring ingesting again to remain accessible. Not sure if this is related. I tested custom ZIPLINE_ROOT on Windows after another issue emerge but did not experience any problems. So perhaps it's related to problems with multiple bundles. The issue would be better under zipline-reloaded, though; I hope to get back to this soon.

**Comment by EcoFin** [comment]
Stefan,  Yes, I read the multiple custom bundles note.  I will report this to zipline reloaded.

There is also a couple of other things I have thought of to check on my side.  If I can find anything else, I will let you know.

 

Regards

ay

**Comment by stefan-jansen** [comment]
Closing this here for now, feel free to continue the discussion on the zipline-reloaded repo.
