### ISSUE TITLE
Zipline Reloaded v.2.0.0.post1 requires yfinance with broken dependency #17

### ISSUE THREAD

**Issue by rydeen7** [stefan-jansen/machine-learning-for-trading#183]
**Describe the bug**
Zipline Reloaded v.2.0.0.post1 requires yfinance with broken dependency #17

**To Reproduce**
- In case you are not running the current version of the notebook/script as found on GitHub.
notebook 04_rolling_regression.ipynb does not work on "prices = yf.download('GFI GLD', period='max').dropna().loc[;, 'Close']

- OS: [e.g. MacOSX, Windows, Ubuntu]
 - Version [e.g. Big Sur, 10, 20.04]

**Additional context**
I patched as you mentioned here, but the problem does not solved.
https://githubmemory.com/repo/stefan-jansen/zipline-reloaded/issues/17

**Comment by rydeen7** [comment]
I found that yfinace version should be 0.1.63  due to recent yahoo finance API change . 
But  Zipline Reloaded v.2.0.0.post1 consists of yfinance version 0.1.59 .

**Comment by stefan-jansen** [comment]
Just released [Ziplne version 2.1.1](https://github.com/stefan-jansen/zipline-reloaded) to address this and other issues.
