### ISSUE TITLE
chapter12: 11_intraday_model.ipynb

### ISSUE THREAD

**Issue by Eeonum** [stefan-jansen/machine-learning-for-trading#196]
**Describe the bug**
lightgbm.basic.LightGBMError: GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1

**Environment**
ml4t
 
- OS: [Ubuntu]

**Comment by stefan-jansen** [comment]
I don't think this is a bug; the environment does not assume you have a GPU on purpose, but you're of course free to change this if you do.
