### ISSUE TITLE
Create_datasets - Download and store data - Metadata on US-traded companies

### ISSUE THREAD

**Issue by Longkho** [stefan-jansen/machine-learning-for-trading#197]
In "Download and store data" under heading "Metadata on US-traded companies"
The following downloads several attributes for companies traded on NASDAQ, AMEX and NYSE
Update: unfortunately, NASDAQ has disabled automatic downloads. However, you can still access and manually download the files at the below URL when you fill in the exchange names. So for AMEX, URL becomes https://www.nasdaq.com/market-activity/stocks/screener?exchange=AMEX&letter=0&render=download.

change to following
https://api.nasdaq.com/api/screener/stocks?tableonly=true&limit=3296&exchange={}&OFFSET=0&DOWNLOAD=TRUE

we can modify the links and point to get the download in json

AMEX = "https://api.nasdaq.com/api/screener/stocks?tableonly=true&limit=3296&exchange=AMEX&OFFSET=0&DOWNLOAD=TRUE"
NYSE = "https://api.nasdaq.com/api/screener/stocks?tableonly=true&limit=3296&exchange=NYSE&OFFSET=0&DOWNLOAD=TRUE"
NASDAQ = "https://api.nasdaq.com/api/screener/stocks?tableonly=true&limit=25&exchange=NASDAQ&OFFSET=0&DOWNLOAD=TRUE"

since the download files are in json format instead of csv for the code to work extra steps require to convert the json to csv/dataframe.

**Comment by stefan-jansen** [comment]
Thanks for the hint! I'll update in the coming days.

**Comment by stefan-jansen** [comment]
I'm getting access denied:

```bash
curl -i https://api.nasdaq.com/api/screener/stocks?tableonly=true&limit=3296&exchange=NASDAQ&OFFSET=0&DOWNLOAD=TRUE
[1] 1796931
[2] 1796932
[3] 1796933
[4] 1796934
[2]   Done                    limit=3296
[3]-  Done                    exchange=NASDAQ
[4]+  Done                    OFFSET=0
 HTTP/2 403 
server: AkamaiGHost
mime-version: 1.0
content-type: text/html
content-length: 295
x-reference-error: 18.6533ca17.1631293045.a714eb7
expires: Fri, 10 Sep 2021 16:57:25 GMT
cache-control: max-age=0, no-cache, no-store
pragma: no-cache
date: Fri, 10 Sep 2021 16:57:25 GMT
strict-transport-security: max-age=86400

<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;api&#46;nasdaq&#46;com&#47;api&#47;screener&#47;stocks&#63;" on this server.<P>
Reference&#32;&#35;18&#46;6533ca17&#46;1631293045&#46;a714eb7
</BODY>
</HTML>
```
Manual download works but provides the same info as the csv files except for the added conversion effort. 

Where you able to download programmatically?

**Comment by stefan-jansen** [comment]
Closing for now as it does not appear to be actionable but please feel free to reopen if there is indeed a way to download directly as opposed to manually.
