### ISSUE TITLE
Error running NASDAQ File

### ISSUE THREAD

**Issue by pankajk** [stefan-jansen/machine-learning-for-trading#2]
AttributeError                            Traceback (most recent call last)
<ipython-input-15-963a711b5b53> in <module>
      1 file_name = may_be_download(FTP_URL + SOURCE_FILE)
----> 2 date = file_name.split('.')[0]

AttributeError: 'PosixPath' object has no attribute 'split'

NameError                                 Traceback (most recent call last)
<ipython-input-14-f5e398eed9d6> in <module>
----> 1 message_labels = (df.loc[:, ['message_type', 'notes']]
      2                   .dropna()
      3                   .rename(columns={'notes': 'name'}))
      4 message_labels.name = (message_labels.name
      5                        .str.lower()

NameError: name 'df' is not defined

**Comment by stefan-jansen** [comment]
Thanks for the heads up, should have been ` file_name.name.split('.')[0]`, just pushed the corrected notebook.
