### ISSUE TITLE
storing predictions code

### ISSUE THREAD

**Issue by creatorpark2017** [stefan-jansen/machine-learning-for-trading#20]
The code on analyzing cross-validation section in rf and boosting chapters are very misleading and unclear. Why are there different labels on stored metrics and evaluated metrics on the hdf file? Why are different hdf files used when runningcv/storing and evaluating?

It seems like the author has run the cross-validation code snippet somewhere else and pasted it on the repo, resulting in different file and metric names?

**Comment by stefan-jansen** [comment]
Thank you for letting me know, happy to look into this. I did indeed run the code on AWS and still need to add comments - this is still under review. Could you please point out the code sections you are referring to?

**Comment by stefan-jansen** [comment]
So I've updated some of the `HDFStore` references in notebooks 05/06/07 for ch 11 and nb 05/06 for ch 12 - please let me know if you find that the issue persists.
