### ISSUE TITLE
Following Installation instructions fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by cancandan** [stefan-jansen/machine-learning-for-trading#200]
**Describe the bug**

Error: Command "/home/xxx/miniconda3/envs/ml4t/bin/x86_64-conda-linux-gnu-cc -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/xxx/miniconda3/envs/ml4t/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/xxx/miniconda3/envs/ml4t/include -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DSCIPY_MKL_H -DHAVE_CBLAS -I/usr/local/include -I/usr/include -I/home/xxx/miniconda3/envs/ml4t/include -Ibuild/src.linux-x86_64-3.8/numpy/core/src/umath -Ibuild/src.linux-x86_64-3.8/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.8/numpy/core/src/common -Inumpy/core/include -Ibuild/src.linux-x86_64-3.8/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/xxx/miniconda3/envs/ml4t/include/python3.8 -Ibuild/src.linux-x86_64-3.8/numpy/core/src/common -Ibuild/src.linux-x86_64-3.8/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.8/numpy/core/src/common -Ibuild/src.linux-x86_64-3.8/numpy/core/src/npymath -c numpy/core/src/multiarray/alloc.c -o build/temp.linux-x86_64-3.8/numpy/core/src/multiarray/alloc.o -MMD -MF build/temp.linux-x86_64-3.8/numpy/core/src/multiarray/alloc.o.d" failed with exit status 1

ERROR: Command errored out with exit status 1: /home/xxx/miniconda3/envs/ml4t/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vymyo958/numpy_a16ca206e8bf44c58ba8f7a6db2a9c81/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vymyo958/numpy_a16ca206e8bf44c58ba8f7a6db2a9c81/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2y8inbq0/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-rhpe_1lu/overlay --compile --install-headers /tmp/pip-build-env-rhpe_1lu/overlay/include/python3.8/numpy Check the logs for full command output.

WARNING: Discarding https://files.pythonhosted.org/packages/83/47/fd1e818b8da30ef18695a0fbf9b66611ab18506f0a44fc69480a75f4db1b/cvxpy-1.1.12.tar.gz#sha256=b499ebfae4fc645e9523621573ffcb1c5b6854a1b5c0ce1d66a8a9a458605807 (from https://pypi.org/simple/cvxpy/) (requires-python:>=3.5). Command errored out with exit status 1: /home/xxx/miniconda3/envs/ml4t/bin/python /tmp/pip-standalone-pip-u_385e9o/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-rhpe_1lu/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'numpy==1.15; python_version=='"'"'3.6'"'"'' 'numpy==1.15; python_version=='"'"'3.7'"'"'' 'numpy==1.16; python_version=='"'"'3.8'"'"'' 'numpy==1.19; python_version=='"'"'3.9'"'"'' 'scipy >= 1.1.0' 'setuptools>=40.8.0' wheel Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement cvxpy==1.1.12 (from versions: 0.1, 0.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.9, 0.2.10, 0.2.11, 0.2.12, 0.2.13, 0.2.14, 0.2.15, 0.2.16, 0.2.17, 0.2.18, 0.2.19, 0.2.20, 0.2.21, 0.2.22, 0.2.23, 0.2.24, 0.2.25, 0.2.26, 0.2.27, 0.2.28, 0.3.0, 0.3.1, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.8, 0.4.9, 0.4.10, 0.4.11, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.8, 1.0.9, 1.0.10, 1.0.11, 1.0.12, 1.0.13, 1.0.14, 1.0.15, 1.0.16, 1.0.17, 1.0.18, 1.0.19, 1.0.20, 1.0.21, 1.0.22, 1.0.23, 1.0.24, 1.0.25, 1.0.26, 1.0.27, 1.0.28, 1.0.29, 1.0.31, 1.1.0a0, 1.1.0a1, 1.1.0a2, 1.1.0a3, 1.1.0a4, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.1.10, 1.1.11, 1.1.12, 1.1.13, 1.1.14, 1.1.15)
ERROR: No matching distribution found for cvxpy==1.1.12
\ 
failed

CondaEnvException: Pip failed

**To Reproduce**
mamba env create -f installation/linux/ml4t.yml 

1. Execute the above line.

**Expected behavior**
A working environment is created.

**Environment**

Ubuntu 20.04

**Comment by cancandan** [comment]
FYI, changing cvxpy==1.1.12 to cvxpy==1.1.13 in the file ml4t.yml, mamba completes successfully.

**Comment by stefan-jansen** [comment]
I've updated the base enviroments `installation/ml4t-base.[txt, yml]` as well as the current linux versions.
