### ISSUE TITLE
Part04 - 04_single_factor_zipline FileNotFoundError: ".zipline/data/quandl'

### ISSUE THREAD

**Issue by kmeans27** [stefan-jansen/machine-learning-for-trading#209]
Hello,

I cloned the env via conda & the ml4t.yml file

But when I try to run the zipline code i get a FileNotFoundError
<img width="1676" alt="Screenshot 2021-11-03 at 10 30 30" src="https://user-images.githubusercontent.com/93648278/140038941-6de97fb1-439c-4d14-8a97-d4238d8a067c.png">

What did I miss? Do I need to add the quandl API somewhere? I am currently reading the book but I am stuck on the backtesting part :-(

**Comment by stefan-jansen** [comment]
You need to run `zipline ingest -b quandl` first see [installation instructions](https://github.com/stefan-jansen/machine-learning-for-trading/tree/main/installation#ingesting-zipline-data).
