### ISSUE TITLE
zipline data ingest for backtesting

### ISSUE THREAD

**Issue by creatorpark2017** [stefan-jansen/machine-learning-for-trading#21]
Hi I tried running the zipline backtest in chapter 12, and upon following the notebook code by code, I came across the following error:

"ValueError: Failed to find any assets with country_code 'US' that traded between 2016-01-13 00:00:00+00:00 and 2016-01-21 00:00:00+00:00.
This probably means that your asset db is old or that it has incorrect country/exchange metadata."

This happened to be so for any stard_date I tried, the first week will always raise this ValueError. 

I also followed the book's instruction on ingesting quandl data.
Any suggestions?
Thanks in advance!

Also, for chapter 11, how is the 'stooq' bundle used for backtesting ingested?

**Comment by creatorpark2017** [comment]
https://github.com/quantopian/zipline/issues/2517

solution above

**Comment by SouthernYoda** [comment]
Can you explain how you managed to solve the issue? 

I am encountering the same error in the Chapter 4 notebook "04_single_factor_zipline"

**Comment by antkealy** [comment]
I'd also appreciate some help on this issue. I didn't have any issue running the zipline code in chapter 2 but have encountered the below in Chapter 4 notebook "04_single_factor_zipline":

"ValueError: Failed to find any assets with country_code 'US' that traded between 2016-01-13 00:00:00+00:00 and 2016-01-21 00:00:00+00:00.
This probably means that your asset db is old or that it has incorrect country/exchange metadata."

**Comment by SouthernYoda** [comment]
The way I solved it is by manually inserting the country_code into the created sqlite database.

Steps to solve the issue
1. Make sure you still run the `!zipline ingest` command to import the latest data into your project folder
2.  Open the "assets07.sqlite" file in the directory path using an sqlite client
     `.\data\.zipline\data\quandl\<timestamp>`
    <i>side note: I used https://sqlitebrowser.org/ as a GUI sqlite client it was really easy to use </i>
3. In the table <b>'exchanges'</b>there will be the column named <b>'country_code'</b> with a Null value, change it to <b>'US'</b> (See screenshot below)
4. I don't know if this affected anything but I reloaded zipline with the command `%reload_ext zipline` before rerunning the trading script

![image](https://user-images.githubusercontent.com/15722886/98820618-62b9b300-23fc-11eb-9fdc-080f2823b166.png)

Hope this helps, if I missed a step let me know I'm going off of memory!

**Comment by antkealy** [comment]
Thanks SouthernYoda! Really appreciate the detailed response.

**Comment by stefan-jansen** [comment]
I've added a warning and link to the Quantopian GitHub issue that discusses this problem in the installation instructions; sorry, should have done so earlier.

**Comment by antkealy** [comment]
Thanks Stefan/Southern Yoda. I am trying this again following the above instructions:
1) %load_ext zipline
2) !zipline ingest in the the project
3) amend the country code in exchanges to US once the ingest is complete, save database 
4) %reload_ext zipline (have also tried not re-loading)
5) run the main trading script

When running the trading script, the kernel seems to stall/stay busy - I don't receive any errors etc. Any ideas what could be causing this? 
5) When I try to run the

**Comment by SouthernYoda** [comment]
It takes some time to execute depending on your hardware, give it like 30mins to run.

If it's not throwing errors then it's probably doing something so put some print statements in the code to help you understand what's going on.

I just started going through the book just like yourself so I'd need some more details to be able to help

**Comment by antkealy** [comment]
Thanks SouthernYoda - I haven't had a zipline one take so long before so assumed first that something was up! Some progress statements are the way forward.

**Comment by cheenweekiang** [comment]
A more elegant way to impute country code into the sqlite database utilizing sqlite3

import sqlite3
db_path = r'C:\Users\users\.zipline\data\stooq\2025-05-30T13;57;21.962940\assets-7.sqlite'
conn = sqlite3.connect(db_path)
cursor = conn.cursor()
 
cursor.execute("UPDATE exchanges SET country_code = 'JP';")
conn.commit()
