### ISSUE TITLE
In chapter 22, all of the hyperparameter and even stock symbol are hard coded in the gym environment

### ISSUE THREAD

**Issue by jimmyland22** [stefan-jansen/machine-learning-for-trading#212]
**Describe the bug**
In the trading_env.py gym environment, all of the hyperparameters are hard coded as well as the stock symbol used.

**To Reproduce**
Make any changes in the 04_q_learning_for_trading.ipynb file, it doesn't do anything as it'll still use AAPL and all of the default hyperparameters.

**Comment by stefan-jansen** [comment]
You can set a different ticker using: 
```python
trading_environment = gym.make('trading-v0', ticker='IBM')
```
I'll update the notebook accordingly.
