### ISSUE TITLE
Data Issue in chapter 9

### ISSUE THREAD

**Issue by Matteocos40** [stefan-jansen/machine-learning-for-trading#213]
In the notebook "06_statistical_arbitrage_with_cointegrated_pairs.ipynb," there is a call referring to the object 'data.h5' but I cannot find what this should be. I could not find it in the data folder either, is it defined somewhere else?

**Comment by stefan-jansen** [comment]
Please see the notebook [05_cointegration_tests.ipynb](https://github.com/stefan-jansen/machine-learning-for-trading/blob/main/09_time_series_models/05_cointegration_tests.ipynb), as mentioned in book p285. Adding a hint in the notebook.
