### ISSUE TITLE
DataPrep Chp11  ValueError: unsupported pickle protocol: 5

### ISSUE THREAD

**Issue by jjviton** [stefan-jansen/machine-learning-for-trading#218]
hi all,
I´m facing this error at data preparation stage "ValueError: unsupported pickle protocol: 5" in this code line (with pd.HDFStore(DATA_STORE) as store:). 
I reinstalled all packages includin pickle without sucess.
My enviroment is: conda, python 3.7.11

**Comment by stefan-jansen** [comment]
There are [pickle version issues](https://stackoverflow.com/questions/63329657/python-3-7-error-unsupported-pickle-protocol-5) when moving between Python 3.7 and 3.8; did you perhaps create the data using one version and then reload with 3.7 or vice versa?

**Comment by CDLim0906** [comment]
I created a new environment, using Python 3.8 with zipline reloaded, pyfolio-reloaded etc, from here [https://pypi.org/user/ml4t/](url) works fine now. Thanks Stefan.

**Comment by stefan-jansen** [comment]
Glad to hear.
