### ISSUE TITLE
chapter 13_unsupervised_learning / 03_kmeans_evaluation

### ISSUE THREAD

**Issue by silent0506** [stefan-jansen/machine-learning-for-trading#219]
**Describe the bug**
Hi. stefan. As i running 13_unsupervised_learning / 03)kmenas_evaluation

I got a error this message. how can i update your code? 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/70154806/151273127-330a34f8-cf78-484b-ab46-9ba61bedcaaa.png)
![image](https://user-images.githubusercontent.com/70154806/151273157-c9f77c04-5f4c-43b9-bbb6-eab927106644.png)
![image](https://user-images.githubusercontent.com/70154806/151273183-aa80a8e4-c8f9-4a8c-82e2-48c61e400fad.png)
![image](https://user-images.githubusercontent.com/70154806/151265726-c15d15d4-1e25-495f-8d46-397d04f7b68d.png)

**Environment**
 
- OS: Windows
 - Version 10

**Additional context**

**Comment by stefan-jansen** [comment]
The color information had to be passed as a list (see error message) since Matplotlib changed its API in a later version.
