### ISSUE TITLE
Dataset is unaccessible. 

### ISSUE THREAD

**Issue by sagebei** [stefan-jansen/machine-learning-for-trading#221]
The following instructions to download the data are not valid. Could you provide an update?

Follow the instructions to create a free NASDAQ account
Download the entire WIKI/PRICES data
Extract the .zip file,
Move to this directory and rename to wiki_prices.csv

**Comment by Jeffery0908** [comment]
I have the same questions about how to get the WIKI/PRICES data.

**Comment by sagebei** [comment]
Hi Stefan. Thank you for your reply. I tried again and it worked.

**Comment by ZhaiCong** [comment]
I had same problem, I use Clash as my IP proxies tools, should change the proxies site, Only American site worked
