### ISSUE TITLE
In create_datasets.ipynb Bond Price Indexes DataSource[GOLDAMGBD228NLBM] is Not ready

### ISSUE THREAD

**Issue by starfire-lzd** [stefan-jansen/machine-learning-for-trading#225]
**Describe the bug**
when I use create_datasets.ipynb to download data, the GOLDAMGBD228NLBM in Bond Price Indexes is count fetch

**To Reproduce**
master

**Expected behavior**
RemoteDataError: Unable to read URL: https://fred.stlouisfed.org/graph/fredgraph.csv?id=GOLDAMGBD228NLBM

**Environment**
If you are not using the latest version of the Docker imag:
 
- OS: [e.g. MacOSX, Windows, Ubuntu]
 - WSL2 
 - python3.8

**Comment by stefan-jansen** [comment]
Unfortunately, this data has been [recently removed](https://news.research.stlouisfed.org/2022/01/ice-benchmark-administration-ltd-iba-data-to-be-removed-from-fred/ from the FRED service. I'll use a different dataset when I update to the next edition and will add a warning in the notebook. Sorry about this, but not much I can do.

**Comment by CDLim0906** [comment]
Hi, I am having the same issue. Are these data ('GOLDAMGBD228NLBM': 'Gold (London, USD)') important later in the chapter? 
Regards

**Comment by stefan-jansen** [comment]
Nope, they are not important.

**Comment by CDLim0906** [comment]
Oh, thanks for the reply, and also, thanks for putting up such a great book.
