### ISSUE TITLE
Machine Learning for Algorithmic Trading, 2nd Edition

### ISSUE THREAD

**Issue by chansingcho** [stefan-jansen/machine-learning-for-trading#226]
Dear Stefan,
Chapter 16 on Word Embeddings (e.g., 01_using_pretrained_vectors.ipynb) requires the file "analogies-en.txt". I could not find the file and do not know how it is created. Please help. Thank you very much.
Sing Cho

**Comment by stefan-jansen** [comment]
You can find the original file here: https://github.com/nicholas-leonard/word2vec/blob/master/questions-words.txt
I'm not sure if I changed the format before using it, will check. Sorry, should have been in the data folder.

**Comment by chansingcho** [comment]
Thanks Stefan. I will try it out.
________________________________

**Comment by stefan-jansen** [comment]
I've found the file but can't access it because I'm traveling. I'll add it early next month.

**Comment by chansingcho** [comment]
Good. Thanks again, Stefan.
________________________________

**Comment by chansingcho** [comment]
Thanks Stefan.
I got the file following your previous email and it worked.

Regards,
SC
________________________________
