### ISSUE TITLE
info.to_hdf(results_path / 'data.h5', 'stocks/info')

### ISSUE THREAD

**Issue by dhsusf** [stefan-jansen/machine-learning-for-trading#227]
**Describe the bug**
04_build_us_stock_dataset.ipynb

info.to_hdf(results_path / 'data.h5', 'stocks/info')

info is not defined.  I believe it should be 

df.to_hdf(results_path / 'data.h5', 'stocks/info')

**Comment by stefan-jansen** [comment]
Correct, fixed.
