### ISSUE TITLE
.numpy() in RL

### ISSUE THREAD

**Issue by creatorpark2017** [stefan-jansen/machine-learning-for-trading#23]
Are there source codes for this particular function?
Just giving us an environment.yml and not explaining how the code works don't seem like a good way to learn and generalize...

**Comment by stefan-jansen** [comment]
I'm happy to help but please provide more specific information about any bug or other issue you are experiencing. 

There is a `.numpy()` method in TensorFlow to convert a tensor to a NumPy array, perhaps this is what you are referring to. For the source code, you would have to look into the TensorFlow GitHub repo.

**Comment by creatorpark2017** [comment]
Thank you!

Sorry for the trouble, I tried replicating the code without installing the ml4t_rl environment, and I thought the method was from NumPy and didn't realize it was from TensorFlow. Turns out it required TensorFlow 2.x and I had 1.x installed. 

Lots of time and energy wasted due to not checking the .yml file...

**Comment by stefan-jansen** [comment]
That's right, I need to update the installation instructions and refresh the environments. There will also be a Docker image to install all environments in one go and then be able to switch them in Jupyter (Lab).
