### ISSUE TITLE
create_datasets.ipynb  Bond Price Indexes  no search results for securities 'GOLDAMGBD228NLBM' 

### ISSUE THREAD

**Issue by ZhaiCong** [stefan-jansen/machine-learning-for-trading#231]
There are no search results for securities 'GOLDAMGBD228NLBM'  .
see link below
https://fred.stlouisfed.org/searchresults?st=GOLDAMGBD228NLBM&404-search-button=Search

Please add a comment before  'GOLDAMGBD228NLBM'  : 'Gold (London, USD)'

**Comment by stefan-jansen** [comment]
This also applies to some of the other datasets. Added comment.
