### ISSUE TITLE
The ftp://emi.nasdaq.com/ITCH can not connect anymore

### ISSUE THREAD

**Issue by YukoOshima** [stefan-jansen/machine-learning-for-trading#234]
The ftp://emi.nasdaq.com/ITCH can not connect anymore.
Where can I find the data to download?

**Comment by stefan-jansen** [comment]
I haven't been able to access the site either, nor to they provide a new link. Looks like the free samples are no longer available. Unfortunately, these things happen. Here's a link to their [paid offerings](http://www.nasdaqtrader.com/Trader.aspx?id=DPUSdata#hti).

Please let me know if you find an alternative source for this.
