### ISSUE TITLE
extract_interesting_date_ranges  from 03_pyfolio_demo Modeling Event Risk

### ISSUE THREAD

**Issue by CDLim0906** [stefan-jansen/machine-learning-for-trading#235]
**Describe the bug**
From 03_pyfolio_demo, Modelling Event Risk. 
Can't find any other events other than from the screenshots. I trace the file back to `interesting_periods.py`  it shows a list of periods. 
 
 
**Screenshots**
![image](https://user-images.githubusercontent.com/16059227/159111800-40cdab31-6beb-4ea4-b1ab-184b2d775324.png)

**Expected behavior**
There should be more than 4 keys, and Period['Flash Crash'] or ['Fukushima] should be included. 

Perhaps, am I doing something wrong?

**Comment by stefan-jansen** [comment]
I'll try to take a look at pyfolio for a new edition to update accordingly, thanks.
