### ISSUE TITLE
Chapter 4 - 01_feature_engineering

### ISSUE THREAD

**Issue by 1JarekNowak** [stefan-jansen/machine-learning-for-trading#239]
Hello, I have a problem downloading data as described in the file 'create_datasets.ipynb', in the 'Wiki prices metadata' section. I can only download single records and when trying to download the entire database, I receive permission error.
As Quandl is no longer available I'm trying to download from links: "https://data.nasdaq.com/api/v3/databases/SCF/data?download_type=full&api_key=YOURAPIKEY"
or
"https://data.nasdaq.com/api/v3/databases/SCF/data?download_type=partial&api_key=YOURAPIKEY"

Is there any other source with a .csv file that I could import for further analysis?

**Comment by stefan-jansen** [comment]
The instructions in the file 'create_datasets.ipynb', in the 'Wiki prices metadata' section read:

> Instead of using the QUANDL API, load the file `wiki_stocks.csv` as described and store in HDF5 format.

The file and sample code are included in the repo. Does this not work for you?

**Comment by 1JarekNowak** [comment]
Thank you. It worked.
