### ISSUE TITLE
2nd edition publishing date

### ISSUE THREAD

**Issue by sabirjana** [stefan-jansen/machine-learning-for-trading#24]
Hi Stefan,
What are the 2nd edition publishing and availability date? Is it the end of this month? Eagerly waiting for it.
Thanks

**Comment by stefan-jansen** [comment]
Hi, thank you for your interest. The current coronavirus crisis has unfortunately caused a little delay so that we are likely only able to publish in June. Thank you for your understanding, we're doing our best!
