### ISSUE TITLE
Kalman Filter and denoising 

### ISSUE THREAD

**Issue by msh855** [stefan-jansen/machine-learning-for-trading#244]
The example in denoising data with Kalman Filter seems that is not applied properly. The initial value is odd (relates to the guess? )  

https://github.com/stefan-jansen/machine-learning-for-trading/blob/main/04_alpha_factor_research/03_kalman_filter_and_wavelets.ipynb 

Here is the pic from the book (second version, Kindle edition) 

![image](https://user-images.githubusercontent.com/26636184/168662081-a0157af0-44dd-45f1-b01e-5ff68eeb9fe0.png)

**Comment by deven13j** [comment]
It was proper as initial_state_mean taken as 0, if you want to start your Kalman Filter guess with your initial measurement then your can change initial_state_mean (in this example approximately 1410)

**Comment by stefan-jansen** [comment]
Thanks, closing for now, please feel free to reopen if you have further questions.
