### ISSUE TITLE
Chapter 12, Section 4, Dollar Volume Rank is Never Used

### ISSUE THREAD

**Issue by majidhosseini1** [stefan-jansen/machine-learning-for-trading#246]
Hello, 
Going through this section, I noticed that the Dollar Volume Rank, meant to restrict the trading universe, seems to never be used in the rest of the this chapter.  
Thanks!

**Comment by stefan-jansen** [comment]
That's right, the model runs with the full dataset. The ranking was just meant to illustrate how you could restrict the universe.
