### ISSUE TITLE
create_datasets.ipynb - Metadata on US-traded companies - file format change

### ISSUE THREAD

**Issue by barashe** [stefan-jansen/machine-learning-for-trading#247]
The NASDAQ, AMEX and NYSE file format changed:

1. The `marketcap` field is now `market cap`.
2. The values in `market cap` are no longer strings with suffixes but rather numerics and no longer require conversion.

**Comment by stefan-jansen** [comment]
I believe I have included the file [here](https://github.com/stefan-jansen/machine-learning-for-trading/blob/main/data/us_equities_meta_data.csv).
