### ISSUE TITLE
RuntimeError: Cannot set name on a level of a MultiIndex. . Use 'MultiIndex.set_names' instead.

### ISSUE THREAD

**Issue by lumiereUmbra** [stefan-jansen/machine-learning-for-trading#248]
**Describe the bug**
I am getting the above runtime error while executing alphalens_signals_quality.ipynb in line from Alphalens library function 
factor_data = get_clean_factor_and_forward_returns(factor=factor, prices=trade_prices,quantiles=5, periods=(1, 5, 10, 21)) . Appears to be a compatibility issue with pandas library . 

**To Reproduce**
- In case you are not running the current version of the notebook/script as found on GitHub.

1. Go to ' https://github.com/PacktPublishing/Machine-Learning-for-Algorithmic-Trading-Second-Edition/blob/master/11_decision_trees_random_forests/06_alphalens_signals_quality.ipynb'
2. Execute the above file 
3. Scroll down to statement -  
factor_data = get_clean_factor_and_forward_returns(factor=factor, prices=trade_prices,quantiles=5, periods=(1, 5, 10, 21)) . 
4. See error  [ attached screenshot ] 

**Expected behavior**

**Screenshots**

**Environment**

I am using  - 
OS:  Windows 10 
alphalens-0.3.6 
pandas 1.3.5 
python 3.7 

![error_alphalens_utils_get_clean_factor_and_forward_returns](https://user-images.githubusercontent.com/36529883/177082686-647a3b37-3880-4058-bd9c-35febe348d29.jpg)

**Additional context**

**Comment by stefan-jansen** [comment]
Due to incompatiblitly with more recent pandas version; either downgrade or modify the library accordingly.
