### ISSUE TITLE
#Chapter 11 - 00_data_prep.ipynb Broken links

### ISSUE THREAD

**Issue by saad-ibrahim** [stefan-jansen/machine-learning-for-trading#249]
Hi, 

In Chapter 11 and the first notebook 00_data_prep.ipynb the links send me to a 404 error. There are three links that do not work and are found in the following sentences:

_"We create the dataset here and store it in our [data] folder to facilitate reuse in later chapters."

"The assets.h5 store can be generated using the the notebook [create_datasets] in the [data] directory in the root directory of this repo for instruction to download the following dataset."_

Naturally I would need access to these to follow along with the example so I would appreciate it if you can take a look into this as soon as possible.

Thanks!

**Comment by stefan-jansen** [comment]
First link refers to [data](https://github.com/stefan-jansen/machine-learning-for-trading/tree/main/data)  in repo root . [create_datasets](https://github.com/stefan-jansen/machine-learning-for-trading/blob/main/data/create_datasets.ipynb) can be found in this directory. Hope this helps.
