### ISSUE TITLE
05_strategy_evaluation - Mean Revision Startegy

### ISSUE THREAD

**Issue by sabirjana** [stefan-jansen/machine-learning-for-trading#25]
Hi Stefan, I am trying to test the mean revision strategy provided by you in chapter 05_strategy_evaluation,  01_backtest_with_trades.ipynb with my own custom bundle of Indian equity. It doesn't create any output for
`returns, positions, transactions = extract_rets_pos_txn_from_zipline(backtest)`

Any help is appreciated. The code looks as below

```
class MeanReversion(CustomFactor):
    """Compute ratio of latest monthly return to 12m average,
       normalized by std dev of monthly returns"""
    inputs = [Returns(window_length=MONTH)]
    window_length = YEAR

    def compute(self, today, assets, out, monthly_returns):
        df = pd.DataFrame(monthly_returns)
        out[:] = df.iloc[-1].sub(df.mean()).div(df.std())

def compute_factors():
    """Create factor pipeline incl. mean reversion,
        filtered by 30d Dollar Volume; capture factor ranks"""
    mean_reversion = MeanReversion()
    dollar_volume = AverageDollarVolume(window_length=30)
    return Pipeline(columns={'longs'  : mean_reversion.bottom(N_LONGS),
                             'shorts' : mean_reversion.top(N_SHORTS),
                             'ranking': mean_reversion.rank(ascending=False)},
                    screen=dollar_volume.top(VOL_SCREEN))

def rebalance(context, data):
    """Compute long, short and obsolete holdings; place trade orders"""
    factor_data = context.factor_data
    assets = factor_data.index

    longs = assets[factor_data.longs]
    shorts = assets[factor_data.shorts]
    divest = context.portfolio.positions.keys() - longs.union(shorts)

    exec_trades(data, assets=divest, target_percent=0)
    exec_trades(data, assets=longs, target_percent=1 / N_LONGS if N_LONGS else 0)
    exec_trades(data, assets=shorts, target_percent=-1 / N_SHORTS if N_SHORTS else 0)

def exec_trades(data, assets, target_percent):
    """Place orders for assets using target portfolio percentage"""
    for asset in assets:
        if data.can_trade(asset) and not get_open_orders(asset):
            order_target_percent(asset, target_percent)

def before_trading_start(context, data):
    """Run factor pipeline"""
    context.factor_data = pipeline_output('factor_pipeline')
    record(factor_data=context.factor_data.ranking)
    assets = context.factor_data.index
    record(prices=data.current(assets, 'price'))

def initialize(context):
    """Setup: register pipeline, schedule rebalancing,
        and set trading params"""
    set_benchmark(symbol('INFY'))
    attach_pipeline(compute_factors(), 'factor_pipeline')
    schedule_function(rebalance,
                      date_rules.week_start(),
                      time_rules.market_open(),)

    set_commission(us_equities=commission.PerShare(cost=0.00075, min_trade_cost=.01))
    set_slippage(us_equities=slippage.VolumeShareSlippage(volume_limit=0.0025, price_impact=0.01))

backtest = run_algorithm(start=start,
                         end=end,
                         initialize=initialize,
                         before_trading_start=before_trading_start,
                         capital_base=capital_base,
                         data_frequency = 'daily', 
                         bundle= 'nse_data')
```

**Comment by sabirjana** [comment]
hi Stefan,
Did you get a chance to look at it? I am trying to use pipeline with my own custom data bundle however not sure where should I define my asset universe and hence it is not working out. I appreciate any help. thanks

**Comment by stefan-jansen** [comment]
Hi @sabirjana, I'm just finalizing the review of all chapters; there will be an update in the next few days that includes details on custom bundle creation.

**Comment by sabirjana** [comment]
Hi Stefan, 
Thanks!! Eagerly waiting for the 2nd edition.
Details on custom bundle will be really good. For now I could able to create my own custom bundle however while using with the pipeline not sure where should I define asset universe.
SJ

**Comment by alphaville76** [comment]
FYI: I've create a database based custom zipline-bundle for the Sharadar
dataset: https://github.com/alphaville76/sharadar_db_bundle
The most obvious advantage is the incrementally ingestion.

Il giorno lun 22 giu 2020 alle ore 04:44 sabirjana <notifications@github.com>
ha scritto:

**Comment by sabirjana** [comment]
@alphaville76, I think this will help, I will go thru it. Thank you very much or sharing.
Thanks

**Comment by stefan-jansen** [comment]
I've finally updated the zipline custom bundle information here: https://github.com/stefan-jansen/machine-learning-for-trading/tree/master/08_ml4t_workflow/04_ml4t_workflow_with_zipline and https://github.com/stefan-jansen/machine-learning-for-trading/tree/master/11_decision_trees_random_forests/00_custom_bundle; this covers daily and minute data. Please let me know if you have any questions in regard.
