### ISSUE TITLE
cp2. edgar_xbrl

### ISSUE THREAD

**Issue by tonygjwns** [stefan-jansen/machine-learning-for-trading#250]
**Describe the bug**
A brief description of the bug and in which notebook/script it lives.

Bad zip file for 2021 Q1~2022Q2

**To Reproduce**
- In case you are not running the current version of the notebook/script as found on GitHub.

**Expected behavior**

**Screenshots**
![제목 없음](https://user-images.githubusercontent.com/41133124/178496877-db6f687d-7b3e-4bee-abd7-aeb51e4662bf.png)

**Environment**
If you are not using the latest version of the Docker imag:
 
- OS: windows 11

**Additional context**

**Comment by stefan-jansen** [comment]
Please check if the [download urls](https://www.sec.gov/dera/data/financial-statement-and-notes-data-set.html) have changed. If so, I'll update the example for the next edition.

**Comment by tonygjwns** [comment]
> Please check if the [download urls](https://www.sec.gov/dera/data/financial-statement-and-notes-data-set.html) have changed. If so, I'll update the example for the next edition.

The download files had changed from Quarter data to monthly data. I think that made the errors
