### ISSUE TITLE
shape mismatch: value array of shape (4096,) could not be broadcast to indexing result of shape (2,4096,3)

### ISSUE THREAD

**Issue by defc0n1** [stefan-jansen/machine-learning-for-trading#251]
Trying to run 04_q_learning_for_trading results in the following error:

    118 print(targets.shape)
    119 print(targets)
--> 120 q_values[[self.idx, actions]] = targets
    122 loss = self.online_network.train_on_batch(x=states, y=q_values)
    123 self.losses.append(loss)

ValueError: shape mismatch: value array of shape (4096,) could not be broadcast to indexing result of shape (2,4096,3)

Running tensorflow 2.9.2 (GPU)

**Comment by dannyleall** [comment]
Same here... have you found a solution?

**Comment by dereklegenzoff** [comment]
I changed the line in the error message to this:`q_values[self.idx, actions] = targets`

So far it seems to be working for me.

**Comment by stefan-jansen** [comment]
There have been several updates to the open AI gym since publication. Please either use the version that was current at publication (around 2020/06) or update the code accordingly.

**Comment by ghostMike666** [comment]
https://www.facebook.com/mxalgrito?mibextid=ZbWKwL
IP??
