### ISSUE TITLE
Working with Order Book Data: NASDAQ ITCH, Invalid URL and variable

### ISSUE THREAD

**Issue by marctheshark3** [stefan-jansen/machine-learning-for-trading#253]
**Describe the bug**
When running 
```file_name = may_be_download(urljoin(FTP_URL, SOURCE_FILE))```

First, there isnt a variable called FTP_URL, and when changed to HTTPS_URL, you get an invalid URL error. 

This doesnt work:
```HTTPS_URL = 'https://emi.nasdaq.com/ITCH/Nasdaq ITCH/'```

This DOES work:
```HTTPS_URL = 'https://emi.nasdaq.com/ITCH/Nasdaq%20ITCH/'```
**To Reproduce**
- Go to: run 01_parse_itch_order_flow_messages.ipynb from the main branch
- Run the first 8 cells

**Comment by tomas-rampas** [comment]
I created PR for the same
https://github.com/stefan-jansen/machine-learning-for-trading/pull/254

**Comment by The1iAmNeo** [comment]
@marctheshark3 thank you for putting this here ... it is working for me now ... seems like this issue should be fixed as it is literally the first thing they ask you to do lol :) ... hopefully he gets around to this fix because there is no ftp and the url is wrong @stefan-jansen

**Comment by stefan-jansen** [comment]
Fixed by #254, thanks.
