### ISSUE TITLE
Chapter 20. build_us_stock_dataset variable AttributeError

### ISSUE THREAD

**Issue by Jano32** [stefan-jansen/machine-learning-for-trading#256]
Does anyone has an issue on chapter 20 "20_autoencoders_for_conditional_risk_factors/04_build_us_stock_dataset.ipynb" with the variable "yf-symbols = yf.Tickers(all_symbols) ?

I have got this error : AttributeError: 'float' object has no attribute 'upper'

![image](https://user-images.githubusercontent.com/99275634/187408589-3a6bbcf1-a733-4702-a351-144288512588.png)

**Comment by stefan-jansen** [comment]
The error suggests there was no value returned (float = np.nan), which can happen if the API doesn't deliver for a specific call. You may want to either handle the error using `try..except` or just retry later.
