### ISSUE TITLE
create dateset

### ISSUE THREAD

**Issue by xtwxfxk** [stefan-jansen/machine-learning-for-trading#261]
https://old.nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange={}&render=download
exchanges = ['NASDAQ', 'AMEX', 'NYSE']

the data been deleted？

**Comment by stefan-jansen** [comment]
You may want to refer to this url ttps://www.nasdaq.com/market-activity/stocks/screener?exchange=AMEX&letter=0&render=download listed in the [current version](https://github.com/stefan-jansen/machine-learning-for-trading/blob/main/data/create_datasets.ipynb) of `create_datasets.ipynb)`.
