### ISSUE TITLE
Code issue: Chapter 22_deep_reinforcement_learning  04_q_learning_for_trading

### ISSUE THREAD

**Issue by KoalaChelsea** [stefan-jansen/machine-learning-for-trading#263]
I tried to reproduce the Q-Learning for trading, but there is an error when I run this notebook. I prepared data as instructed in data/create_datasets.ipynb. However, I still got the following error when creating the environment from trading_env.py

![image](https://user-images.githubusercontent.com/28869032/198383080-07cefe21-658f-4202-802a-b261560488b0.png)

**Comment by DavidHJong** [comment]
Did you modify the trading_env.py? It seems that the `DataSource.min_values` and `DataSource.max_values` are not configured correctly.

**Comment by Maathouse** [comment]
It helped my to convert the min_values df to the following: self.min_values = self.data.min().to_numpy()

**Comment by stefan-jansen** [comment]
Please note that there have been [several releases](https://github.com/openai/gym/releases) for the OpenAI gym. It's a good idea to run the latest software, but you'll need to adapt the examples to work with more recent versions accordingly.
