### ISSUE TITLE
QUANDL site is permanently down

### ISSUE THREAD

**Issue by shaktisd** [stefan-jansen/machine-learning-for-trading#265]
**Describe the bug**
A brief description of the bug and in which notebook/script it lives.

**zipline ingest -b quandl**

Error 
ValueError: Please set your QUANDL_API_KEY environment variable and retry.
After giving a dummy - set QUANDL_API_KEY=X
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

Is there a way to digest the zipline bundle offline from local computer ?

**Comment by stefan-jansen** [comment]
You can ingest zipline locally following the examples provided in [Chapter 08](https://github.com/stefan-jansen/machine-learning-for-trading/tree/main/08_ml4t_workflow/04_ml4t_workflow_with_zipline/01_custom_bundles). 

NASDAQ continues to make the data [available for free](https://data.nasdaq.com/tables/WIKIP/WIKI-PRICES/export).
