### ISSUE TITLE
MESSAGE_TYPES ON nyse order book construction

### ISSUE THREAD

**Issue by Bandita88** [stefan-jansen/machine-learning-for-trading#266]
Hi everyone, i am tring to construct the nyse order book using the https://www.nasdaqtrader.com/content/technicalsupport/specifications/dataproducts/NQTVITCHSpecification.pdf
But i don't understad something... 
i have to copy and past ALL the data in this link in a file and so on import on jupyter? 
Because in the write code i see one first table example like this format belove:
NAME   OFFSET   LENGHT  VALUE   NOTES
XXXX     XXXX      XXXXX     XXXXX  XXXXX

and after i find also an other one table with the single tipe message specify. 
MESSAGE_TYPE    VALUE/DESCRIPTION
XXXXX                    XXXXXX

Could you give me an help and explanantion? and maybe link for the message_types file? 

Really thanks 

Also, i am using the directly connection with the itch link withouth downloading the file. 
Is it correct? or i must download the file and then do i accede with the http url?

**Comment by Bandita88** [comment]
I have resolve the problem just finding the message_type file from the repositery. i was searching to construct the file on my hands.

**Comment by ishikabansal77** [comment]
Hey, could you please help me where did you find message_types.xls file?

**Comment by stefan-jansen** [comment]
The file is here: it's right here: 02_market_and_fundamental_data/01_NASDAQ_TotalView-ITCH_Order_Book. Hope this helps.

**Comment by ghostMike666** [comment]
No please no More
