### ISSUE TITLE
about the order book itch nasdaq total view

### ISSUE THREAD

**Issue by Bandita88** [stefan-jansen/machine-learning-for-trading#267]
Hi,the order book is in the dataframe file named pd.HDFStore(order_book_store) right?!
if i want to import historical data with a defined datetime how can i do that?
thanks for the help.

**Comment by stefan-jansen** [comment]
Sounds like the correct storage location. To select a specific time during day you would use standard pandas slicing methods frequently used in the examples, such as `df.loc[idx["10:00":"11:'00", :], :]` if the datetime variable is your first index level. Keep in mind that the sample data includes only a single day.

Closing for now, please feel free to reopen if the issue persists.
