### ISSUE TITLE
Crypto

### ISSUE THREAD

**Issue by QuantFreedom1022** [stefan-jansen/machine-learning-for-trading#268]
I don't have a bug or antyhing but just an observation ... all of the crypto markets or most of them ... all give away the trade and tick data as well as the orderbook websockets for free ... if you check out the bybit and binance api you will see you can get all this historical data for free ... i was wondering if anyone has any experience translating all this information from this book over to crypto ... because it seems like it is this gigantic mess just to get info from the source and then you have to do all kinds of manipulation to it ... but crypto you just download it and its all done for you in nice and neat columns

**Comment by stefan-jansen** [comment]
I'll try to incorporate some crypto examples in the 3rd edition.
