### ISSUE TITLE
searching alpha- featuring engineering

### ISSUE THREAD

**Issue by angelowra** [stefan-jansen/machine-learning-for-trading#27]
Hi Stefen,
I have gone trough the algo, (lagged returns, etc) but at the end I did not understand how you have identified the alpha factor. I m basically missing the conclusion. 

thks Angelo

**Comment by stefan-jansen** [comment]
Hi Angelo,

I was going to respond to your other issue after updating the files. There should be tested notebooks for the first several chapters up in a day or two.

The feature engineering notebook (assuming you're referring to the one in chapter 4?) is just creating features that are hopefully predictive when used as inputs to a model. In this sense, this notebook does no arrive at a conclusion, it just prepares data for the next step. The point is evaluating the features, either on their own (e.g. using alphalens) or in the context of a model. Hope this helps!

Cheers, Stefan
