### ISSUE TITLE
ValueError: Please set your QUANDL_API_KEY environment variable and retry.

### ISSUE THREAD

**Issue by quant2008** [stefan-jansen/machine-learning-for-trading#275]
after run: zipline ingest -b quandl

I get the following error:

ValueError: Please set your QUANDL_API_KEY environment variable and retry.

I am using windows 10. what should I do?

**Comment by stefan-jansen** [comment]
Please see this guide on environment variables in Windows 10.

**Comment by AkshayVaghani** [comment]
Same  error r- ValueError: Please set your QUANDL_API_KEY environment variable and retry. How to set env variable in Window and where to get API key ?

**Comment by Eating-Sulfur** [comment]
? what is this?

Akshay ***@***.***> schrieb am Fr., 18. Aug. 2023, 17:13:

**Comment by AkshayVaghani** [comment]
sorry for confusion , This is error occurring while running single_factor_zipline notebook. I installed zipline-reloaded  and to run the notebook which suggested me to run  zipline ingest -b quandl and then get following error. 
ValueError: Please set your QUANDL_API_KEY environment variable and retry. I am using windows 11.

**Comment by AkshayVaghani** [comment]
basically I am getting following error while running
single_factor_zipline.ipynb notebook. Would you help ?

ValueError: SQLite file
'C:\\Users\\lalta\\.zipline\\data\\quandl\\2023-08-18T14;56;37.388452\\assets-7.sqlite'
doesn't exist.
Output is truncated. View as a scrollable element or open in a text editor.
Adjust cell output settings...

**Comment by MBounouar** [comment]
You need a QUANDL api key from https://data.nasdaq.com/ and set up the environment variable in windows
