### ISSUE TITLE
Would someone please provide all data for data/assets.h5 downloadable?

### ISSUE THREAD

**Issue by joshua-xia** [stefan-jansen/machine-learning-for-trading#276]
Becasue of some data source is NOT accessible now, so it is very  welcomed if someone provide data/assets.h5 contain all data downloadable.

Thanks a lot!

**Comment by stefan-jansen** [comment]
Copyright restrictions imposed by the sources prevent us from making the data available. Which sources are not accessible?

**Comment by stefan-jansen** [comment]
Closing for now, please feel free to reopen if you are facing issues with accessing the data (in case they are still available for free).
