### ISSUE TITLE
Chapter 12, 04_preparing_the_model_data.ipynb

### ISSUE THREAD

**Issue by sh0gg0th** [stefan-jansen/machine-learning-for-trading#278]
In the  deciles cells, `pd.qcut` doesn't want to handle series which are all `NaN` and throws  "IndexError: cannot do a non-empty take from an empty axes." I'm using pandas 1.5.2.

 I solved it somewhat crudely like this:

**Daily historical return deciles**
```
for t in T:
    prices[f'r{t:02}dec'] = (prices[f'r{t:02}']
                             .dropna()
                             .groupby(level='date')
                             .apply(lambda x: pd.qcut(x, 
                                                      q=10, 
                                                      labels=False, 
                                                      duplicates='drop')))
```

**Daily sector return deciles**
```
for t in T:
    prices[f'r{t:02}q_sector'] = (prices
                                  .groupby(['date', 'sector'])[f'r{t:02}']
                                  .transform(lambda x: pd.qcut(x, 
                                                               q=5, 
                                                               labels=False, 
                                                               duplicates='drop')
                                                       if not x.isnull().all() else np.nan))
```

**Comment by stefan-jansen** [comment]
Thanks @sh0gg0th, there's probably not much one can other than graceful error handling if there is simply no data available. Since it looks like you found a solution, I'll close this for now but pls feel free to reopen if you have further questions.

**Comment by SUSHANTH009** [comment]
> In the deciles cells, `pd.qcut` doesn't want to handle series which are all `NaN` and throws "IndexError: cannot do a non-empty take from an empty axes." I'm using pandas 1.5.2.
> 
> I solved it somewhat crudely like this:
> 
> **Daily historical return deciles**
> 
> ```
> for t in T:
>     prices[f'r{t:02}dec'] = (prices[f'r{t:02}']
>                              .dropna()
>                              .groupby(level='date')
>                              .apply(lambda x: pd.qcut(x, 
>                                                       q=10, 
>                                                       labels=False, 
>                                                       duplicates='drop')))
> ```
> 
> **Daily sector return deciles**
> 
> ```
> for t in T:
>     prices[f'r{t:02}q_sector'] = (prices
>                                   .groupby(['date', 'sector'])[f'r{t:02}']
>                                   .transform(lambda x: pd.qcut(x, 
>                                                                q=5, 
>                                                                labels=False, 
>                                                                duplicates='drop')
>                                                        if not x.isnull().all() else np.nan))
> ```

when I use this command I am getting all the rows of [f'r{t:02}dec'] this column as null

**Comment by andywatts** [comment]
```
for t in T:
    # Calculate deciles for each date
    def get_deciles(x):
        return pd.qcut(x, q=10, labels=False, duplicates='drop')

    prices[f'r{t:02}dec'] = (prices[f'r{t:02}']
                             .dropna()
                             .groupby(level='date')
                             .apply(get_deciles)
                             .reset_index(level=0, drop=True) # Reset index to avoid ambiguity
                             .reindex(prices.index)) # Reindex to match 'prices' index
```
