### ISSUE TITLE
04_q_learning_for_trading -> Error during Observation Space creation

### ISSUE THREAD

**Issue by hacky1610** [stefan-jansen/machine-learning-for-trading#284]
**Describe the bug**
The creation of a Box in trading_env.py:242 is failung. The Datatype of the parameters is not correct. It has to be an nd_array.

1. OPen 04_q_learning_for_trading
2. Execute all

**Expected behavior**
No error occurs

**Screenshots**
![image](https://user-images.githubusercontent.com/18327894/225560525-7b43f107-1aa1-48fc-9e4f-a84a191d9867.png)

**Environment**
jupyter/datascience-notebook:latest
 
Solution:
    self.observation_space = spaces.Box(self.data_source.min_values.to_numpy(),
                                            self.data_source.max_values.to_numpy())

**Comment by yeonmo317** [comment]
> **Describe the bug** The creation of a Box in trading_env.py:242 is failung. The Datatype of the parameters is not correct. It has to be an nd_array.
> 
> Steps to reproduce the behavior:
> 
>     1. OPen 04_q_learning_for_trading
> 
>     2. Execute all
> 
> 
> **Expected behavior** No error occurs
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/18327894/225560525-7b43f107-1aa1-48fc-9e4f-a84a191d9867.png)
> 
> **Environment** jupyter/datascience-notebook:latest
> 
> Solution: self.observation_space = spaces.Box(self.data_source.min_values.to_numpy(), self.data_source.max_values.to_numpy())

A million thanks! I was getting the same error and this worked :)
