### ISSUE TITLE
01_pandas_datareader_demo.ipynb from chapter 2

### ISSUE THREAD

**Issue by sgjohnson1981** [stefan-jansen/machine-learning-for-trading#285]
**Describe the bug**
A brief description of the bug and in which notebook/script it lives.
In the notebook located at this issue's title, pandas.datareader for yahoo finance is broken. Changing FB (which no longer exists as a ticker) to META didn't make any difference. On both occasions, the following error is thrown: string indices must be integers
I noticed FB is also fetched under the Quandl section, but I didn't complete the entire notebook since I noticed it seems nothing gets saved to disk to be used in later exercises.

**To Reproduce**
- In case you are not running the current version of the notebook/script as found on GitHub.
Ran as is.

Changed the code as below. Seems to work fine.
start = datetime(2014, 1, 1)
end = datetime(2017, 5, 24)

yahoo= yf.download('META', start=start, end=end)
yahoo.info()

**Comment by NicoNicoNico123** [comment]
I checked the module I think yahoo getting to paid model:

https://github.com/pydata/pandas-datareader/issues/962

**Comment by stefan-jansen** [comment]
Please create an issue in the pandas-datareader repo if this problem persists.
