### ISSUE TITLE
Mamba env installation fails

### ISSUE THREAD

**Issue by hacky1610** [stefan-jansen/machine-learning-for-trading#287]
**Describe the bug**
The installation of the python packages by means of the ml4t.yml file is failing.
I am getting the error: 

Encountered problems while solving:
  - package numpy-1.19.1-py36hbc911f0_0 requires mkl >=2019.4,<2021.0a0, but none of the providers can be installed
  - package libsqlite-3.40.0-h753d276_0 requires libzlib >=1.2.13,<1.3.0a0, but none of the providers can be installed

**To Reproduce**
1. Create a DOCKERFILE inside of the installation folder.
    The content should be 
    
    # Start from a core stack version
    FROM jupyter/datascience-notebook:python-3.8
    # Install in the default python3 environment
    COPY ./linux/ml4t.yml /var/tmp/ml4t.yml
    RUN conda create -n ml4t python=3.8
    RUN mamba env update -n ml4t -f /var/tmp/ml4t.yml
    RUN conda activate ml4t
2. run docker image build --tag jupyter/base-notebook:my_version .

**Comment by stefan-jansen** [comment]
I'd recommend to just install the packages you'll actually use given the notebooks of interest. Installation without pinned versions allows access to the latest versions but may fail due to conflicts given python version etc.
