### ISSUE TITLE
04_q_learning_for_trading -> experience_replay(self) --> predict q values gives shape mismatch error

### ISSUE THREAD

**Issue by yeonmo317** [stefan-jansen/machine-learning-for-trading#288]
### Error:

This line of code:
q_values[[self.idx, actions]] = targets 
Gives an error:
Exception has occurred: ValueError
shape mismatch: value array of shape (4096,) could not be broadcast to indexing result of shape (2,4096,3)
![bug reported v2](https://user-images.githubusercontent.com/129945927/230040259-71dc56f8-e790-4891-9bf0-1354df5c0975.jpg)

### Steps to reproduce: 
run 04_q_learning_for_trading.ipynb

### Environment: 
python 3.9

**Comment by Frxljord** [comment]
I found by replacing line 123 with :

        for i in self.idx:
            action = actions[i]
            q_values[self.idx][action] = targets[i]

the training works!
