### ISSUE TITLE
Add Multi GPU training in Folder 20 (TimeGAN) & 21 ( trading using reinforcement Learning)

### ISSUE THREAD

**Issue by developeralgo8888** [stefan-jansen/machine-learning-for-trading#29]
Tested the examples and they work fine on 1 GPU . i was trying to have it work on multiple GPUs ( 2 to 8 GPUs ). 

Any suggestions to train and test on multiple GPUs ?

**Comment by stefan-jansen** [comment]
Glad to hear the code works! I probably won't have the time unfortunately to revise the code to use multiple GPU but the [TensorFlow Guide](https://www.tensorflow.org/guide/distributed_training) on distributed training is quite comprehensive and should get you going pretty quickly.
