### ISSUE TITLE
ML4T Workflow - Vectorized versus event driven - script data.py not found on githup package

### ISSUE THREAD

**Issue by gmolinaro-git** [stefan-jansen/machine-learning-for-trading#290]
I cannot find the data.py script mentioned in the section "Vectorized versus event driven backtesting". Can someone provide it ?

**Comment by stefan-jansen** [comment]
You are probably looking for https://github.com/stefan-jansen/machine-learning-for-trading/blob/main/08_ml4t_workflow/00_data/data_prep.py
