### ISSUE TITLE
SARIMA notebook - huge amount of errors

### ISSUE THREAD

**Issue by shimritabraham** [stefan-jansen/machine-learning-for-trading#294]
**Describe the bug**
About 90% of this notebook shows errors
https://github.com/stefan-jansen/machine-learning-for-trading/blob/main/09_time_series_models/02_arima_models.ipynb

**To Reproduce**
- Load https://github.com/stefan-jansen/machine-learning-for-trading/blob/main/09_time_series_models/02_arima_models.ipynb

1. Go to 'https://github.com/stefan-jansen/machine-learning-for-trading/blob/main/09_time_series_models/02_arima_models.ipynb'
2. Scroll down
3. See error

**Expected behavior**
No errors upon loading

**Screenshots**
<img width="1005" alt="image" src="https://github.com/stefan-jansen/machine-learning-for-trading/assets/7744628/54406bce-4eb3-418c-ad2f-5285b43c7147">

<img width="999" alt="image" src="https://github.com/stefan-jansen/machine-learning-for-trading/assets/7744628/286da851-b189-4944-8e4d-80caf2bc06cf">

**Environment**
Chrome browser

**Additional context**
I love this tutorial!

**Comment by stefan-jansen** [comment]
The error is the result of `KeyboardInterrupt`. I just stopped the notebook because it was taking too long. Just remove the current outputs https://bobbyhadz.com/blog/jupyter-notebook-clear-cell-output
