### ISSUE TITLE
MESSAGE_TYPES.XLS CHAPTER 2 

### ISSUE THREAD

**Issue by ishikabansal77** [stefan-jansen/machine-learning-for-trading#295]
**Describe the bug**
I was trying to find message_types.xls file used in chapter 2, script 1 but wasn't able to. Kindly help.

**Comment by JeroenGoddijn** [comment]
I see it right in that chapter: [https://github.com/stefan-jansen/machine-learning-for-trading/tree/main/02_market_and_fundamental_data/01_NASDAQ_TotalView-ITCH_Order_Book](https://github.com/stefan-jansen/machine-learning-for-trading/tree/main/02_market_and_fundamental_data/01_NASDAQ_TotalView-ITCH_Order_Book)

**Comment by stefan-jansen** [comment]
Yes, it's right here: 02_market_and_fundamental_data/01_NASDAQ_TotalView-ITCH_Order_Book
