### ISSUE TITLE
facing error while installing ta-lib

### ISSUE THREAD

**Issue by ishikabansal77** [stefan-jansen/machine-learning-for-trading#297]
!pip install ta-lib==0.4.21

Collecting ta-lib==0.4.21
  Downloading TA-Lib-0.4.21.tar.gz (270 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 270.1/270.1 kB 5.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from ta-lib==0.4.21) (1.22.4)
Building wheels for collected packages: ta-lib
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for ta-lib (setup.py) ... error
  ERROR: Failed building wheel for ta-lib
  Running setup.py clean for ta-lib
Failed to build ta-lib
ERROR: Could not build wheels for ta-lib, which is required to install pyproject.toml-based projects

was not able to install ta-lib
<img width="731" alt="Screenshot 2023-07-21 192532" src="https://github.com/stefan-jansen/machine-learning-for-trading/assets/133491760/6811e248-fa53-4821-8cb2-2bee628eba1c">

**Comment by stefan-jansen** [comment]
You need to install TA-Lib source library, see pre-requisites. See [here](https://github.com/stefan-jansen/machine-learning-for-trading/tree/main/installation#pre-requisites-macos) for macOS and Linux and [here](https://blog.quantinsti.com/install-ta-lib-python/) for Windows.

**Comment by stefan-jansen** [comment]
Closing for now due to lack of activity. Feel free to reopen if issue persists.
