### ISSUE TITLE
%load_ext zipline

### ISSUE THREAD

**Issue by ishikabansal77** [stefan-jansen/machine-learning-for-trading#299]
----------------------------------------------------------------
ImportError                    Traceback (most recent call last)
Cell In[5], line 1
----> 1 get_ipython().run_line_magic('load_ext', 'zipline')

File ~\anaconda3\envs\baclass\lib\site-packages\IPython\core\interactiveshell.py:2369, in InteractiveShell.run_line_magic(self, magic_name, line, _stack_depth)
   2367     kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2368 with self.builtin_trap:
-> 2369     result = fn(*args, **kwargs)
   2371 # The code below prevents the output from being displayed
   2372 # when using magics with decodator @output_can_be_silenced
   2373 # when the last Python token in the expression is a ';'.
   2374 if getattr(fn, magic.MAGIC_OUTPUT_CAN_BE_SILENCED, False):

File ~\anaconda3\envs\baclass\lib\site-packages\IPython\core\magics\extension.py:33, in ExtensionMagics.load_ext(self, module_str)
     31 if not module_str:
     32     raise UsageError('Missing module name.')
---> 33 res = self.shell.extension_manager.load_extension(module_str)
     35 if res == 'already loaded':
     36     print("The %s extension is already loaded. To reload it, use:" % module_str)

File ~\anaconda3\envs\baclass\lib\site-packages\IPython\core\extensions.py:76, in ExtensionManager.load_extension(self, module_str)
     69 """Load an IPython extension by its module name.
     70 
     71 Returns the string "already loaded" if the extension is already loaded,
     72 "no load function" if the module doesn't have a load_ipython_extension
     73 function, or None if it succeeded.
     74 """
     75 try:
---> 76     return self._load_extension(module_str)
     77 except ModuleNotFoundError:
     78     if module_str in BUILTINS_EXTS:

File ~\anaconda3\envs\baclass\lib\site-packages\IPython\core\extensions.py:91, in ExtensionManager._load_extension(self, module_str)
     89 with self.shell.builtin_trap:
     90     if module_str not in sys.modules:
---> 91         mod = import_module(module_str)
     92     mod = sys.modules[module_str]
     93     if self._call_load_ipython_extension(mod):

File ~\anaconda3\envs\baclass\lib\importlib\__init__.py:127, in import_module(name, package)
    125             break
    126         level += 1
--> 127 return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1030, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1007, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:986, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:680, in _load_unlocked(spec)

File <frozen importlib._bootstrap_external>:850, in exec_module(self, module)

File <frozen importlib._bootstrap>:228, in _call_with_frames_removed(f, *args, **kwds)

File ~\anaconda3\envs\baclass\lib\site-packages\zipline\__init__.py:29
     27 from .utils.numpy_utils import numpy_version
     28 from .utils.pandas_utils import new_pandas
---> 29 from .utils.run_algo import run_algorithm
     31 # These need to happen after the other imports.
     32 from .algorithm import TradingAlgorithm

File ~\anaconda3\envs\baclass\lib\site-packages\zipline\utils\run_algo.py:24
     22 from zipline.finance import metrics
     23 from zipline.finance.trading import SimulationParameters
---> 24 from zipline.pipeline.data import USEquityPricing
     25 from zipline.pipeline.loaders import USEquityPricingLoader
     27 import zipline.utils.paths as pth

File ~\anaconda3\envs\baclass\lib\site-packages\zipline\pipeline\__init__.py:3
      1 from .classifiers import Classifier, CustomClassifier
      2 from .domain import Domain
----> 3 from .factors import Factor, CustomFactor
      4 from .filters import Filter, CustomFilter
      5 from .term import Term, LoadableTerm, ComputableTerm

File ~\anaconda3\envs\baclass\lib\site-packages\zipline\pipeline\factors\__init__.py:7
      1 from .factor import (
      2     CustomFactor,
      3     Factor,
      4     Latest,
      5     RecarrayField,
      6 )
----> 7 from .basic import (
      8     AnnualizedVolatility,
      9     AverageDollarVolume,
     10     DailyReturns,
     11     EWMA,
     12     ExponentialWeightedMovingAverage,
     13     ExponentialWeightedMovingStdDev,
     14     EWMSTD,
     15     LinearWeightedMovingAverage,
     16     MaxDrawdown,
     17     PeerCount,
     18     PercentChange,
     19     Returns,
     20     SimpleMovingAverage,
     21     VWAP,
     22     WeightedAverageValue,
     23 )
     24 from .events import (
     25     BusinessDaysSincePreviousEvent,
     26     BusinessDaysUntilNextEvent,
     27 )
     28 from .statistical import (
     29     RollingPearson,
     30     RollingSpearman,
   (...)
     34     SimpleBeta,
     35 )

File ~\anaconda3\envs\baclass\lib\site-packages\zipline\pipeline\factors\basic.py:21
      3 from numbers import Number
      4 from numpy import (
      5     arange,
      6     average,
   (...)
     18     errstate as np_errstate,
     19 )
---> 21 from zipline.pipeline.data import EquityPricing
     22 from zipline.utils.input_validation import expect_types
     23 from zipline.utils.math_utils import (
     24     nanargmax,
     25     nanmax,
   (...)
     28     nansum,
     29 )

File ~\anaconda3\envs\baclass\lib\site-packages\zipline\pipeline\data\__init__.py:1
----> 1 from .equity_pricing import EquityPricing, USEquityPricing
      2 from .dataset import (
      3     BoundColumn,
      4     Column,
   (...)
      7     DataSetFamilySlice,
      8 )
     10 __all__ = [
     11     "BoundColumn",
     12     "Column",
   (...)
     17     "USEquityPricing",
     18 ]

File ~\anaconda3\envs\baclass\lib\site-packages\zipline\pipeline\data\equity_pricing.py:7
      4 from zipline.utils.numpy_utils import float64_dtype, categorical_dtype
      6 from ..domain import US_EQUITIES
----> 7 from .dataset import Column, DataSet
     10 class EquityPricing(DataSet):
     11     """
     12     :class:`~zipline.pipeline.data.DataSet` containing daily trading prices and
     13     volumes.
     14     """

File ~\anaconda3\envs\baclass\lib\site-packages\zipline\pipeline\data\dataset.py:10
      7 from toolz import first
      9 from zipline.currency import Currency
---> 10 from zipline.data.fx import DEFAULT_FX_RATE
     11 from zipline.pipeline.classifiers import Classifier, Latest as LatestClassifier
     12 from zipline.pipeline.domain import Domain, GENERIC

File ~\anaconda3\envs\baclass\lib\site-packages\zipline\data\fx\__init__.py:4
      2 from .in_memory import InMemoryFXRateReader
      3 from .exploding import ExplodingFXRateReader
----> 4 from .hdf5 import HDF5FXRateReader, HDF5FXRateWriter
      6 __all__ = [
      7     "DEFAULT_FX_RATE",
      8     "ExplodingFXRateReader",
   (...)
     12     "InMemoryFXRateReader",
     13 ]

File ~\anaconda3\envs\baclass\lib\site-packages\zipline\data\fx\hdf5.py:96
      1 """
      2 HDF5-backed FX Rates
      3 
   (...)
     93 for column i in a data node is the ith element of /index/dts.
     94 """
     95 from interface import implements
---> 96 import h5py
     97 import logging
     98 import numpy as np

File ~\anaconda3\envs\baclass\lib\site-packages\h5py\__init__.py:33
     30     else:
     31         raise
---> 33 from . import version
     35 if version.hdf5_version_tuple != version.hdf5_built_version_tuple:
     36     _warn(("h5py is running against HDF5 {0} when it was built against {1}, "
     37            "this may cause problems").format(
     38             '{0}.{1}.{2}'.format(*version.hdf5_version_tuple),
     39             '{0}.{1}.{2}'.format(*version.hdf5_built_version_tuple)
     40     ))

File ~\anaconda3\envs\baclass\lib\site-packages\h5py\version.py:15
     10 """
     11     Versioning module for h5py.
     12 """
     14 from collections import namedtuple
---> 15 from . import h5 as _h5
     16 import sys
     17 import numpy

File h5py\h5.pyx:1, in init h5py.h5()

ImportError: DLL load failed while importing defs: The specified procedure could not be found.

**Comment by stefan-jansen** [comment]
Can't say much without know what your environment looks like. 

Please install zipline according to the current instructions [here](https://github.com/conda-forge/zipline-reloaded-feedstock)
