### ISSUE TITLE
back testing is not working 

### ISSUE THREAD

**Issue by AkshayVaghani** [stefan-jansen/machine-learning-for-trading#303]
Hi,

 it looks like zipline back testing is not working. Code from chp 4 and 5 cannot execute and throw errors. anyone would help ?

**Comment by SUSHANTH009** [comment]
> Hi,
> 
> it looks like zipline back testing is not working. Code from chp 4 and 5 cannot execute and throw errors. anyone would help ?

I think I can

**Comment by stefan-jansen** [comment]
Please use [this library](https://pypi.org/project/zipline-reloaded/)
