### ISSUE TITLE
No object named P in the file

### ISSUE THREAD

**Issue by Impesud** [stefan-jansen/machine-learning-for-trading#310]
**Describe the bug**
Hi, unfortunately I saw two errors in the code of chapter 2 and I can't find a solution.

In the file "01_parse_itch_order_flow_messages.ipynb" I see:

1."Cannot serialize the column [primary_market_maker]
because its data contents are not [string] but [integer] object dtype
L" , processes the binary file and produces the parsed orders stored by message type.

2. "'No object named P in the file'", in the last section of the code.

**Screenshots**
![Screenshot 2023-12-10 143240](https://github.com/stefan-jansen/machine-learning-for-trading/assets/1665536/e9b6b5ce-b468-42e9-97e7-1d8263ba035e)

**Environment**
VsCode v1.85
Python v1.8.10
JupytervVsCode extension v2023.11.1003402403

**Comment by Impesud** [comment]
Hi! I put the the solution here: 
https://github.com/Impesud/machine-learning-for-trading/blob/main/02_market_and_fundamental_data/01_NASDAQ_TotalView-ITCH_Order_Book/01_parse_itch_order_flow_messages.ipynb

View "Impesud Note" rows.

**Comment by 2f2a** [comment]
> Hi! I put the the solution here: https://github.com/Impesud/machine-learning-for-trading/blob/main/02_market_and_fundamental_data/01_NASDAQ_TotalView-ITCH_Order_Book/01_parse_itch_order_flow_messages.ipynb
> 
> View "Impesud Note" rows.

I had the same issue: "..Cannot serialize.." 
But your ("Impesud Note") version solved it.

Im on Linux, and use uptodate modules also, just had to rewrite the "Path".

Another difference: "store.append" vs "store._append", <- pandas.HDFStore last line, uhg, so the fix doesn't fix rollback versions of modules, that are suggested to use..

**Comment by Impesud** [comment]
Hi @2f2a 
In fact, store._append does not completely solve the problem. We should try again with the concat method, as I did, and find the right way to keep the Q column with the table format, eliminating the fixed one.

**Comment by mahdic200** [comment]
I have the same problem . it's OK when you print the heads but when you try to read the Object it gives you an unpredictable error which is shown above . please help , this repository and this book are vital for me . I currently gaining more information about all the used packages in chapter 2 , to be able to solve this issue . but now , I really need help .

**Comment by stefan-jansen** [comment]
DId you look at the [installation instructions](https://github.com/stefan-jansen/machine-learning-for-trading/tree/main/installation).

**Comment by stefan-jansen** [comment]
Closing for now as my understanding is that this has been resolved, feel free to reopen if otherwise.

**Comment by mahdic200** [comment]
install python3.8 and the mentioned version of modules (like pandas and numpy ) in [installation](https://github.com/stefan-jansen/machine-learning-for-trading/tree/main/installation) directory .
in this case : 
pandas 1.2.5
numpy 1.20.3

> [!WARNING]
> do not install all modules together , just the imported ones in this specific notebook . otherwise you will be crazy of the error volume you will encounter .

I solved the problem . I didn't know there is an [installation](https://github.com/stefan-jansen/machine-learning-for-trading/tree/main/installation) directory which has instructions and guide to setup an appropriate environment for this  book's jupyter notebooks . 

in the mentioned directory everything is explained perfectly .

here are the steps I did to fix this issue :

1. I installed python 3.8 with pyenv
2. created a virtual environment using python venv and the python3.8 in the cloned project directory
3. updated my virtual environment pip to the latest
4. installed the imported modules in the chapter02 notebook01 according to the mentioned versions in [installation/linux/ml4t.txt](https://github.com/stefan-jansen/machine-learning-for-trading/tree/main/installation/linux/ml4t.txt) file (I'm using linux ) using the latest version of pip.
5. then opened my vscode and I reselected the python kernel to my virtual environment python (I have installed related jupyter notebook extensions in my vscode and I'm using vscode environment but you can use miniconda or anything else  which you are comfortable with)

and issue fixed .

the key was to install the appropriate python version and right pandas version mentioned in the [installation](https://github.com/stefan-jansen/machine-learning-for-trading/tree/main/installation) directory .
