### ISSUE TITLE
Twitter data gone? Broken link in "data/twitter_sentiment.ipynb"

### ISSUE THREAD

**Issue by 2f2a** [stefan-jansen/machine-learning-for-trading#311]
**Describe the bug**
Hi, "data/twitter_sentiment.ipynb" is broken. Needs:

'http://cs.stanford.edu/people/alecmgo/trainingandtestdata.zip' <- That don't exist

-- mvh.

**Comment by stefan-jansen** [comment]
See [this page](https://snap.stanford.edu/data/twitter7.html).
