### ISSUE TITLE
Unable to replicate backtest performance | Chapter 8 02_backtesting_with_zipline

### ISSUE THREAD

**Issue by benhsampson** [stefan-jansen/machine-learning-for-trading#312]
Running the notebook myself, the backtest performs worse. Note that I've imported the notebook and not made any modifications.

**My run**
![image](https://github.com/stefan-jansen/machine-learning-for-trading/assets/27483525/20d0e3a8-dff8-4c67-94f2-96fd8510f69f)

**From repo**
![image](https://github.com/stefan-jansen/machine-learning-for-trading/assets/27483525/fdbb593d-fb5b-40f6-980c-94c254112635)

**Environment**
Python 3.8
Here's the important dependencies in `requirements.txt` file after running `pip freeze > requirements.txt`
```
TA-Lib==0.4.28
zipline-reloaded==2.1.1
pyfolio-reloaded==0.9.4
```
 
- OS: Windows
- Version: 11

**Comment by BlockchainPunks** [comment]
if possible - would you mind exporting your .yml files for your **ml4t** and **backtester** environments then attach them here.

you can do that using conda command.

The install instructions are messed - i'm looking for working windows exact package list which steps below will give 
here are steps:
https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#sharing-an-environment

this will help allot of the windows people - so would really appreciate your help

**Comment by stefan-jansen** [comment]
Can be differences in data (which may change depending on when you download), differences in the trained model, etc. 

I"m sorry but the goal is to show you how you can run this, not to claim specific performance so I can't help much further, thanks for your understanding.
