### ISSUE TITLE
Install instructions for windows and linux suck - no offence

### ISSUE THREAD

**Issue by BlockchainPunks** [stefan-jansen/machine-learning-for-trading#316]
At the start of the install document you indicate don't install all the packages but rather install packages for relevant chapter.

Problem 1: at start of each chapter - you don't indicate which packages for the chapter are required - if it needs separate ones per chapter then provide a .yml or .txt file + conda command to install that chapters packages 

Problem 2: you then go on to indicate the packages can all be installed using mt4t-base.txt (Which contradicts the start of your install instructions) - which one is it? As you clearly state don't install all at once.

While your book makes really good sense - the notebooks don't run - each with different package failures.

If possible: its 2024 : Please provide clear install steps for Windows Or Linux environment. (Take out the deprecated stuff and move into separate deprecated file)

Note: Packages do change over time - so maybe create working .yml file that indicates exact versions required. 
i.e. if you setup 1 environment with all working then export the .yml file it should then work on every persons machine for that platform.

i.e. create 1 for osx- export .yml with exact versions of packages needed (after you tested they all run on that platform) - then repeat for  linux and then again for windows.

Apologies if I sound annoyed - Book was an expensive purchase and expected the notebooks to at least run (+ install instructions to work).

Example: Add cell at top of your notebook to install the packages required for that notebook:

import sys
!{sys.executable} -m pip install numpy
!{sys.executable} -m pip install python-binance
!{sys.executable} -m pip install pandas
!{sys.executable} -m pip install statsmodels
!{sys.executable} -m pip install matplotlib

**Comment by stefan-jansen** [comment]
Thank you for your message. I'm so sorry you are so frustrated with the installation that you must express yourself this way.

I've provided different installation instructions, for instance, here: https://github.com/stefan-jansen/machine-learning-for-trading/tree/main/installation

These include pip requirement and conda env files for Linux and Windows, which you ask for, but also for macOS. It also has those with detailed versions and with the top-level libraries only.

Unfortunately, there are 150 notebooks with over 400 libraries and Python dependencies, which creates many potential conflicts and makes it difficult to maintain as things evolve. 

Also, completely unnecessary. The required packages are already listed in the import section. If you run it and don't have any of these packages, pip will tell you. You'd respond using code along the lines you post.  It really just boils down to 

```bash
pip install package1 package2 ...
```

Now, you may find that you lack some dependencies, such as an underlying system library. You would then proceed to that library's documentation.

Hope this helps.
