### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by cody-vandervoort** [stefan-jansen/machine-learning-for-trading#32]
when I run docker run -it -v $(pwd):/home/packt/ml4t -p 8888:8888 -e QUANDL_API_KEY=*****myapi******- --name ml4t appliedai/packt:latest bash

from command line after installing docker desktop and allocating 4gb ram i get this:

 docker: error during connect: Post https://192.168.99.100:2376/v1.40/containers/create?name=ml4t: dial tcp 192.168.99.100:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
See 'docker run --help'.

any help to get me on the right track would be greatly appreciated, so far i've just been trying to run the code in pycharm or jupyter notebooks with abit of trouble

**Comment by stefan-jansen** [comment]
Sorry to hear. Are you on Windows? If so, see discussion and proposed solutions [here](https://github.com/docker/for-win/issues/2575) and [here](https://github.com/docker/for-win/issues/2596). Perhaps 4GB is too low for the memory.
Please let me know if you continue to experience issues.

**Comment by cody-vandervoort** [comment]
Hey thanks so much for the reply! It's all good I really appreciate your book and all of these examples, I am on windows, 8gb 4 core, I was learning how to enable hyper virtualization to make a VM with gcp to run docker, but i decided to upgrade to windows pro to see if it would work on my computer, perhaps 4gb is too low, i see that the error at the link you provided matches mine so that gives me hope, otherwise i've been trying to run within AI notebooks on google platform, on the section of downloading and building the nazdaq tick data, I was getting stuck at loading the .lxlm file or whatever it is exactly i was getting caught within the code as the variable was not defined but I couldn't open it up in editor to be able to know exactly what to do with it, I did not have time to read through the 32 pages of documentation you linked to referring to that file but I was wondering if you could include how I integrate that file into the code for the section downloading the order book? I couldn't open it im not sure how I work it, Thanks so much for your quick reply!

**Comment by stefan-jansen** [comment]
Hi @cody-vandervoort, I added some remarks regarding the resource-hungry exercises like the NASDAQ ticker data one. You'll probably need more than 16GB RAM to run this. 

Not sure which lxml file you're referring to? There's an .xlsx file in this notebook: https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/02_market_and_fundamental_data/01_NASDAQ_TotalView-ITCH_Order_Book/01_parse_itch_order_flow_messages.ipynb.
It provides info on the message types that is then use to parse the binary data, like how long each field is, what data type, etc.

Keep in mind that it's not super important to execute it yourself as it is mainly intended to demonstrate how data in an institutional investor context works where you would a custom-built platform to handle much larger data. Nothing in the book builds on it.

I'm going to close this for now, feel free to reopen if you continue to run into issues.

**Comment by cody-vandervoort** [comment]
Thanks, Yeah I was referring to the xlsx file, I was running through Jupiter notebooks in the google AI lab, but once I downloaded the order book and tried to parse, it came up as , I can’t recall exactly now but “‘module_name” not defined I think, as it seemed like it was referring to something that was missing in the xlsx file that I’m not sure how to integrate into the code to continue the parsing, I was just trying to execute all the code from the start so that I could create all the necessary files for the later chapters. I’ll see if I can just skip that but I thought I should learn how to integrate to xlsx file, do I need to pip install xlsx reader for the file to be able to be called into action within the the tick data notebook?
