### ISSUE TITLE
no data.h5: '../12_gradient_boosting_machines/data.h5'

### ISSUE THREAD

**Issue by 672819398** [stefan-jansen/machine-learning-for-trading#321]
**Describe the bug**
A brief description of the bug and in which notebook/script it lives.

**To Reproduce**
- In case you are not running the current version of the notebook/script as found on GitHub.

**Expected behavior**

**Screenshots**

**Environment**
If you are not using the latest version of the Docker imag:
 
- OS: [e.g. MacOSX, Windows, Ubuntu]
 - Version [e.g. Big Sur, 10, 20.04]

**Additional context**

**Comment by stefan-jansen** [comment]
Data is created [here](https://github.com/stefan-jansen/machine-learning-for-trading/blob/main/12_gradient_boosting_machines/04_preparing_the_model_data.ipynb).

**Comment by rajatanand86** [comment]
I am new to this and in this link there is a line at 27 DATA_STORE = '../data/assets.h5'
where to get this .h5 file?

**Comment by tinkerdragon** [comment]
Theres a notebook for data creation that u have to run first. Look at the
github repo

**Comment by stefan-jansen** [comment]
@rajatanand86 and that folder is linked in my post just above your question.

**Comment by rajatanand86** [comment]
Yes, Please excuse for a relatively simple question.
in the link you shared, in the 27th line, below code is there where we have to Load Quandl Wiki Stock Prices & Meta Data

DATA_STORE = '../data/assets.h5'
ohlcv = ['adj_open', 'adj_close', 'adj_low', 'adj_high', 'adj_volume']
with pd.HDFStore(DATA_STORE) as store:
    prices = (store['quandl/wiki/prices']
              .loc[idx[START:END, :], ohlcv] # select OHLCV columns from 2010 until 2017
              .rename(columns=lambda x: x.replace('adj_', '')) # simplify column names
              .swaplevel()
              .sort_index())
    metadata = (store['us_equities/stocks'].loc[:, ['marketcap', 'sector']])

where to get this assets.h5 file?
