### ISSUE TITLE
Ch 11-5 LightGBM  Random Forest & Ch 12-5/8 LightGBM and Catboost Prediction Probability Scores

### ISSUE THREAD

**Issue by hbtholen** [stefan-jansen/machine-learning-for-trading#324]
I have reproduced the notebooks of chapter 11 and partly the notebooks of chapter 12 and I am interested in the probability score of the predictions made:

I would like to calculate the probability score for each lgb - random forest regression prediction. I know, normally you should fit the model via the LGBMClassifier to get the predict_proba variable and hereby the following scores. However, I cannot reproduce this in (for example) the training and test data in notebook ch11-5 random forest return signals. Does anyone know how to implement such probability scores in (for example) the notebook ch11-5 random forest return signals or ch12-5 or ch12-8?

**Comment by stefan-jansen** [comment]
You are referring to a regression problem. Probability scores typically appear in classification problems. You could convert the problem by re-labeling the outputs, for instance.
