### ISSUE TITLE
For the alpha101 factor, how do you consider the stock's suspension period in your calculation process?

### ISSUE THREAD

**Issue by berisfu** [stefan-jansen/machine-learning-for-trading#327]
**Describe the bug**
A brief description of the bug and in which notebook/script it lives.

**To Reproduce**
- In case you are not running the current version of the notebook/script as found on GitHub.

**Expected behavior**

**Screenshots**

**Environment**
If you are not using the latest version of the Docker imag:
 
- OS: [e.g. MacOSX, Windows, Ubuntu]
 - Version [e.g. Big Sur, 10, 20.04]

**Additional context**

**Comment by stefan-jansen** [comment]
Please clarify.
