### ISSUE TITLE
Installation \Environments\ no Windows path

### ISSUE THREAD

**Issue by hadihedge** [stefan-jansen/machine-learning-for-trading#34]
Stefan - congrats on the new book. I am trying to replicate the environments you have provided but the directory has installations for Linux only. Zipline on the other hand is very fiddly. I will attempt the docker images but would have preferred to work on my local computer. Thanks for your custom and insights.

**Comment by stefan-jansen** [comment]
Thank you @hadihedge! You can (most likely) use the linux `.yml` files [here](https://github.com/stefan-jansen/machine-learning-for-trading/tree/master/installation/environments/linux); `conda` will complain about some files that it can't find, just delete them from the file and try again. 

For `zipline`, the `ml4t_zipline.yml` environment will install the [patched version](https://github.com/stefan-jansen/zipline); I have not yet tested this on Windows but anecdotal evidence suggests it should work.

Please let me know if you run into any issues with this approach and I'll see that I install a Windows environment to properly test setup.

**Comment by stefan-jansen** [comment]
Closing for now, feel free to reopen if issue persists.

**Comment by antkealy** [comment]
Stefan,

Is it fair to say that readers of the book using windows should focus on the docker installation method? I tried creating a conda environment on a windows machine using the linux .yml file and got the below:

ResolvePackageNotFound:
  - libxkbcommon=0.10.0
  - libgcc-ng=9.2.0
  - gmp=6.2.0
  - gxx_impl_linux-64=7.5.0
  - libedit=3.1.20191231
  - gxx_linux-64=7.5.0
  - libgfortran-ng=7.5.0
  - ld_impl_linux-64=2.34
  - dbus=1.13.14
  - graphviz=2.42.3
  - nspr=4.25
  - libuuid=2.32.1
  - libxgboost=1.0.2
  - libtool=2.4.6
  - readline=8.0
  - gcc_linux-64=7.5.0
  - _openmp_mutex=4.5
  - nss=3.47
  - gst-plugins-base=1.14.5
  - gcc_impl_linux-64=7.5.0
  - ta-lib-base=0.4.0
  - binutils_linux-64=2.34
  - py-xgboost=1.0.2
  - libgomp=9.2.0
  - ncurses=6.2
  - libstdcxx-ng=9.2.0
  - gstreamer=1.14.5
  - xgboost=1.0.2
  - binutils_impl_linux-64=2.34

As you mentioned in an earlier comment, I deleted these from the linux file and tried again to create the conda environment but it appeared to result in way too many conflicts. When do you expect to have a tested windows .yml file (you mentioned this was something you were looking into) or should I just proceed with the docker installation approach?

Thanks for your help - I'm looking forward to working through the book!
