### ISSUE TITLE
ResolvePackageNotFound: error (window os)

### ISSUE THREAD

**Issue by silent0506** [stefan-jansen/machine-learning-for-trading#36]
Hello. I recently bought a book(**first edition**) and am reading it well. Thank you.

I'm going to practice the code.

Using 'conda env create -f environment.yml'

I was trying to install my environment, but the following error occurred:

What should I do? (I am a Windows os user.)

`ResolvePackageNotFound:

binutils_impl_linux-64=2.28.1
gxx_impl_linux-64=7.2.0
gxx_linux-64=7.2.0
libgcc-ng=8.2.0
libstdcxx-ng=8.2.0
readline=7.0
gcc_linux-64=7.2.0
gmp=6.1.2
libuuid=1.0.3
gstreamer=1.14.0
graphviz=2.40.1
dbus=1.13.2
binutils_linux-64=7.2.0
expat=2.2.6
libgfortran-ng=7.3.0
gcc_impl_linux-64=7.2.0
ncurses=6.1
gst-plugins-base=1.14.0
libedit=3.1.20170329`

**Comment by stefan-jansen** [comment]
Hi @silent0506, 

thank you for your interest in the book. You can just delete these packages form the `environment.yml` file. However, the `first_edition` branch also contains a file tailored to Windows, you may want to use this instead.

The second edition has been released a few weeks ago and contains a lot of additional material; I would highly recommend you review the notebooks in this repo as well, you may find it quite useful.

**Comment by silent0506** [comment]
Thank you for your kind answer.I have one more question to ask you.Where can I find the tailored to Windows file?Can you tell me url?Thank you.
------ Original Message ------
Date: Thursday, Sep 10, 2020 09:17:44 AM

**Comment by silent0506** [comment]
Thank you for your kind reply.
I
 found the environment_windows.yml from the first_edition branch and installed it well and am using it well.
I have one additional question.

Where can I find the zipline installation files for Windows in Python 3.5 environments to use Chapter 4 through 5?

In this chapter folder, i could only find file for linux. Do you provide an installation file for Windows os ?


> Hi @silent0506,
> 
> thank you for your interest in the book. You can just delete these packages form the `environment.yml` file. However, the `first_edition` branch also contains a file tailored to Windows, you may want to use this instead.
> 
> The second edition has been released a few weeks ago and contains a lot of additional material; I would highly recommend you review the notebooks in this repo as well, you may find it quite useful.

thank
