### ISSUE TITLE
Thank you for your kind reply.

### ISSUE THREAD

**Issue by silent0506** [stefan-jansen/machine-learning-for-trading#37]
Thank you for your kind reply.
I
 found the environment_windows.yml from the first_edition branch and installed it well and am using it well.
I have one additional question.

Where can I find the zipline installation files for Windows in Python 3.5 environments to use Chapter 4 through 5?

In this chapter folder, i could only find file for linux. Do you provide an installation file for Windows os ?

> Hi @silent0506,
> 
> thank you for your interest in the book. You can just delete these packages form the `environment.yml` file. However, the `first_edition` branch also contains a file tailored to Windows, you may want to use this instead.
> 
> The second edition has been released a few weeks ago and contains a lot of additional material; I would highly recommend you review the notebooks in this repo as well, you may find it quite useful.

thank

_Originally posted by @silent0506 in https://github.com/stefan-jansen/machine-learning-for-trading/issues/36#issuecomment-690355090_

**Comment by stefan-jansen** [comment]
You can use the so docker image as explained in the installation instructions for the 2nd edition. I would generally strongly recommend the 2nd edition as it has much improved and expanded content.

Alternatively, you could modify the .yml file by removing Linux-specific packages and prepare windows for ziplineaccording to their instructions.
