### ISSUE TITLE
Installation/Docker issue

### ISSUE THREAD

**Issue by tsferro2** [stefan-jansen/machine-learning-for-trading#38]
I've downloaded Docker for windows but have encountered a couple issues when attempting to follow the steps here: https://github.com/PacktPublishing/Machine-Learning-for-Algorithmic-Trading-Second-Edition/blob/44c03418255a196c74b698c7d8a1cb82d5c7fa5f/installation/README.md.

- in #2 it is unclear what repo we should be cloning ("git clone...?") as I cannot find any "starter repo" on github or Docker hub. My best guess was to clone the entire:  https://github.com/PacktPublishing/Machine-Learning-for-Algorithmic-Trading-Second-Edition

- in #4 when I attempt to run:
`docker run -it -v $(pwd):/home/packt/ml4t -p 8888:8888 -e QUANDL_API_KEY=XXXXXX --name ml4t appliedai/packt:latest bash`

It throws the following error:
`docker: invalid reference format.`

any feedback is much appreciated!

**Comment by stefan-jansen** [comment]
Please use only this repo, not the version published by Packt.
- You should be cloning this repo, so the command becomes `git clone https://github.com/stefan-jansen/machine-learning-for-trading.git`.
- I'm assuming you have replaced `XXXX` with your actual API key. The implication of the error is explained [here](https://techoverflow.net/2019/10/14/how-to-fix-docker-invalid-reference-format/). You may, for instance, have inadvertently added a space after `$(pwd)` or need to use `${pwd}`.

Closing for now; please feel free to reopen this issue if you continue to have difficulties getting this to work.
