### ISSUE TITLE
get_wiki_constitutents

### ISSUE THREAD

**Issue by shortvol** [stefan-jansen/machine-learning-for-trading#4]
Hi, 

I recently purchased your book. I am working through through 4th chapter on alpha factor research. The get_data script in packt repo has a get_wiki_constitutents function. I believe the quandl link for that function might have changed, is there a new link i can try?

https://www.quandl.com/api/v3/databases/WIKI/codes?api_key=<API_KEY>

The link for prices file works fine

**Comment by stefan-jansen** [comment]
Sorry for the late response, Quandl has moved this to https://www.quandl.com/databases/WIKIP/documentation, I've updated `get_data.py` and the instructions accordingly.
