### ISSUE TITLE
Docker Installation 

### ISSUE THREAD

**Issue by cody-vandervoort** [stefan-jansen/machine-learning-for-trading#40]
HI there,

I'm attempting to do a fresh install of the ml4t setup within docker desktop on windows 10 pro. 
 Having trouble with the docker run -it -v line you provided, even after downloading the directory and switching into that folder with "cd"  whether it be the unzipped machine learning for trading/ folder or down to env/linux/ where the .yaml file is for zipline ect, 

each time I run docker run -it -v $(pwd):/home/packt/ml4t -p 8888:8888 -e QUANDL_API_KEY=<myapikeyhere-> --name ml4t appliedai/packt:latest bash

i get back the system cannot find the file specified.

I have also linked the file within docker>resources 

When I put in the docker getting started example "docker run" file into my cmd terminal I am able to get dockers "getting started" repo or whatever it is called no problem, but no matter what i try i just get system cannot find the file specified when trying to setup, 

I've just wiped my whole machine to start fresh for this, I was thinking to set back up with linux mint because i was looking into someone elses issue of setting up linux no problem, but docker desktop isnt for linux so It just went with windows since i already upgrated to pro for it, but still facing this issue either way not sure what to do., I was trying to set up with andaconda last night but everytime I setup the zipline_env and activated I got hit with the giant list of missing dependancies so I was like okay I clearly need to setup the image in the docker environment to make it work, but not i just cant get the file located to do so, 

Im super excited to get this set up though

I greatly appreciate your help with this and the insights you're sharing through the book I was wondering if you had a ebook or audio copy so I could listen as well to consumer the information in multiple ways, i just dont have any money to buy the ebook on packt right now or i would I could just see myself being able to slide in another 15-20 hours just listening to the book on top of what im already trying to consume, just thought id ask so i could consume in the most efficient amount of time as possible, this is my sole task/ goal right now. 

Thanks again, have a good one.

**Comment by stefan-jansen** [comment]
Hi @cody-vandervoort, sorry you're having issues with the docker image. 

The exact command you need to run is
```bash
docker run -it -v $(pwd):/home/packt/ml4t -p 8888:8888 -e QUANDL_API_KEY=<your API key> --name ml4t appliedai/packt:latest bash
```
where `<your API key>` should be the Quandl API key for your account. 

The part `$(pwd)` references your current working directory and works on linux and mac os. This may be breaking on windows, so could you please it replace it with the absolute path to the root folder of the unzipped ML4T repo?

[Here](https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c)'s a bit more detail on setup on Windows; you will probably also give docker permissions to access your drive as explained in the first step in the article. 

I hope this helps, please let me know if you have additional questions.

**Comment by cody-vandervoort** [comment]
Thanks for the reply, the article you linked their describes information
for what seems to be an outdated docket gui because the adding directory
settings/ interface is a lot different on Docker Desktop anyways.

And so I’m not mistaken keep the brackets around (pwd) but where pwd is
replace with C:\Desktop\ML\machine-learning-for-trading\

For example?

I redowloaded git, seems like there’s an extra 900mb that comes with
cloning git repo rather than downloading via zip, I had the correct quandl
API I just took it out for public reference, also perhaps I had not yet
logged in to dockerhub revolving my ability to clone from your docker hub
account, thanks for the response I’ll keep working at this and let u know
what works

Would you run this on Linux yourself? If so what version of docket do you
use? Socker engine?

**Comment by cody-vandervoort** [comment]
I went onto dockerhub and downloader the repo with docker pull
appliedai/packt:latest, downloading that hopefully i can figure it out from
here, mainly for the focus of getting the zipline environment up, thats
where im at anyways ive been exploring with jupyter other than than for a
few months now., Thank you for writing your book its so great to find such
a rich piece information like this

**Comment by cody-vandervoort** [comment]
at this point I have been able to get into the terminal for the docker container but im missing adding my quandl API 

after pulling the container, and numerous youtube videos to find some traction,  I ran `docker run -it appliedai/packt `bash`` this got me into the interactive terminal for `packt@-ID-:~/ml4t$` where i then added `conda activate ml4t-zipline` all went well, but i couldnt ingest the zipline data because I did not enter my quandle API yet, might have to reset the docker image now im close im sure ill figure it out haha

**Comment by cody-vandervoort** [comment]
Okay i get it, had to open powershell from the unzipped directory

**Comment by cody-vandervoort** [comment]
PermissionError: [Errno 13] Permission denied: '/home/packt/ml4t/data' 

i still get this error when I try to ingest zipline data hmm

**Comment by cody-vandervoort** [comment]
i will try again from admin cmd aha

**Comment by cody-vandervoort** [comment]
idk it worked now haha downloading
