### ISSUE TITLE
Cannot access Jupyter Notebook from Dockers container.

### ISSUE THREAD

**Issue by cheenweekiang** [stefan-jansen/machine-learning-for-trading#41]
Thank you for sharing this awesome work.

I am using windows and  following the dockers workflow, currently i am stuck at step 7 on opening the jupyter notebook. 

   (base) packt@1154ebfb6453:~/ ml4t$ conda activate ml4t 

(ml4t) packt@1154ebfb6453:~/ml4t$ jupyter notebook --ip 0.0.0.0 --no-browser --allow-root
 [I 09:37:37.174 NotebookApp] [nb_conda_kernels] enabled, 4 kernels found
 [I 09:37:37.184 NotebookApp] Writing notebook server cookie secret to 
 /home/packt/.local/share/jupyter/runtime/notebook_cookie_secret
 [I 09:37:39.115 NotebookApp] JupyterLab extension loaded from /opt/conda/envs/ml4t/lib/python3.7/site-packages/jupyterlab
 [I 09:37:39.115 NotebookApp] JupyterLab application directory is /opt/conda/envs/ml4t/share/jupyter/lab
 [I 09:37:39.118 NotebookApp] Serving notebooks from local directory: /home/packt/ml4t
 [I 09:37:39.118 NotebookApp] The Jupyter Notebook is running at:
 [I 09:37:39.118 NotebookApp] http://1154ebfb6453:8888/?token=ffbf0a92a3c46f4d3cbbffab66a66d144dc3a23c0a93bb6f
 [I 09:37:39.118 NotebookApp]  or http://127.0.0.1:8888/?token=ffbf0a92a3c46f4d3cbbffab66a66d144dc3a23c0a93bb6f
 [I 09:37:39.118 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
 [C 09:37:39.122 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///home/packt/.local/share/jupyter/runtime/nbserver-296-open.html
    Or copy and paste one of these URLs:
        http://1154ebfb6453:8888/?token=ffbf0a92a3c46f4d3cbbffab66a66d144dc3a23c0a93bb6f
     or http://127.0.0.1:8888/?token=ffbf0a92a3c46f4d3cbbffab66a66d144dc3a23c0a93bb6f

i copy and paste this url http://127.0.0.1:8888/?token=ffbf0a92a3c46f4d3cbbffab66a66d144dc3a23c0a93bb6f on the browser to open up jupyter notebook but was prompted to an authentication page as follows

![image](https://user-images.githubusercontent.com/33094161/95012188-f1eae280-0668-11eb-8afd-5366de352098.png)

I have tried the following but still fail to access the jupyternotebook 

- entering the authentication token code ffbf0a92a3c46f4d3cbbffab66a66d144dc3a23c0a93bb6f

- running this command before running jupyter notebook --ip 0.0.0.0 --no-browser --allow-root  jupyter notebook --NotebookApp.token='' to clear authentication 

Thank you for your help.

**Comment by stefan-jansen** [comment]
Could you please check if you have another process using port 8888 (eg jupyter..) running on your windows host as described [here](https://stackoverflow.com/questions/48198/how-can-you-find-out-which-process-is-listening-on-a-port-on-windows)?

**Comment by cheenweekiang** [comment]
Thank you for your reply. 
I exited the dockers and ran the code  Get-Process -Id (Get-NetTCPConnection -LocalPort 8888).OwningProcessas shown below. 
Not really sure what this is. 

![image](https://user-images.githubusercontent.com/33094161/95014168-b4418600-0677-11eb-8ac6-46068bee1ab9.png)

Appreciate your help here.

**Comment by stefan-jansen** [comment]
This suggest you have a jupyter server running on your windows host that conflicts with the one inside docker re port usage. Please stop this service and retry using docker; you will likely have to remove the docker container you just created to avoid naming conflicts.

**Comment by cheenweekiang** [comment]
thank you stefan. 

I manage to rerun this using this command and able to launch the jupyter lab but i can't create new notebooks.
 thank you for your help. 

 docker run -p 8888:8888 -it -v ml4t appliedai/packt:latest bash

![image](https://user-images.githubusercontent.com/33094161/95020823-12825f00-06a0-11eb-9408-1347bf797100.png)

![image](https://user-images.githubusercontent.com/33094161/95020956-d0a5e880-06a0-11eb-95dc-377f18edaf7a.png)

**Comment by stefan-jansen** [comment]
Did you enable docker permissions as outlined in the article [linked](https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c) in the installation instructions? I think the GUI has changed a bit but the idea is the same.

**Comment by cheenweekiang** [comment]
Thanks Stefan for the advice. 
After much research and consulting with friend,  I found out window 10 home version is not compatible(which i am using) to the docker option. I do not see the file sharing option on mine dockers (per screenshot). I am going to explore the miniconda or virtual enviroment option although is a pain or i might upgrade my terminal to window 10 pro version.

![image](https://user-images.githubusercontent.com/33094161/95294048-29df6900-08a7-11eb-9e75-b4c42cd532aa.png)

**Comment by stefan-jansen** [comment]
I have updated the installation instructions to clarify how to use Docker with Windows 10 Home. I've just tested, it works just fine after enabling the WSL 2 backend and the virtual machine platform as outlined in the [docs](https://docs.docker.com/docker-for-windows/install-windows-home/).

**Comment by cheenweekiang** [comment]
Thanks you Stefan. I followed the steps from the link. I can acess the notebooks with the files now. :1st_place_medal:
