### ISSUE TITLE
Windows .yml file

### ISSUE THREAD

**Issue by antkealy** [stefan-jansen/machine-learning-for-trading#42]
Stefan,

Is it fair to say that readers of the book using windows should focus on the docker installation method? I tried creating a conda environment on a windows machine using the linux .yml file and got the below:

ResolvePackageNotFound:

libxkbcommon=0.10.0
libgcc-ng=9.2.0
gmp=6.2.0
gxx_impl_linux-64=7.5.0
libedit=3.1.20191231
gxx_linux-64=7.5.0
libgfortran-ng=7.5.0
ld_impl_linux-64=2.34
dbus=1.13.14
graphviz=2.42.3
nspr=4.25
libuuid=2.32.1
libxgboost=1.0.2
libtool=2.4.6
readline=8.0
gcc_linux-64=7.5.0
_openmp_mutex=4.5
nss=3.47
gst-plugins-base=1.14.5
gcc_impl_linux-64=7.5.0
ta-lib-base=0.4.0
binutils_linux-64=2.34
py-xgboost=1.0.2
libgomp=9.2.0
ncurses=6.2
libstdcxx-ng=9.2.0
gstreamer=1.14.5
xgboost=1.0.2
binutils_impl_linux-64=2.34
As you mentioned in an earlier comment, I deleted these from the linux file and tried again to create the conda environment but it appeared to result in way too many conflicts. When do you expect to have a tested windows .yml file (you mentioned this was something you were looking into) or should I just proceed with the docker installation approach?

Thanks for your help - I'm looking forward to working through the book!

**Comment by stefan-jansen** [comment]
You can remove the version numbers after removing the offending files and should get get it installed (except for the zipline environment which is more complicated). However, the docker images are specifically designed for windows users who want a painless setup so I would recommend sticking with those.

**Comment by antkealy** [comment]
Thanks for the prompt response. So I am clear, I would remove the above packages I highlighted in my first comment from the linux.yml file and then remove the version numbers on the remaining packages effectively installing all the latest versions? Regarding Zipline, I actually already have a conda environment setup that works - same issues with version Zipline 1.3 encountered with "Trading Evolved" - so I was initially hoping I could just use that! 

As you mention though, maybe I will just use the docker image - I haven't used it before so was laziness on my part to get that up and running. Painless setup sounds good though.

**Comment by antkealy** [comment]
Hi Stefan, If you could clarify the below that would be great? 
"So I am clear, I would remove the above packages I highlighted in my first comment from the linux.yml file and then remove the version numbers on the remaining packages effectively installing all the latest versions?"

I believe docker needs windows 10 pro installed so have tried but failed to upgrade. I only have windows home single language which doesn't appear to be able to upgrade to pro without a custom install that will remove all 3rd party apps - I don't want to go down this route given the time involved in restoring everything so ideally I will be sticking with the conda environments option for now.

**Comment by stefan-jansen** [comment]
My understanding is that Windows Home now permits Docker installation according to [this](https://docs.docker.com/docker-for-windows/install-windows-home/) installation guide - could you please check if this would work for you?

**Comment by antkealy** [comment]
Thanks Stefan, will take a look at that

**Comment by stefan-jansen** [comment]
I've updated the installation instructions for Windows Docker install and other aspects. Docker works fine with Windows 10 Home.

**Comment by antkealy** [comment]
Thanks Stefan
