### ISSUE TITLE
Open Table Spyder MAC IOS problem

### ISSUE THREAD

**Issue by stylesaler** [stefan-jansen/machine-learning-for-trading#43]
Good morning,
I'm trying to run the spyder files about open table folders, I have a mac with Catalina and I have a problem with geckodriver, it seems there is a bug 
https://firefox-source-docs.mozilla.org/testing/geckodriver/Notarization.html
https://github.com/mozilla/geckodriver/issues/1629

I have installed geckodrive with homebrew but it doesn't work anyway
I receive this spyder console error: WebDriverException: 'geckodriver' executable needs to be in PATH. 

Please help me to resolve this issue
Ty Ale

**Comment by stefan-jansen** [comment]
Please see suggested [solution](https://stackoverflow.com/questions/40208051/selenium-using-python-geckodriver-executable-needs-to-be-in-path) on stackoverflow.
