### ISSUE TITLE
Create_stooq_data.ipynb error storing data

### ISSUE THREAD

**Issue by cheenweekiang** [stefan-jansen/machine-learning-for-trading#44]
I was running create_stooq_data.ipynb

# load some Japanese and all US assets for 2000-2019
markets = {'jp': ['tse stocks'],
           'us': ['nasdaq etfs', 'nasdaq stocks', 'nyse etfs', 'nyse stocks', 'nysemkt stocks']
          }
frequency = 'daily'

idx = pd.IndexSlice
for market, asset_classes in markets.items():
    for asset_class in asset_classes:
        print(f'\n{asset_class}')
        prices, tickers = get_stooq_prices_and_tickers(frequency=frequency,market=market,asset_class=asset_class)
        
        prices = prices.sort_index().loc[idx[:, '2000': '2019'], :]
        names = prices.index.names
        prices = (prices
                  .reset_index()
                  .drop_duplicates()
                  .set_index(names)
                  .sort_index())
        
        print('\nNo. of observations per asset')
        print(prices.groupby('ticker').size().describe())
        key = f'stooq/{market}/{asset_class.replace(" ", "/")}/'
        
        print(prices.info(null_counts=True))
        
        prices.to_hdf(DATA_STORE, key + 'prices', format='t')
        
        print(tickers.info())
        tickers.to_hdf(DATA_STORE, key + 'tickers', format='t')

got this error.

tse stocks
stooq/data/daily/jp/tse stocks
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-28-e5d8e787c42d> in <module>
      9     for asset_class in asset_classes:
     10         print(f'\n{asset_class}')
---> 11         prices, tickers = get_stooq_prices_and_tickers(frequency=frequency,market=market,asset_class=asset_class)
     12 
     13         prices = prices.sort_index().loc[idx[:, '2000': '2019'], :]

<ipython-input-12-a0105fe8d4bc> in get_stooq_prices_and_tickers(frequency, market, asset_class)
     38                 file.unlink()
     39 
---> 40     prices = (pd.concat(prices, ignore_index=True)
     41               .rename(columns=str.lower)
     42               .set_index(['ticker', date_label])

/opt/conda/envs/ml4t/lib/python3.7/site-packages/pandas/core/reshape/concat.py in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    279         verify_integrity=verify_integrity,
    280         copy=copy,
--> 281         sort=sort,
    282     )
    283 

/opt/conda/envs/ml4t/lib/python3.7/site-packages/pandas/core/reshape/concat.py in __init__(self, objs, axis, join, keys, levels, names, ignore_index, verify_integrity, copy, sort)
    327 
    328         if len(objs) == 0:
--> 329             raise ValueError("No objects to concatenate")
    330 
    331         if keys is None:

ValueError: No objects to concatenate

Any help is appreciated.

**Comment by stefan-jansen** [comment]
This looks like you did not first download the price data for Japan. The example only downloads the US data, you would have to rerun cells 5-9 using `'jp'` instead of `'us'`. I've updated the code so you do not have to modify this yourself.
