### ISSUE TITLE
--> 145     return registry.make(id, **kwargs)

### ISSUE THREAD

**Issue by cody-vandervoort** [stefan-jansen/machine-learning-for-trading#45]
Hi i was wondering if you could point me in the right direction im getting this error, I thought it might have been something to do with loading quandl data but It seemed fine when I loaded in another notebook, I thought I had it all working then my computer went to sleep over night and it would not work anymore, I am in the ml4t-dl conda environment using docker, inside of jupyter lab, i had to first reinstall the tensorflow estimator last night from an error it was throwing then this was the next, I can't get past it, my quandl api key works well with other notebooks reloading, I thought you may be more familiar with this code than I am, thank you kindly

```
`INFO:trading_env:trading_env` logger started.
INFO:trading_env:loading data for AAPL...
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-10-f07228b2136b> in <module>
----> 1 trading_environment = gym.make('trading-v0')
      2 trading_environment.env.trading_days = trading_days
      3 trading_environment.env.trading_cost_bps = 1e-3
      4 trading_environment.env.time_cost_bps = 1e-4
      5 trading_environment.env.ticker = 'AAPL'

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/gym/envs/registration.py in make(id, **kwargs)
    143 
    144 def make(id, **kwargs):
--> 145     return registry.make(id, **kwargs)
    146 
    147 def spec(id):

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/gym/envs/registration.py in make(self, path, **kwargs)
     88             logger.info('Making new env: %s', path)
     89         spec = self.spec(path)
---> 90         env = spec.make(**kwargs)
     91         # We used to have people override _reset/_step rather than
     92         # reset/step. Set _gym_disable_underscore_compat = True on

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/gym/envs/registration.py in make(self, **kwargs)
     58         else:
     59             cls = load(self.entry_point)
---> 60             env = cls(**_kwargs)
     61 
     62         # Make the environment aware of which spec it came from.

~/ml4t/22_deep_reinforcement_learning/trading_env.py in __init__(self, trading_days, trading_cost_bps, time_cost_bps, ticker)
    234         self.time_cost_bps = time_cost_bps
    235         self.data_source = DataSource(trading_days=self.trading_days,
--> 236                                       ticker=ticker)
    237         self.simulator = TradingSimulator(steps=self.trading_days,
    238                                           trading_cost_bps=self.trading_cost_bps,

~/ml4t/22_deep_reinforcement_learning/trading_env.py in __init__(self, trading_days, ticker, normalize)
     62         self.trading_days = trading_days
     63         self.normalize = normalize
---> 64         self.data = self.load_data()
     65         self.preprocess_data()
     66         self.min_values = self.data.min()

~/ml4t/22_deep_reinforcement_learning/trading_env.py in load_data(self)
     73         idx = pd.IndexSlice
     74         with pd.HDFStore('../data/assets.h5') as store:
---> 75             df = (store['quandl/wiki/prices']
     76                   .loc[idx[:, self.ticker],
     77                        ['adj_close', 'adj_volume', 'adj_low', 'adj_high']]

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/pandas/io/pytables.py in __getitem__(self, key)
    551 
    552     def __getitem__(self, key: str):
--> 553         return self.get(key)
    554 
    555     def __setitem__(self, key: str, value):

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/pandas/io/pytables.py in get(self, key)
    744         group = self.get_node(key)
    745         if group is None:
--> 746             raise KeyError(f"No object named {key} in the file")
    747         return self._read_group(group)
    748 

KeyError: 'No object named quandl/wiki/prices in the file'
```

**Comment by stefan-jansen** [comment]
The `KeyError: 'No object named quandl/wiki/prices in the file'` implies that either the path to the `HDFStore` is wrong, or the key you are requesting does not exist in there.

In line 74, the backtrace indicates the HDFStore location: 
```
       74         with pd.HDFStore('../data/assets.h5') as store:
---> 75             df = (store['quandl/wiki/prices']
```
Either the path is wrong (perhaps you've created the `assets.h5` file in different location?) or you need to first run the code in the `data` folder to create the `quandl/wiki/prices` object as described there.

**Comment by cody-vandervoort** [comment]
Awesome thanks for the swift reply once again, I will check out the data folder!

**Comment by cody-vandervoort** [comment]
Hi, when I try to load the wiki prices csv I am getting this error about the date, but as you can see when i read the csv the dates are there correcly on the csv could you please once again point me in the right direction for loading the data properly, I uploaded it to the data directory in jupyter notebooks its under data/wiki_prices.csv `

  | CIDM | 2009-11-20 | 1.3202 | 1.34 | 1.26 | 1.34.1 | 7200.0 | 0.0 | 1.0 | 13.202 | 13.4 | 12.6 | 13.4.1 | 720.0
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
CIDM | 2009-11-23 | 1.25 | 1.50 | 1.2500 | 1.5000 | 70800.0 | 0.0 | 1.0 | 12.50 | 15.00 | 12.5000 | 15.000 | 7080.0
CIDM | 2009-11-24 | 1.51 | 1.51 | 1.4000 | 1.4201 | 19600.0 | 0.0 | 1.0 | 15.10 | 15.10 | 14.0000 | 14.201 | 1960.0
CIDM | 2009-11-25 | 1.48 | 1.50 | 1.4300 | 1.4800 | 4400.0 | 0.0 | 1.0 | 14.80 | 15.00 | 14.3000 | 14.800 | 440.0
CIDM | 2009-11-27 | 1.48 | 1.50 | 1.4800 | 1.4831 | 3900.0 | 0.0 | 1.0 | 14.80 | 15.00 | 14.8000 | 14.831 | 390.0
CIDM | 2009-11-30 | 1.44 | 1.45 | 1.4000 | 1.4000 | 19000.0 | 0.0 | 1.0 | 14.40 | 14.50 | 14.0000 | 14.000 | 1900.0
... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ... | ...
ZUMZ | 2018-03-21 | 23.80 | 24.60 | 23.6058 | 23.9500 | 354092.0 | 0.0 | 1.0 | 23.80 | 24.60 | 23.6058 | 23.950 | 354092.0
ZUMZ | 2018-03-22 | 23.90 | 24.35 | 23.3000 | 23.3500 | 269607.0 | 0.0 | 1.0 | 23.90 | 24.35 | 23.3000 | 23.350 | 269607.0
ZUMZ | 2018-03-23 | 23.55 | 24.20 | 23.4500 | 23.5500 | 301584.0 | 0.0 | 1.0 | 23.55 | 24.20 | 23.4500 | 23.550 | 301584.0
ZUMZ | 2018-03-26 | 23.75 | 24.80 | 23.7000 | 24.6500 | 375320.0 | 0.0 | 1.0 | 23.75 | 24.80 | 23.7000 | 24.650 | 375320.0
ZUMZ | 2018-03-27 | 24.65 | 24.65 | 23.3500 | 23.6000 | 403884.0 | 0.0 | 1.0 | 24.65 | 24.65 | 23.3500 | 23.600 | 403884.0

``---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-7ad14f8565c0> in <module>
      2                  parse_dates=['date'],
      3                  index_col=['date', 'ticker'],
----> 4                  infer_datetime_format=True)
      5      .sort_index())
      6 

/opt/conda/envs/ml4t/lib/python3.7/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
    674         )
    675 
--> 676         return _read(filepath_or_buffer, kwds)
    677 
    678     parser_f.__name__ = name

/opt/conda/envs/ml4t/lib/python3.7/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    446 
    447     # Create the parser.
--> 448     parser = TextFileReader(fp_or_buf, **kwds)
    449 
    450     if chunksize or iterator:

/opt/conda/envs/ml4t/lib/python3.7/site-packages/pandas/io/parsers.py in __init__(self, f, engine, **kwds)
    878             self.options["has_index_names"] = kwds["has_index_names"]
    879 
--> 880         self._make_engine(self.engine)
    881 
    882     def close(self):

/opt/conda/envs/ml4t/lib/python3.7/site-packages/pandas/io/parsers.py in _make_engine(self, engine)
   1112     def _make_engine(self, engine="c"):
   1113         if engine == "c":
-> 1114             self._engine = CParserWrapper(self.f, **self.options)
   1115         else:
   1116             if engine == "python":

/opt/conda/envs/ml4t/lib/python3.7/site-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   1947                 _validate_usecols_names(usecols, self.names)
   1948 
-> 1949         self._set_noconvert_columns()
   1950 
   1951         self.orig_names = self.names

/opt/conda/envs/ml4t/lib/python3.7/site-packages/pandas/io/parsers.py in _set_noconvert_columns(self)
   2013                         _set(k)
   2014                 else:
-> 2015                     _set(val)
   2016 
   2017         elif isinstance(self.parse_dates, dict):

/opt/conda/envs/ml4t/lib/python3.7/site-packages/pandas/io/parsers.py in _set(x)
   2003 
   2004             if not is_integer(x):
-> 2005                 x = names.index(x)
   2006 
   2007             self._reader.set_noconvert(x)

ValueError: 'date' is not in list`

**Comment by stefan-jansen** [comment]
The first line of the file does not seem to have headers. Not sure why, but there should be column names. This is why pandas complains the expected column names do not exist. Something must have happened to the file after download, please double check the original Quandl data.
