### ISSUE TITLE
Train Agent - TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

### ISSUE THREAD

**Issue by cody-vandervoort** [stefan-jansen/machine-learning-for-trading#47]
Hi, I managed to get the data to redownload correctly but i've run into this syntax error moving forward on the block of code under the "train agent" section I receive this error:

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-40-8975ae38bea2> in <module>
     13                                  0.0 if done else 1.0)
     14         if ddqn.train:
---> 15             ddqn.experience_replay()
     16         if done:
     17             break

<ipython-input-17-a9539b52dba1> in experience_replay(self)
    107 
    108         q_values = self.online_network.predict_on_batch(states)
--> 109         q_values[[self.idx, actions]] = targets
    110 
    111         loss = self.online_network.train_on_batch(x=states, y=q_values)

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment`

I appreciate you're guidance greatly, thanks again.

**Comment by cody-vandervoort** [comment]
running it again im able to get a single line before i get the error i've done this several times with the same result.
10 | 00:00:02 | Agent: -39.1% (-39.1%) | Market:   4.6% (  4.6%) | Wins: 20.0% | eps:  0.960

**Comment by stefan-jansen** [comment]
Which environment and TF version are you using?

**Comment by cody-vandervoort** [comment]
I’m using the ml4t-dl environment, I will check which TF version I’m using
which one is it that I need

**Comment by cody-vandervoort** [comment]
I Think I may have updated tensorflow at one point I remember getting an
error for the tf.estimator and reinstalled

**Comment by cody-vandervoort** [comment]
The version is 2.1

**Comment by stefan-jansen** [comment]
This actually needs TensorFlow 2.2, which conda does not yet support for CPU (but for GPU apparently, which I used to test this code. It looks like the following fixes it:
```
conda remove tensorflow tensorflow-estimator -n ml4t-dl
pip install -U tensorflow numpy
```
Please let me know if this doesn't work for you; I'll update the (installation) instructions accordingly.

**Comment by cody-vandervoort** [comment]
I was able to get the agent to train with the updated tensorflow numpy, but
after the agent trained which took 3 hours I couldn’t get it to save the
results I wanted an extra couple hours nothing happened I guess I’ll just
have to get gpu I was thinking I might try outside of docker to gain access
to the ram from my entire system.
