### ISSUE TITLE
ISSUE WITH 

### ISSUE THREAD

**Issue by ashraf-01** [stefan-jansen/machine-learning-for-trading#48]
20_autoencoders_for_conditional_risk_factors/06_conditional_autoencoder_for_asset_pricing_model.ipynb

HI STEFAN , I WANT TO THANK YOU FIRST FOR THE NICE WEBINAR FEW DAYS BACK AIRED ON YOUTUBE ,HOWVEVER I RAN ON TO THE BELOW ERROR (LIST INDEX OUT OF THE RANGE ) AND HERE ARE SOME SCREENSHOTS 
![Screenshot from 2020-10-13 22-36-51](https://user-images.githubusercontent.com/50061659/95914413-f79da200-0da5-11eb-8444-40462101044e.png)
![Screenshot from 2020-10-13 22-36-24](https://user-images.githubusercontent.com/50061659/95914440-ff5d4680-0da5-11eb-93c9-dcab6ed7f76b.png)
YOU WILL NOTICE THAT IN THE SECOND SCREEN SHOT THAT THE ERROR IS COMING FROM THE LINES OR DATES WHICH ONE OF THEM IS OUT OF LINE WITH THE OTHER BETWEEN TRAINING AND TESTING 
YOUR INPUT IS HIGHLY APPRECIATED 
BEST REGARDS

**Comment by stefan-jansen** [comment]
Please check your settings for `train_period_length`,, `test_period_length`, and `n_splits`. They need to be consistent with the amount of data you have. The error indicates that you do not have enough observations for your desired cross-validation configuration.

Also, please note [this](https://www.lifewire.com/why-not-to-write-in-all-caps-1173242) regarding comments in all caps.

**Comment by ashraf-01** [comment]
so I don't have to make changes to actually theses lines codes which are part of utils,py , right ? it is only the train period length and , test perrido legnth , n_splits  , I need to look in to that again thanks stefan

**Comment by stefan-jansen** [comment]
that's correct, these settings determine how many observations `MultipleTimeSeriesCV` will try to select for training/testing. If there's not enough data, it will through the error you saw. Btw, which webinar are you referring to?
