### ISSUE TITLE
get_data.py script missing in repo?

### ISSUE THREAD

**Issue by ahotrod** [stefan-jansen/machine-learning-for-trading#5]
At location 2646 "_Useful pandas and NumPy methods_" in the book it states "_The notebook uses data generated by the **get_data.py** script in the data folder in the root directory of the GitHub repo and stored in HDF5 format for faster access_".

Can't find the **get_data.py** script in this repo, missing?  Assume it generates the **access.h5** file used in many of the other chapters' notebooks.

**Comment by stefan-jansen** [comment]
It's now available in the `data` folder.
