### ISSUE TITLE
LDA model converges poorly due to bad hyperparameters

### ISSUE THREAD

**Issue by chrisfalter** [stefan-jansen/machine-learning-for-trading#50]
In the notebook [lda_with_sklearn](https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/15_topic_modeling/04_lda_with_sklearn.ipynb), the LDA model predicts only 3 topics for documents in 5 classes. 

By performing hyperparameter optimization with `sklearn.model_selection.GridSearchCV`, I was able to determine the following:
* Root cause is badly chosen `min_df` and `max_df` parameters to the `TfidfVectorizer` instance.
* Setting `max_df = 0.11` and `min_df = 0.026` produces excellent results.

My code and analysis are in my public Github repo [here](https://github.com/chrisfalter/DataScience/blob/master/NLP/lda_with_sklearn.ipynb). You have my permission to use my code and analysis; I would only request the courtesy of being credited for any contribution I make toward your final product. (Thanks!)

**Comment by stefan-jansen** [comment]
Thank you, more than happy to point out to readers that it's possible to optimize the `TfidfVectorizer` parameters to improve the results for this dataset. In which form would you like to be credited? Would a link to this issue be sufficient?

**Comment by chrisfalter** [comment]
Yes, that would be fine!
