### ISSUE TITLE
could you please share the notebook for pgportfolio

### ISSUE THREAD

**Issue by cody-vandervoort** [stefan-jansen/machine-learning-for-trading#53]
I've been working on deconstructing pgfortfolio which I found you pointed to in the read me in 22. reinforcement learning, i decided to wander off into the packt library and came across a new RL book releases sept 2020 and listened to it with a google chrome extension fairly quickly so it allowed me to gain some high inspiration for trader, where I actually wrote out my first hypothesis which was that reinforcement learning will allow me to learn the strategy which the agent uses so I could at least implement this for my own strategy and stop loosing money, as oct 1st i wasted away the last of my october funds on poor signals which gave me ultra motivation to commit to my fullest capability. 

Anyways I know its not your code but i was really hoping you might be kind enough to share the code which you used for pgfortfolio to receive the 4 fold returns so i could play with it further and try to deconstruct it into my own system, it would really help if i could help it working from the start, i've been taking notes from their system for the majority of the week to understand the architecture i only tried to implement the code a couple times, but i have note figured it out yet as of now, 
was really hoping you might be able to help me with a quick consult to get me on the right track so i could see what code you put in what order. so i could then pull up pgfortfolio in a jupyter notebook and disect it,

thanks so much once again

**Comment by stefan-jansen** [comment]
Hi @cody-vandervoort, this looks like a misunderstanding. The reference in the README does actually point to the [PGPortfolio](https://github.com/ZhengyaoJiang/PGPortfolio) repo, you find the link to the paper there. I have not used it myself but will update the README.
