### ISSUE TITLE
docker install in GCP

### ISSUE THREAD

**Issue by rydeen7** [stefan-jansen/machine-learning-for-trading#55]
Hi,
I'm trying to setup environment in GCP and AWS because my laptop power is small.
I succeeded in docker run.
But when it comes to 'zipline ingest', I can do on AWS, while in GCP there are error statement as below. .

`PermissionError: [Errno 13] Permission denied: '/home/packt/ml4t/data/.zipline'`

Do I have any solution?

KR

**Comment by stefan-jansen** [comment]
The Docker user needs permissions to write to the directory. In some environments you need to specifically set these permissions. Please check how you can verify permissions on GCP and alter them accordingly.

**Comment by RodionKovalenko** [comment]
command  <sudo env "PATH=/home/packt/ml4t/data" conda update conda> asks me for a user password in packt. But I do not know it.

**Comment by stefan-jansen** [comment]
You should be able to update using `conda update -n base conda`, or using a different environment like so: `conda update -n ml4t conda`. Please just keep in mind that updating environment packages may break code somewhere.

**Comment by pcyzxcvb** [comment]
Also see the Permission denied error on my Mac. Try to add the user to docker group as below but request for packs password. Any other alternative way to solve the permission problem?

(ml4t-zipline) packt@eab8a1a096cb:/$ cat /etc/group | grep docker
(ml4t-zipline) packt@eab8a1a096cb:/$ sudo groupadd docker
[sudo] password for packt:

**Comment by stefan-jansen** [comment]
Adding the user to the docker group should happen on the host (before `docker run ...` and allows you to run docker commands there without `sudo`. To have `sudo` privileges while running docker, use the `docker exec` command in the second answer [here](https://stackoverflow.com/questions/25845538/how-to-use-sudo-inside-a-docker-container).

**Comment by niklasb1609** [comment]
Hey @stefan-jansen ,
I still have this error. Doesn't matter if I try it on Mac OS or Windows. I really want to start coding.
I'm not very familiar with the Mac/Windows Shell. How can I give my normal user permissions? When I try it with 
```
docker exec -u root -t -i container_id /bin/bash
```
I can ingest, but when I start the notebook it is empty. Really annoying at the moment :(

**Comment by stefan-jansen** [comment]
If you are doing this on your local machine (as you should), you also need to mount the volume (the `-v ` portion of the command) so you can acccess the directory with the notebooks in docker - if you run `ls` inside docker, you should see the repo directories). To make this work, you should also run this from the root directory of the repo.  

Just throwing out some issues that could explain why it's not working - anything sounds relevant?

**Comment by niklasb1609** [comment]
@stefan-jansen where should I put the -v? In this command? docker exec -u root -t -i container_id /bin/bash

**Comment by stefan-jansen** [comment]
`docker exec` is for executing a command in an [already running container](https://docs.docker.com/engine/reference/commandline/exec/). When you first run the container, you should run the command as provided in the installation instructions from the root directory:
```
docker run -it -v $(pwd):/home/packt/ml4t -p 8888:8888 -e QUANDL_API_KEY=<your API key> --name ml4t appliedai/packt:latest bash
```
`pwd` here stands for `present working directory`; you can also use the absolute path instead. The goal of `-v` here is to mount the current working directory at `/home/packt/ml4t` inside the docker container. In other words, if you change into this directory using `cd /home/packt/ml4t`, you should see the content of your working directory inside docker; if you then run `jupyter notebook` you can just browse its content. 

If you do this in google collab and your repo is on google drive, for instance, this would change; it would be easier to install the software using `pip` instead than using docker.

**Comment by niklasb1609** [comment]
Hey @stefan-jansen,
thanks to your help I got a better understanding of the docker container. My problem was that I replaced the $(pwd):/home/packt/ml4t with $(pwd):/absolutepath because I thought I had to do so. Now it seems logical. Thanks for you help! I look forward to begin with the coding.

**Comment by stefan-jansen** [comment]
Glad to hear! I'll see if I can update the instructions to make this part clearer.
