### ISSUE TITLE
algoseek data

### ISSUE THREAD

**Issue by sabirjana** [stefan-jansen/machine-learning-for-trading#56]
Hi Stefan,
Any update regarding how to process of algoseek data? I just checked algoseek website and found the option to download the data used in your book.
Thanks
Sabir Jana

**Comment by stefan-jansen** [comment]
Thank you, sorry but very busy right now, will update next week.

**Comment by mundus08** [comment]
Hi Sabir,
can you give me a hint how to download the data from the algoseek website?
Thanks
Michael

**Comment by stefan-jansen** [comment]
Apologies for the delay - the NASDAQ 100 trade and quote minute bar data for 2015-17 are now available [here](https://www.algoseek.com/ml4t-book-data.html). I've updated the instructions in Chapter 2 and the intraday strategy example in Chapter 12 accordingly.
