### ISSUE TITLE
Zipline run_algorithm() modification

### ISSUE THREAD

**Issue by BegelAdr** [stefan-jansen/machine-learning-for-trading#57]
Hi, 

I'm trying to modify the run_algorithm function on zipline to allow custom_loader but I have no idea how do deal with it.

The function: (17_deep_learning/05_backtesting_with_zipline.ipynb)
```
results = run_algorithm(start=start_date,
                        end=end_date,
                        initialize=initialize,
                        before_trading_start=before_trading_start,
                        capital_base=1e5,
                        data_frequency='daily',
                        bundle='quandl',
                        custom_loader=signal_loader)  # need to modify zipline_
``` 
Do you know how to properly modify the function?

Thank you very much!

BegelAdr

**Comment by stefan-jansen** [comment]
The patched `zipline` version included in the Docker images contains the modification for the `custom_loader` to work. See code [here](https://github.com/stefan-jansen/zipline).
