### ISSUE TITLE
11_decison_trees_random forests: 00_data_prep

### ISSUE THREAD

**Issue by jfreeze3** [stefan-jansen/machine-learning-for-trading#58]
The code fails at line 34: prices = prices.unstack('ticker')
ValueError: Index contains duplicate entries, cannot reshape

Please advise, thank you.

**Comment by stefan-jansen** [comment]
Your index contains duplicate entries. You could do 

```
idx = ['ticker', 'date']
prices = prices.reset_index().drop_duplicates(idx).set_index(idx)
```
.

**Comment by jfreeze3** [comment]
Thank you!
