### ISSUE TITLE
Link to notebook ml4t_quantopian doesn't work

### ISSUE THREAD

**Issue by ntrang086** [stefan-jansen/machine-learning-for-trading#60]
The link to the  ml4t_quantopian in the following ReadMe document doesn't work:
![image](https://user-images.githubusercontent.com/14242380/98579841-1b60e480-228d-11eb-9551-e954e91facc9.png)

https://github.com/stefan-jansen/machine-learning-for-trading/tree/master/08_ml4t_workflow/04_ml4t_workflow_with_zipline

**Comment by stefan-jansen** [comment]
Thanks, fixed.
