### ISSUE TITLE
Cell in storage_benchmark notebook causes kernel to crash

### ISSUE THREAD

**Issue by sgjohnson1981** [stefan-jansen/machine-learning-for-trading#64]
The cell below:

    %%timeit -o
    df = pd.read_parquet(parquet_file)

**Comment by stefan-jansen** [comment]
Please reduce the size of the test data; it takes up 1.5GB of RAM on my machine (with 64GM RAM) buy may hit resource limits elsewhere. To accomplish this, just modify the call to `generate_test_data` which has the following default argument values:
```
generate_test_data(nrows=100000, numerical_cols=2000, text_cols=0, text_length=10)
```

**Comment by sgjohnson1981** [comment]
I already did that. I adjusted both arguments down to 100 each. The cell with the function call works fine. It ends up using ~152MB for which I have plenty of memory. It's the timeit cell that crashes the kernel.

**Comment by stefan-jansen** [comment]
I'm sorry but I can't reproduce this on my machine, see attached.

![Screenshot from 2020-12-02 21-10-39](https://user-images.githubusercontent.com/4275885/100959040-70d68d00-34eb-11eb-92d9-6468fca361d9.png)

**Comment by stefan-jansen** [comment]
One reason might be that if you are running this in a Docker, container, your VM resource allocation may hit a limit earlier than your overall RAM.

**Comment by sgjohnson1981** [comment]
I wasn't using Docker, but now that I'm trying to follow the instructions to use it (maybe there's a missing dependency Jupyter on windows is failing to report?), something seems amiss with the instructions. I don't see a Docker image anywhere in the repo. I have no prior experience with Docker. Is the Docker command in the README supposed to pull an image? Is the /home/packt/m4lt directory just a default name for the cloned directory on a Linux machine? I changed it to the directory on my windows 10 machine. I keep getting a "The system cannot find the file specified" error.

**Comment by stefan-jansen** [comment]
Please let me know where you find the instructions missing specific yet critical steps. 

Regarding the difficulties you are encountering, the [instructions](https://github.com/stefan-jansen/machine-learning-for-trading/tree/master/installation) state:

>With a single Docker command, we can accomplish several things at once (see the Getting Started guides linked above for more detail):
> - only on the first run: pull the Docker image from the Docker Hub account appliedai and the repository packt with the tag `latest`

In other words: the Docker command is indeed going to pull the image.

Regarding the directory, two bullets below, it says
> - mount the current directory containing the starter project files as a volume in the directory /home/packt/ml4t inside the container

This means that the path `/home/packt/ml4t` exists inside the container (which runs Linux, as also mentioned in the instructions) and does not refer to 'the cloned directory on a Linux machine'. So you should not change it. For windows, you need to provide the path to the directory on your machine. To this end, you should modify the sample path `C:/Users/stefan/Documents/machine-learning-for-trading` provided in the README:
```
docker run -it -v C:/Users/stefan/Documents/machine-learning-for-trading:/home/packt/ml4t -p 8888:8888 -e QUANDL_API_KEY=<your API key> --name ml4t appliedai/packt:latest bash
```
I sincerely hope this helps and strongly recommend reading through the (not too long) Docker 'Getting Started' guide linked in the instructions. It's a very useful and increasingly common technology worthy of becoming familiar with; I was hoping readers would consider this a small side benefit.

If you find  additional shortcomings in the instructions, please open a new issue.

**Comment by sgjohnson1981** [comment]
Could not get past the file not found error. Not sure what was going on. I tried creating a container without all the options with

    docker run alliedai/packt

but got an error about it being inaccessible without logging in. I was logged in to the Docker Desktop so not sure what that meant. I gave up. Sorry, but Docker doesn't seem worth it to me. Just pulling the image from the server and extracting it caused some Vmmem process on Windows 10 to gobble up all my memory. Not sure if Docker has any effect on Hyper-V. Seems Hyper-V doesn't play well with other virtualization software on the latest update of Windows 10. Maybe that was causing issues. Unlike Hyper-V and Docker, I do know VirtualBox and Debian well, so I just used the yml file to create a conda environment. After that everything seemed to work in the notebook until the next to last cell. Got a FileNotFound error for Mixed.csv. Can't figure out from the code where that file should have been created.

**Comment by stefan-jansen** [comment]
Assuming this is a typo, but the Dockerhub repo is under `appliedai`, not `alliedai`. You can't pull from a private repo without logging in. 

The `Mixed.csv` file results from a second run that uses text data as well; see p 57/58 in the 2nd edition.

**Comment by sgjohnson1981** [comment]
Yes, that was typo.

"...second run..."? As in, it has to make it through a first run? Don't see how that works. I looked at those pages. It says nothing about creating a Mixed.csv file. Those pages refer to the notebook in question, which I already tried to run.

**Comment by stefan-jansen** [comment]
You are right, the book does not explicitly say how to create that specific file. However, it does say the following:
> The `storage_benchmark.ipynb` notebook compares the performance of the preceding libraries using a test DataFrame that can be configured to contain numerical or text data, or both. For the HDF5 library, we test both the fixed and table formats. The table format allows for queries and can be appended to.
> The following charts illustrate the read and write performance for 100,000 rows with either **1,000 columns of random floats and 1,000 columns of a random 10-character string**, or just **2,000 float columns** (on a log scale).
> The left panel shows that, for purely numerical data, the HDF5 format performs best by far, and the table format also shares with CSV the smallest memory footprint at 1.6 GB. The fixed format uses twice as much space, while the parquet format uses 2 GB.
> For a **mix of numerical and text data**, Parquet is the best choice for read and write operations. HDF5 has an advantage with read in relation to CSV, but it is slower with write because it pickles text data.

I was hoping that mentioning how data could be created containing a mix of numeric and text data would allow an interested reader to recreate the comparison of running times and memory requirements of the different storage methods. Unfortunately, the notebook does indeed contain a reference to a file that was not created during that run and I am sorry if the lack of explicit instructions here created frustration.

Please let me know if I can do anything else to help you execute the code you are trying to run.
