### ISSUE TITLE
Chapter 4 - Issue with assets.h5 file

### ISSUE THREAD

**Issue by LuisNoName** [stefan-jansen/machine-learning-for-trading#67]
Hi Stefan, I have just recently started going trough your book and have run into an issue in Chapter 4 that is a little bit beyond me. 
I have run the create_datasets notebook and then started running the 01_feature engineering notebook. However, when i run the following:

with pd.HDFStore(DATA_STORE) as store:
    prices = (store['quandl/wiki/prices']
              .loc[idx[str(START):str(END), :], 'adj_close']
              .unstack('ticker'))
    stocks = store['us_equities/stocks'].loc[:, ['marketcap', 'ipoyear', 'sector']]

i get an error saying :

KeyError: 'No object named us_equities/stocks in the file'

(in the data directory, the file assets.h5 has been created and its 1.54GB large, so i think that step went good.)
I am not quite sure what the problem is and would appreciate if you could help me resolve it :)
Thank you in advance!

**Comment by rightx2** [comment]
How did you solve it? I'm faced with the same problem..

**Comment by stefan-jansen** [comment]
See the instructions [here](https://render.githubusercontent.com/view/ipynb?color_mode=dark&commit=93f98d99728c57b15a6a3d9fd60f8adb51d7df58&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f73746566616e2d6a616e73656e2f6d616368696e652d6c6561726e696e672d666f722d74726164696e672f393366393864393937323863353762313561366133643966643630663861646235316437646635382f646174612f6372656174655f64617461736574732e6970796e62&nwo=stefan-jansen%2Fmachine-learning-for-trading&path=data%2Fcreate_datasets.ipynb&repository_id=132754148&repository_type=Repository#Wiki-Prices-Metadata) - load the file `wiki_stocks.csv` and store in `assets.h5` as in cell [5].

**Comment by 1JarekNowak** [comment]
Hi, I have a problem downloading data as described in the file 'create_datasets.ipynb', in the 'Wiki prices metadata' section. I can only download single records and when trying to download the entire database, I receive permission error. 
As Quandl is no longer available I'm trying to download from links: "https://data.nasdaq.com/api/v3/databases/SCF/data?download_type=full&api_key=YOURAPIKEY"
or
"https://data.nasdaq.com/api/v3/databases/SCF/data?download_type=partial&api_key=YOURAPIKEY"

Is there any other source with a .csv file that I could import for further analysis?

**Comment by stefan-jansen** [comment]
Are you replacing `YOURAPIKEY` with the actual value of your API key (see 'my account' or the like)?

**Comment by 1JarekNowak** [comment]
Yes, of course.
