### ISSUE TITLE
ml4t-zipline installation link broken

### ISSUE THREAD

**Issue by mariamadalina** [stefan-jansen/machine-learning-for-trading#70]
Using Zipline
This notebook uses the conda environment ml4t-zipline.

Please follow the instructions provided here [https://github.com/stefan-jansen/machine-learning-for-trading/blob/installation/](https://github.com/stefan-jansen/machine-learning-for-trading/blob/installation/)
The link is not working anymore

**Comment by stefan-jansen** [comment]
Thank you. Could you please let me know where to find this link? Meanwhile, this [link](https://github.com/stefan-jansen/machine-learning-for-trading/tree/master/installation) works, it's "https://github.com/stefan-jansen/machine-learning-for-trading/tree/master/installation".

**Comment by stefan-jansen** [comment]
Text search doesn't yield a match in this repo; happy to update the link if you point out the location or accept a pull request. Closing for now.
