### ISSUE TITLE
Massive error log trying to create ml4t-zipline env

### ISSUE THREAD

**Issue by sgjohnson1981** [stefan-jansen/machine-learning-for-trading#72]
Using the yml file on Debian, I get this error log. Looks like bcolz isn't installing correctly. The git repository clone errored as well.
[error.txt](https://github.com/stefan-jansen/machine-learning-for-trading/files/5680979/error.txt)

**Comment by stefan-jansen** [comment]
Unfortunately, installing the `Zipline` dependencies is not straightforward and requires some research or review of the docs for the respective libraries. Hence the Docker images.
