### ISSUE TITLE
Mistake in performance_eval_alphalens notebook

### ISSUE THREAD

**Issue by sgjohnson1981** [stefan-jansen/machine-learning-for-trading#73]
The eighth or so input field contains a sentence repeated in another text block below, rather than code. Looks like it should just be deleted. This sentence:

    We can create the alphalens input data in the required format using the `get_clean_factor_and_forward_returns` utility function that also returns the signal quartiles and the forward returns for the given holding periods:

**Comment by stefan-jansen** [comment]
I can't find the text in this repo using text search - which notebook are you referring to? Feel free to send a pull request as well.

**Comment by sgjohnson1981** [comment]
https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/04_alpha_factor_research/06_performance_eval_alphalens.ipynb
