### ISSUE TITLE
Multivariate RNN

### ISSUE THREAD

**Issue by jfreeze3** [stefan-jansen/machine-learning-for-trading#76]
A big ask on my part but I have spent three months studying your book and would like to stick with how you do things.

Studying your book is much more informative and efficient than piecemeal extracts from various data sources.  Each data source has its own way of doing things.

Can you provide example code of a rnn with multiple features being fed into model to predict one target, for one or more timesteps ahead, please?  Particularly interested in the data preprocessing and getting into correct format for keras.

Thank you for considering.

**Comment by stefan-jansen** [comment]
Hi @jfreeze3, thank you for you interest in the book, I hope you are finding it useful!

Chapter 19 on RNN has two notebooks, one on [univariate](https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/19_recurrent_neural_nets/01_univariate_time_series_regression.ipynb) and another on [multivariate](https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/19_recurrent_neural_nets/04_multivariate_timeseries.ipynb) time series. 

These should illustrate much of what you are looking for? To predict multiple steps, you can either shift the outcome accordingly (say 7 days to predict T+7) or feed the predicted values back into the RNN if you want to use several 1-day ahead forecasts.

**Comment by stefan-jansen** [comment]
Feel free to reopen if you have any additional questions.
