### ISSUE TITLE
issue on https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/05_strategy_evaluation/01_backtest_with_trades.ipynb

### ISSUE THREAD

**Issue by luisvelo** [stefan-jansen/machine-learning-for-trading#77]
Hi Stefan

https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/05_strategy_evaluation/01_backtest_with_trades.ipynb

gives the below error, is solvable?

[2020-12-17 17:09:50.545236] WARNING: Loader: Still don't have expected treasury data for 'SPY' from 1990-01-02 00:00:00+00:00 to 2020-12-17 00:00:00+00:00 after redownload!
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/data/bundles/core.py in most_recent_data(bundle_name, timestamp, environ)
    474             candidates = os.listdir(
--> 475                 pth.data_path([bundle_name], environ=environ),
    476             )

FileNotFoundError: [Errno 2] No such file or directory: '/home/packt/ml4t/data/.zipline/data/quantopian-quandl'

(Side note: Seems to me also that the docker container for MacOsx you distributed is older than the one you currently use (is not possible to run  --no-benchmark ))

**Comment by luisvelo** [comment]
Stefan

end of the above is

me, timestamp, environ)
    490                 'maybe you need to run: $ zipline ingest -b {bundle}'.format(
    491                     bundle=bundle_name,
--> 492                     timestamp=timestamp,
    493                 ),
    494             )

ValueError: no data for bundle 'quantopian-quandl' on or before 2020-12-17 17:09:50.560635+00:00
maybe you need to run: $ zipline ingest -b quantopian-quandl

NEXT ONE
https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/05_strategy_evaluation/02_backtest_with_pf_optimization.ipynb

gives the below error, probably linked to the issue on the SQLLITE (already there is an issue on that one):
ValueError: Failed to find any assets with country_code 'US' that traded between 2013-01-02 00:00:00+00:00 and 2013-01-09 00:00:00+00:00.
This probably means that your asset db is old or that it has incorrect country/exchange metadata.

**Comment by luisvelo** [comment]
and also, if you have backtests.h5 to post on the data directory maybe the below will run

_https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/05_strategy_evaluation/03_pyfolio_demo.ipynb_

**Comment by stefan-jansen** [comment]
The first item is a warning that you can ignore. 

What do you mean by 'container is older than the one you currently use'? There is only one image on Dockerhub from which you create a container on your host machine. It may not have the latest versions of all libraries, if this is what you are referring to, but ensuring dependencies are availlable and the environment works for the purpose is the main goal of containerizing the setup. The included Zipline version downloads benchmark data from FRED for the last 10 years IIRC.

The NEXT ONE issue is indeed related to the missing country codes; see my response on the related issue.
