### ISSUE TITLE
Chapter 5. a must be greater than 0 error

### ISSUE THREAD

**Issue by silent0506** [stefan-jansen/machine-learning-for-trading#79]
I am practicing the file of the mean_variance_optimization.ipynb.(first edition)

questions1>

`with pd.HDFStore('C://Users//silen//문서(D)//Hands On ML//assets.h5') as store: `
    `sp500_stocks = store['sp500/stocks'].index`
    `prices = store['quandl/wiki/prices'].adj_close.unstack('ticker').filter(sp500_stocks).sample(n=50, axis=1)`

I got an error below

_a must be greater than 0_

how can I fix it?

questions2>

`start = 1988, end = 2017`
` monthly_returns = prices.loc[f'{start}':f'{end}'].resample('M').last().pct_change().dropna(how='all')`
`monthly_returns = monthly_returns.dropna(axis=1)`
`monthly_returns.info()`

I got an error below

  _File "<ipython-input-18-a2510af3cfb1>", line 1
    monthly_returns = prices.loc[f'{start}':f'{end}'].resample('M').last().pct_change().dropna(how='all')
                                          ^
SyntaxError: invalid syntax_

how can I fix it, can you exchange the code `f'{start}':f'{end}'` for old python version(version 3.5)?

**Comment by stefan-jansen** [comment]
This would simply be `str(start):str(end)`.
