### ISSUE TITLE
Regarding the Russian translation

### ISSUE THREAD

**Issue by capissimo** [stefan-jansen/machine-learning-for-trading#8]
Hi, Stefan.

I'm working on a Russian translation of your book for a Saint-Petersburg Publ. and found some omissions in the text of ch 17 on DL (formulas) and ch. 18 on CNN (picture #1) for filters so far.
Can you indicate, where to find the amended versions of the chapters or advise on what to do?

By the way, I found your book very enlightening, an excellent add-on to the Advances in FML by Marcos de Prado.

B.R.,
Andrey Logunov

**Comment by capissimo** [comment]
In the same chaper #18 on CNN picture #2 is misleading, being a copy from chapter #17 on DL.
Where can I get the right pict?

**Comment by stefan-jansen** [comment]
Thank you. That's right, the editor made a few mistakes. The updated version is scheduled to be online by tomorrow. Please be aware that the publisher retains the rights for translations worldwide. Happy to put you in touch with them unless your publisher has already obtained consent.

**Comment by capissimo** [comment]
The publisher already purchased the right.

пн, 29 апр. 2019 г. в 03:55, Stefan Jansen <notifications@github.com>:

**Comment by capissimo** [comment]
Found one more thing. The numbering of the chapters on CNN (19) and on RNN (18) should be swapped in the text.

**Comment by capissimo** [comment]
Oops, in the same chaper #18 on CNN the same thing again - picture #3 is a copy from chapter #17 on DL.

**Comment by stefan-jansen** [comment]
Thank you. Chapters 16-20 have already been reviewed and will be updated tomorrow, so you may want to hold off until then.

**Comment by capissimo** [comment]
OK, Just in case, all pictures 1 thru 5 in chaper on CNN are just copies of those from previous chapter on DL.

**Comment by stefan-jansen** [comment]
I know, there's also a lot of latex that did not render etc. Someone made a
mistake and published the wrong version, will be replaced shortly, sorry
for the inconvenience.

Great you've found it worth translating! Please let me know if you have any
questions on content or code. By the way, who's the publisher and what's
the timeline?

You can also reach me via stefan@applied-ai.com or at
https://www.linkedin.com/in/applied-ai/.

Cheers, Stefan

**Comment by capissimo** [comment]
OK, used your email.
