### ISSUE TITLE
Cannot find train predictions generation in notebook alphalens_signal_quality for chapter 11

### ISSUE THREAD

**Issue by zmarozas** [stefan-jansen/machine-learning-for-trading#80]
Hello,
In chapter 11 notebook 07_backtesting_with_zipline.ipynb it states that:
"We generate the train predictions in the notebook alphalens_signal_quality and the test predictions in the notebook random_forest_return_signals."

However I do not see code for generating train predictions. Am I missing something?
Regards,
Zilvinas

**Comment by stefan-jansen** [comment]
Sorry, that's misleading. We are generating both train and test predictions in the `notebook random_forest_return_signals.ipynb`; the former during cross-validation, the later in the last section. The alphalens notebook just allows you to reload both; I'll clarify this in the notebook.
