### ISSUE TITLE
Quantopian was closed one month ago, do you have another code?

### ISSUE THREAD

**Issue by silent0506** [stefan-jansen/machine-learning-for-trading#81]
hi Stefan

when I Run the 02_multiple_factors_quantopian_research.ipynb, i got _No module named 'quantopian'_ error.

so I check Qunatopian.com, Quantopian.com is not served service util one month ago 

Below is my code.

```
from quantopian.research import run_pipeline
from quantopian.pipeline import Pipeline
from quantopian.pipeline.data.builtin import USEquityPricing
from quantopian.pipeline.data.morningstar import income_statement, operation_ratios, balance_sheet
from quantopian.pipeline.data.psychsignal import stocktwits
from quantopian.pipeline.factors import CustomFactor, SimpleMovingAverage, Returns
from quantopian.pipeline.filters import QTradableStocksUS

import numpy as np
import pandas as pd
from time import time
```

and Below is the error code.

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-127e0578188b> in <module>()
----> 1 from quantopian.research import run_pipeline
      2 from quantopian.pipeline import Pipeline
      3 from quantopian.pipeline.data.builtin import USEquityPricing
      4 from quantopian.pipeline.data.morningstar import income_statement, operation_ratios, balance_sheet
      5 from quantopian.pipeline.data.psychsignal import stocktwits

ImportError: No module named 'quantopian'
```

do you have an alternative code? or how can fix it?

Sincerely yours,

Thank you for your book and reply always.

**Comment by stefan-jansen** [comment]
Unfortunately, this example relies on the Quantopian platform, especially on the data they used to provide there. However, all the other examples accomplish similar things - load data, compute factors, produce signals, and backtest a strategy. In other words, you have plenty of alternatives, no need to recreate this particular example in a different environment. I'll add a warning to the notebook that this no longer works.
