### ISSUE TITLE
No params with get_params 

### ISSUE THREAD

**Issue by jmg17** [stefan-jansen/machine-learning-for-trading#83]
In 
=> 12_gradient_boosting_machines
=> 05_trading_signals_with_lightgbm_and_catboost.ipynb
=> Generate LightGBM predictions
=> Generate predictions
I have an error with « get_params ».
I try to write  a module « def get_params »  (that does not exist) but with inconsistent result.
What is the solution ?
Thank for your replay

**Comment by stefan-jansen** [comment]
I"m sorry, the function is in the notebook [05_random_forest_return_signals](https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/11_decision_trees_random_forests/05_random_forest_return_signals.ipynb) after 'Generate Predictions':
```
def get_params(data, t=5, best=0):
    df = data[data.t == t].sort_values('ic', ascending=False).iloc[best]
    df = df.loc[param_cols]
    rounds = int(df.rounds)
    params = pd.to_numeric(df.drop('rounds'))
    return params, rounds
```
Not sure why it's missing from `05_trading_signals_with_lightgbm_and_catboost.ipynb`, I'll add it shortly.

**Comment by jmg17** [comment]
Thank you for updating chapter 12.
And thank you very much for your whole book which is a real mine of
knowledge which makes me a little less dumb in trading programming.

Le mar. 29 déc. 2020 à 00:07, Stefan Jansen <notifications@github.com> a
écrit :
