### ISSUE TITLE
conda environment on mac

### ISSUE THREAD

**Issue by rydeen7** [stefan-jansen/machine-learning-for-trading#84]
I'm trying to create conda environment on mac, but it fails.
Part of error messages are as below. 

ld: warning: -pie being ignored. It is only used when linking a main executable
    ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks//IOKit.framework/IOKit.tbd' for architecture x86_64
    clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1

**Comment by stefan-jansen** [comment]
I can't tell what's going on if you don't show the command you ran and only display part of the error message.

I recommend using the Docker image; the environment files are only intended for the case where you are familiar with creating  and troubleshooting conda environments.
