### ISSUE TITLE
selenium installation

### ISSUE THREAD

**Issue by justcurious123** [stefan-jansen/machine-learning-for-trading#85]
HI

I ran into a permission issue when installing selenium:

![Untitled](https://user-images.githubusercontent.com/54954137/103769217-4ffadd80-503d-11eb-8830-ccb8f172541a.jpg)

**Comment by stefan-jansen** [comment]
See second answer [here](https://stackoverflow.com/questions/25845538/how-to-use-sudo-inside-a-docker-container) to run with `sudo`. 

Exit from running container, then use `docker start -i -a ml4t` to restart; then the `docker exec...` command from SO.

**Comment by justcurious123** [comment]
Thanks for response. I proceeded with your instructions and ran into another error: "sudo: setrlimit(RLIMIT_CORE): Operation not permitted". Then found the following solution: "echo "Set disable_coredump false" >> /etc/sudo.conf". So I was able move geckodriver to /usr/local/bin/  (as specified in selenium_setup.sh). Then I installed selenium in ml4t environment with pip (as it was absent). Finally when I ran selenium_setup.sh, I got this error  "Unable to find a matching set of capabilities". Then I added the following arguments to driver = webdriver.Firefox(capabilities=DesiredCapabilities().FIREFOX, executable_path='/usr/local/bin'). Now I got this error: "Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox" (with or without "executable_path" argument). So if you have time please respond.

**Comment by stefan-jansen** [comment]
Just checked and realized that the web-scraping part is the only example that I did not properly test using Docker, just on my Ubuntu host. My apologies, it's of course much more difficult to run a browser-based application on a VM. Now we have two options: if you are using Linux (or Mac, which should also work with minor changes such as using homebrew) you switch to your host as well (and I'll update the instructions accordingly). Alternatively, I find some time in the coming days and see if I can update the image to properly work with a headless browser. 

To make matters a bit more disappointing, unfortunately, please also note that in the meantime seekingalpha changed their website and now requires captions, so this example doesn't work any longer; last time I checked a few months ago, opentable was still operational.
