### ISSUE TITLE
Chapter 12. Long-Short Strategy, Part 3

### ISSUE THREAD

**Issue by jmg17** [stefan-jansen/machine-learning-for-trading#86]
In :
=> Chapter 12 Gradient boosting machines
=> Long-Short Strategy, Part 3: Evaluating our Boosting Model Signals

1) Probably « path » mistake in  Summary metrics by fold…
	=> with pd.HDFStore('data/tuning_lgb.h5') as store... is instead
	=> with pd.HDFStore('results/us_stocks/tuning_lgb.h5') as store ?

2) In « HyperParameter Impact: Linear Regression »
 	This cell gives memory bug with your example (ubuntu 20.04, conda env with 16 GB memory)
	
	lin_reg = {}
	for t in [1, 21]:
    		df_ = lgb_ic[lgb_ic.lookahead==t]
   		……..
   	 	coefs.to_csv(f'results/linreg_result_{t:02}.csv', index=False)

I don’t understand what is happening. Insufficient memory ?
Thank for your reply.

**Comment by jmg17** [comment]
For question "2", it is a memory problem because  the calculation in 2 successive steps (for 1 and after 21) solves the problem.

**Comment by stefan-jansen** [comment]
You're right about the path mistake, updated the notebook to also use `results_path` as in model training part.
