### ISSUE TITLE
Chapter12. Long-Short Strategy, Part 6

### ISSUE THREAD

**Issue by jmg17** [stefan-jansen/machine-learning-for-trading#87]
In : Long-short-stratégy, part6 :

How to create « data/predictions.h5', 'lgb/train/01 » that is required by zipline 
and not  create in Part 5: Generating out-of-sample predictions ?

Thank for your replay

**Comment by jmg17** [comment]
Solved. Issue with path error.

**Comment by stefan-jansen** [comment]
They are generated while training the model and retrieved/stored under this label in Part 4. See cell [57] [here](https://github.com/stefan-jansen/machine-learning-for-trading/blob/master/12_gradient_boosting_machines/06_evaluate_trading_signals.ipynb).
