### ISSUE TITLE
04_single_factor_zipline: factor_pipeline key error

### ISSUE THREAD

**Issue by ironjaw33** [stefan-jansen/machine-learning-for-trading#89]
When I run 04_single_factor_zipline, I get the following error:

`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/algorithm.py in _pipeline_output(self, pipeline, chunks, name)
   2324         try:
-> 2325             data = self._pipeline_cache.get(name, today)
   2326         except KeyError:

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/utils/cache.py in get(self, key, dt)
    152         try:
--> 153             return self._cache[key].unwrap(dt)
    154         except Expired:

KeyError: 'factor_pipeline'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-6-2eb7efda75f8> in <module>
----> 1 get_ipython().run_cell_magic('zipline', '--start 2015-1-1 --end 2018-1-1 --output single_factor.pickle', '\nfrom zipline.api import (\n    attach_pipeline,\n    date_rules,\n    time_rules,\n    order_target_percent,\n    pipeline_output,\n    record,\n    schedule_function,\n    get_open_orders,\n    calendars\n)\nfrom zipline.finance import commission, slippage\nfrom zipline.pipeline import Pipeline, CustomFactor\nfrom zipline.pipeline.factors import Returns, AverageDollarVolume\nimport numpy as np\nimport pandas as pd\n\nMONTH = 21\nYEAR = 12 * MONTH\nN_LONGS = N_SHORTS = 25\nVOL_SCREEN = 1000\n\n\nclass MeanReversion(CustomFactor):\n    """Compute ratio of latest monthly return to 12m average,\n       normalized by std dev of monthly returns"""\n    inputs = [Returns(window_length=MONTH)]\n    window_length = YEAR\n\n    def compute(self, today, assets, out, monthly_returns):\n        df = pd.DataFrame(monthly_returns)\n        out[:] = df.iloc[-1].sub(df.mean()).div(df.std())\n\n\ndef compute_factors():\n    """Create factor pipeline incl. mean reversion,\n        filtered by 30d Dollar Volume; capture factor ranks"""\n    mean_reversion = MeanReversion()\n    dollar_volume = AverageDollarVolume(window_length=30)\n    return Pipeline(columns={\'longs\': mean_reversion.bottom(N_LONGS),\n                             \'shorts\': mean_reversion.top(N_SHORTS),\n                             \'ranking\': mean_reversion.rank(ascending=False)},\n                    screen=dollar_volume.top(VOL_SCREEN))\n\n\ndef exec_trades(data, assets, target_percent):\n    """Place orders for assets using target portfolio percentage"""\n    for asset in assets:\n        if data.can_trade(asset) and not get_open_orders(asset):\n            order_target_percent(asset, target_percent)\n\n\ndef rebalance(context, data):\n    """Compute long, short and obsolete holdings; place trade orders"""\n    factor_data = context.factor_data\n    record(factor_data=factor_data.ranking)\n\n    assets = factor_data.index\n    record(prices=data.current(assets, \'price\'))\n\n    longs = assets[factor_data.longs]\n    shorts = assets[factor_data.shorts]\n    divest = set(context.portfolio.positions.keys()) - set(longs.union(shorts))\n\n    exec_trades(data, assets=divest, target_percent=0)\n    exec_trades(data, assets=longs, target_percent=1 / N_LONGS)\n    exec_trades(data, assets=shorts, target_percent=-1 / N_SHORTS)\n\n\ndef initialize(context):\n    """Setup: register pipeline, schedule rebalancing,\n        and set trading params"""\n    attach_pipeline(compute_factors(), \'factor_pipeline\')\n    schedule_function(rebalance,\n                      date_rules.week_start(),\n                      time_rules.market_open(),\n                      calendar=calendars.US_EQUITIES)\n    context.set_commission(commission.PerShare(cost=.01, min_trade_cost=0))\n    context.set_slippage(slippage.VolumeShareSlippage())\n\n\ndef before_trading_start(context, data):\n    """Run factor pipeline"""\n    context.factor_data = pipeline_output(\'factor_pipeline\')\n')

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2319             magic_arg_s = self.var_expand(line, stack_depth)
   2320             with self.builtin_trap:
-> 2321                 result = fn(magic_arg_s, cell)
   2322             return result
   2323 

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/__main__.py in zipline_magic(line, cell)
    309             '%s%%zipline' % ((cell or '') and '%'),
    310             # don't use system exit and propogate errors to the caller
--> 311             standalone_mode=False,
    312         )
    313     except SystemExit as e:

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/click/core.py in main(self, args, prog_name, complete_var, standalone_mode, **extra)
    780             try:
    781                 with self.make_context(prog_name, args, **extra) as ctx:
--> 782                     rv = self.invoke(ctx)
    783                     if not standalone_mode:
    784                         return rv

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/click/core.py in invoke(self, ctx)
   1064         _maybe_show_deprecated_notice(self)
   1065         if self.callback is not None:
-> 1066             return ctx.invoke(self.callback, **ctx.params)
   1067 
   1068 

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/click/core.py in invoke(*args, **kwargs)
    608         with augment_usage_errors(self):
    609             with ctx:
--> 610                 return callback(*args, **kwargs)
    611 
    612     def forward(*args, **kwargs):  # noqa: B902

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/click/decorators.py in new_func(*args, **kwargs)
     19 
     20     def new_func(*args, **kwargs):
---> 21         return f(get_current_context(), *args, **kwargs)
     22 
     23     return update_wrapper(new_func, f)

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/__main__.py in run(ctx, algofile, algotext, define, data_frequency, capital_base, bundle, bundle_timestamp, start, end, output, trading_calendar, print_algo, metrics_set, local_namespace, blotter)
    274         environ=os.environ,
    275         blotter=blotter,
--> 276         benchmark_returns=None,
    277     )
    278 

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/utils/run_algo.py in _run(handle_data, initialize, before_trading_start, analyze, algofile, algotext, defines, data_frequency, capital_base, bundle, bundle_timestamp, start, end, output, trading_calendar, print_algo, metrics_set, local_namespace, environ, blotter, benchmark_returns, custom_loader)
    209             } if algotext is None else {
    210                 'algo_filename': getattr(algofile, 'name', '<algorithm>'),
--> 211                 'script'       : algotext,
    212             }
    213     ).run()

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/algorithm.py in run(self, data_portal)
    637         try:
    638             perfs = []
--> 639             for perf in self.get_generator():
    640                 perfs.append(perf)
    641 

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/gens/tradesimulation.py in transform(self)
    221                     self.simulation_dt = dt
    222                     algo.on_dt_changed(dt)
--> 223                     algo.before_trading_start(self.current_data)
    224                 elif action == MINUTE_END:
    225                     minute_msg = self._get_minute_message(

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/algorithm.py in before_trading_start(self, data)
    430 
    431     def before_trading_start(self, data):
--> 432         self.compute_eager_pipelines()
    433 
    434         if self._before_trading_start is None:

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/algorithm.py in compute_eager_pipelines(self)
    605         for name, pipe in self._pipelines.items():
    606             if pipe.eager:
--> 607                 self.pipeline_output(name)
    608 
    609     def get_generator(self):

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/utils/api_support.py in wrapped_method(self, *args, **kwargs)
    101             if not self.initialized:
    102                 raise exception
--> 103             return method(self, *args, **kwargs)
    104         return wrapped_method
    105     return decorator

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/algorithm.py in pipeline_output(self, name)
   2315                 valid=list(self._pipelines.keys()),
   2316             )
-> 2317         return self._pipeline_output(pipe, chunks, name)
   2318 
   2319     def _pipeline_output(self, pipeline, chunks, name):

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/algorithm.py in _pipeline_output(self, pipeline, chunks, name)
   2327             # Calculate the next block.
   2328             data, valid_until = self.run_pipeline(
-> 2329                 pipeline, today, next(chunks),
   2330             )
   2331             self._pipeline_cache.set(name, data, valid_until)

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/algorithm.py in run_pipeline(self, pipeline, start_session, chunksize)
   2374 
   2375         return \
-> 2376             self.engine.run_pipeline(pipeline, start_session, end_session), \
   2377             end_session
   2378 

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/pipeline/engine.py in run_pipeline(self, pipeline, start_date, end_date, hooks)
    386                 start_date,
    387                 end_date,
--> 388                 hooks,
    389             )
    390 

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/pipeline/engine.py in _run_pipeline_impl(self, pipeline, start_date, end_date, hooks)
    407         extra_rows = plan.extra_rows[self._root_mask_term]
    408         root_mask = self._compute_root_mask(
--> 409             domain, start_date, end_date, extra_rows,
    410         )
    411         dates, sids, root_mask_values = explode(root_mask)

/opt/conda/envs/ml4t-zipline/lib/python3.5/site-packages/zipline/pipeline/engine.py in _compute_root_mask(self, domain, start_date, end_date, extra_rows)
    526                 "This probably means that your asset db is old or that it has "
    527                 "incorrect country/exchange metadata.".format(
--> 528                     domain.country_code, start_date, end_date,
    529                 )
    530             )

ValueError: Failed to find any assets with country_code 'US' that traded between 2015-01-02 00:00:00+00:00 and 2015-01-09 00:00:00+00:00.
This probably means that your asset db is old or that it has incorrect country/exchange metadata.
`

**Comment by stefan-jansen** [comment]
Please see instructions under 'Known Zipline Issues' in the installation [README](https://github.com/stefan-jansen/machine-learning-for-trading/tree/master/installation#known-zipline-issues).

**Comment by ironjaw33** [comment]
Thanks, this worked.
