### ISSUE TITLE
Chapter 5 Solver failure

### ISSUE THREAD

**Issue by ironjaw33** [stefan-jansen/machine-learning-for-trading#90]
I'm going through the following notebook:

05_strategy_evaluation/02_backtest_with_pf_optimization.ipynb

When I run the backtest, I get the following error:

`SolverError: Solver 'OSQP' failed. Try another solver, or solve with verbose=True for more information.`

Using get_datetime(), this error occurs on the 2014-12-08 rebalance.  I've tried several other solvers (ECOS and CVXOPT), which also error out.  Also of note, the ml4t-zipline environment, which I am using through the Docker container, did not have the PyPortfolioOpt library installed.  I installed it via pip.

Edit: on some days, the determinant of the price covariance matrix is zero, including on days where the solver doesn't crash out.  Playing around with the gamma parameter doesn't change anything.  It still bails on the same day.  When running in verbose mode, OSQP states "maximum iterations reached."

**Comment by stefan-jansen** [comment]
Indeed. I used an older version of `PyPortFolioOpt` that silently failed when `cvxopt` did not solve the problem. I have added some try/except to catch these errors and continue the backtest. I have also modified the related notebook in Chapter 13 on hierarchical risk parity accordingly, and added alerts regarding the required installs. I'll try to update the Docker images as well.

I hope this solves this issues, feel free to reopen if you run into additional bugs.
