### ISSUE TITLE
The data urls in /04_alpha_factor_research/01_feature_engineering.ipynb are broken

### ISSUE THREAD

**Issue by PerrySong** [stefan-jansen/machine-learning-for-trading#93]
Hi, the following links in /04_alpha_factor_research/01_feature_engineering.ipynb are broken. 

https://render.githubusercontent.com/data/create_datasets.ipynb
https://render.githubusercontent.com/data

**Comment by stefan-jansen** [comment]
That's right, thanks. There were a couple broken chapter links as well. Should be all fixed now. Feel free to reopen or post a new issue if you come across other broken links or other things (but I sure hope you don't...). Hope you find the material useful!

**Comment by PerrySong** [comment]
Thanks much
