### ISSUE TITLE
Zipline and Pandas

### ISSUE THREAD

**Issue by edaustin** [stefan-jansen/machine-learning-for-trading#95]
Zipline seems abandoned, however it can be made to work but requires Pandas <= 0.21.0, this breaks virtually everything else (that requires later pandas). Any workarounds?

Great book!

**Comment by stefan-jansen** [comment]
Thanks! I think for now it's best to Run zipline in a separate environment. I think there are some attempts to update it and I'd like to also take a look at this for the next edition given the dearth of alternatives. Unfortunately this will consume some time which is a bit hard to find these days..

**Comment by edaustin** [comment]
Hi

Solution!

Simply create two conda virtual environments, one for zipline and another for normal work.
This works great with PyCharm and allows switching between the two dependent on what you need to do.

Also started using vectorbt, this looks promising.

Regards
Ed Austin

**Comment by stefan-jansen** [comment]
This is how the docker image is set up as described [here](https://github.com/stefan-jansen/machine-learning-for-trading/tree/master/installation) which comes with three environments (separate one of DL). On Ubuntu, you can only get things to work without `conda` which can speed up updates. I use [pyenv](https://github.com/pyenv/pyenv) to manage different python versions and their respective environments.

Hope you'll find the material useful - please don't hesitate to ask questions if you run into any bugs or other issues.
