### ISSUE TITLE
PandasRollingOLS depracated

### ISSUE THREAD

**Issue by N2Network** [stefan-jansen/machine-learning-for-trading#96]
Is there a fix for PandasRollingOLS being deprecated? 

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/my-project-env/lib/python3.8/site-packages/pyfinance/utils.py in <module>
     77 try:
---> 78     from .tseries.frequencies import FreqGroup, get_freq_code
     79 except ImportError:  # 0.24+, or somewhere around then

ImportError: cannot import name 'FreqGroup' from 'pandas.tseries.frequencies' (/root/my-project-env/lib/python3.8/site-packages/pandas/tseries/frequencies.py)

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-7eb2ab888285> in <module>
      7 import pandas as pd
      8 import pandas_datareader.data as web
----> 9 from pyfinance.ols import PandasRollingOLS

~/my-project-env/lib/python3.8/site-packages/pyfinance/__init__.py in <module>
     30 
     31 # Echoing Pandas, bring these to top-level namespace.
---> 32 from .returns import TFrame, TSeries  # noqa

~/my-project-env/lib/python3.8/site-packages/pyfinance/returns.py in <module>
     40 import pandas as pd
     41 
---> 42 from pyfinance import ols, utils
     43 
     44 SECS_PER_CAL_YEAR = 365.25 * 24 * 60 * 60

~/my-project-env/lib/python3.8/site-packages/pyfinance/ols.py in <module>
     13 from statsmodels.tools import add_constant
     14 
---> 15 from pyfinance import utils
     16 
     17 

~/my-project-env/lib/python3.8/site-packages/pyfinance/utils.py in <module>
     78     from .tseries.frequencies import FreqGroup, get_freq_code
     79 except ImportError:  # 0.24+, or somewhere around then
---> 80     from ._libs.tslibs.frequencies import FreqGroup, get_freq_code
     81 
     82 

ModuleNotFoundError: No module named 'pandas._libs.tslibs.frequencies'pandaspandaspandas`

**Comment by stefan-jansen** [comment]
Yes, you can use `statsmodels.regression.rolling.RollingOLS¶` as demonstrated in [Chapter 18](https://github.com/stefan-jansen/machine-learning-for-trading/blob/c7e508dbe98e064887faeca65a45966e85af1c96/18_convolutional_neural_nets/05_engineer_cnn_features.ipynb). I'll update the code as soon as I find the time.

**Comment by N2Network** [comment]
Thanks for the super quick response. I haven't gotten that far in the book yet. I did try to implement statsmodels.regression.rolling.RollingOLS but it made the code not work further down. Any help would be appreciated. 

`TypeError: __init__() got an unexpected keyword argument 'y'`

`T = 24
betas = (factor_data
         .groupby(level='ticker', group_keys=False)
         .apply(lambda x: RollingOLS(window=min(T, x.shape[0]-1), y=x.return_1m, x=x.drop('return_1m', axis=1)).beta))`

**Comment by stefan-jansen** [comment]
Right, you can't just swap it out but the logic is somewhat similar - this is not adapted to ch 4 but directly from the similar feature engineering notebook (# 5)  in ch 18 linked above. The following is from cell 45, take a look at the preceding couple of cells and it should be straightforward to adjust for ch 4:
```
t = 1
ret = f'r{t:02}'
factors = ['Market', 'SMB', 'HML', 'RMW', 'CMA']
windows = list(range(15, 90, 5))
for window in windows:
    print(window)
    betas = []
    for symbol, data in universe.groupby(level='symbol'):
        model_data = data[[ret]].merge(factor_data, on='date').dropna()
        model_data[ret] -= model_data.RF

        rolling_ols = RollingOLS(endog=model_data[ret], 
                                 exog=sm.add_constant(model_data[factors]), window=window)
        factor_model = rolling_ols.fit(params_only=True).params.drop('const', axis=1)
        result = factor_model.assign(symbol=symbol).set_index('symbol', append=True)
        betas.append(result)
    betas = pd.concat(betas).rename(columns=lambda x: f'{window:02}_{x}')
    universe = universe.join(betas)
```
Hope this helps, don't have the time to update ch 4 right now; also: if you stick with the package version specified in the environment (or use docker) you shouldn't run into any deprecation issues.
