### ISSUE TITLE
f'r{t:02} Could you please help me by breaking down the meaning to each piece for building factors better?

### ISSUE THREAD

**Issue by cody-vandervoort** [stefan-jansen/machine-learning-for-trading#97]
I'm trying to create my own factors and I'm very curious what `f'r{t:02}` means from the `for t in T:
    prices[f'r{t:02}dec'] = (prices[f'r{t:02}'].groupby(level='date')
             .apply(lambda x: pd.qcut(x, q=10, labels=False, duplicates='drop')))`

and a few other sections I'm trying to use a new data set for currencies and i would really appreciate gaining that knowledge, thanks so much for writing this book.

**Comment by stefan-jansen** [comment]
`f'r{t:02}` is a [format string](https://realpython.com/python-f-strings/) that takes the value for `t`, inserts it and formats it to two digits with a leading zero while keeping the remainder of the string as is. So for `t=2` you get `'r02dec'`.

**Comment by cody-vandervoort** [comment]
nice thank you! I have just encountered a problem running the univariate time series regression in chapter 19 the error is as follows when importing tensorflow and such `---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-07b70ac3ef43> in <module>
     11 from sklearn.preprocessing import MinMaxScaler
     12 
---> 13 import tensorflow as tf
     14 from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
     15 from tensorflow.keras.models import Sequential

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/tensorflow/__init__.py in <module>
     99 
    100 # We still need all the names that are toplevel on tensorflow_core
--> 101 from tensorflow_core import *
    102 
    103 # These should not be visible in the main tf module.

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/tensorflow_core/__init__.py in <module>
     44 from . _api.v2 import autograph
     45 from . _api.v2 import bitwise
---> 46 from . _api.v2 import compat
     47 from . _api.v2 import config
     48 from . _api.v2 import data

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/tensorflow_core/_api/v2/compat/__init__.py in <module>
     37 import sys as _sys
     38 
---> 39 from . import v1
     40 from . import v2
     41 from tensorflow.python.compat.compat import forward_compatibility_horizon

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/tensorflow_core/_api/v2/compat/v1/__init__.py in <module>
     30 from . import autograph
     31 from . import bitwise
---> 32 from . import compat
     33 from . import config
     34 from . import data

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/tensorflow_core/_api/v2/compat/v1/compat/__init__.py in <module>
     37 import sys as _sys
     38 
---> 39 from . import v1
     40 from . import v2
     41 from tensorflow.python.compat.compat import forward_compatibility_horizon

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/tensorflow_core/_api/v2/compat/v1/compat/v1/__init__.py in <module>
     27 
     28 from . import compat
---> 29 from tensorflow._api.v2.compat.v1 import app
     30 from tensorflow._api.v2.compat.v1 import audio
     31 from tensorflow._api.v2.compat.v1 import autograph

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/tensorflow_core/_api/v2/compat/__init__.py in <module>
     37 import sys as _sys
     38 
---> 39 from . import v1
     40 from . import v2
     41 from tensorflow.python.compat.compat import forward_compatibility_horizon

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/tensorflow_core/_api/v2/compat/v1/__init__.py in <module>
     30 from . import autograph
     31 from . import bitwise
---> 32 from . import compat
     33 from . import config
     34 from . import data

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/tensorflow_core/_api/v2/compat/v1/compat/__init__.py in <module>
     37 import sys as _sys
     38 
---> 39 from . import v1
     40 from . import v2
     41 from tensorflow.python.compat.compat import forward_compatibility_horizon

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/tensorflow_core/_api/v2/compat/v1/compat/v1/__init__.py in <module>
    665 _current_module = _sys.modules[__name__]
    666 try:
--> 667   from tensorflow_estimator.python.estimator.api._v1 import estimator
    668   _current_module.__path__ = (
    669       [_module_util.get_parent_dir(estimator)] + _current_module.__path__)

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/tensorflow_estimator/__init__.py in <module>
      8 import sys as _sys
      9 
---> 10 from tensorflow_estimator._api.v1 import estimator
     11 
     12 del _print_function

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py in <module>
      8 import sys as _sys
      9 
---> 10 from tensorflow_estimator._api.v1.estimator import experimental
     11 from tensorflow_estimator._api.v1.estimator import export
     12 from tensorflow_estimator._api.v1.estimator import inputs

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py in <module>
      8 import sys as _sys
      9 
---> 10 from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
     11 from tensorflow_estimator.python.estimator.canned.kmeans import KMeansClustering as KMeans
     12 from tensorflow_estimator.python.estimator.canned.linear import LinearSDCA

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py in <module>
     31 from tensorflow.python.keras.utils import losses_utils
     32 from tensorflow.python.util.tf_export import estimator_export
---> 33 from tensorflow_estimator.python.estimator import estimator
     34 from tensorflow_estimator.python.estimator.canned import head as head_lib
     35 from tensorflow_estimator.python.estimator.canned import optimizers

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py in <module>
     51 from tensorflow_estimator.python.estimator import model_fn as model_fn_lib
     52 from tensorflow_estimator.python.estimator import run_config
---> 53 from tensorflow_estimator.python.estimator import util as estimator_util
     54 from tensorflow_estimator.python.estimator.export import export_lib
     55 from tensorflow_estimator.python.estimator.mode_keys import ModeKeys

/opt/conda/envs/ml4t-dl/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/util.py in <module>
     73 
     74 
---> 75 class _DatasetInitializerHook(tf.compat.v1.train.SessionRunHook):
     76   """Creates a SessionRunHook that initializes the passed iterator."""
     77 

AttributeError: module 'tensorflow' has no attribute 'compat'`

**Comment by cody-vandervoort** [comment]
I'm stuck at chapter 19 univariate time series, in terms on getting my own data to work, i have four hour data for two years up to today, this is the format it's in, im more or less lost when it comes to pre processing now, i was able to save the same data here inside of an h5 file but when i tried to get it out I was having a problem because it couldn't locate the idx, as i was trying to use your code for a template on some gbd_jpy data, anyways if you wouldn't mind could you help me to understand how i can get my data which is now just in csv pre processed to train the RNN? I really appreciate the knowledge thanks so much 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3323 entries, 0 to 3322
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   DATE    3323 non-null   object 
 1   close   3323 non-null   float64
dtypes: float64(1), object(1)
memory usage: 52.0+ KB
